---
title: ""
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{meds_at_visit}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# RISK Med Journey

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
options(rmarkdown.html_vignette.check_title = FALSE)
```

The RISK medication journey table documents the long term medication journey of [RISK](https://www.crohnscolitisfoundation.org/research/current-research-initiatives/pediatric-risk-stratification) pediatric patients for biologics, aminosalicylates and immunomodulators. The medication start and end dates are from the case report forms for the RISK study. The columns included in the RISK medication journey are:

| Column                          | Description                                                                                                                                                                                                                                                                                                                    |
|-------------------|-----------------------------------------------------|
| DEIDENTIFIED_MASTER_PATIENT_ID  | Unique patient ID                                                                                                                                                                                                                                                                                                              |
| MEDICATION_NAME                 | Name of the medication patient was on                                                                                                                                                                                                                                                                                          |
| MED_START_DATE                  | The earliest reported start date of a medication from the RISK case report form. If no medication start date was supplied but it was indicated the medication was administered, the medication start date is the visit encounter date associated with the first time the medication was administered.                          |
| MED_END_DATE                    | The reported medication end date. If a patient has multiple medication end dates but only one medication start date, the latest medication end date is used. If the patient has multiple medication start and end dates, each interval for the medication is a separate row in the medication journey table.                   |
| MED_ORDER                       | An index that counts the order in which a patient received medications based on medication start date. The first medication a patient received == 1.                                                                                                                                                                           |
| MED_GROUP                       | The class of medication. Either biologic, 5-ASA (aminosalicylates), or immunomodulators.                                                                                                                                                                                                                                       |
| MEDS_OVERLAP                    | List of medications that overlap with the medication a patient is on at any point in the interval.                                                                                                                                                                                                                             |
| OVERLAPPING_MOA                 | List of overlapping mechanisms of action that overlap with the medication is on at any point in the interval.                                                                                                                                                                                                                  |
| OVERLAP_DAYS\_[MEDICATION NAME] | Count of the number of days an additional medication overlapped with the original medication interval. The possible overlapping medications include: Adalimumab, Azathioprine, Certolizumab Pegol, Infliximab (Unspecified), Mercaptopurine, Mesalamine, Methotrexate, Natalizumab, Olsalazine, Sulfasalazine, and Tacrolimus. |
| ANTIBIOTICS_OVERLAP             | 1 if the patient was also on antibiotics at any point in the medication interval.                                                                                                                                                                                                                                              |
| STEROID_OVERLAP                 | 1 if the patient was also on steroids at any point in the medication interval.                                                                                                                                                                                                                                                 |

#### Anti-TNF Logic

Some patients reported being on two different anti-TNF medications at some point in their medication journey. In the case that there was no reported medication end date for one anti-TNF medication and another anti-TNF medication was started, then the day before the start date of the next anti-TNF is used as the medication end date for the prior medication.

#### Overlapping Medications

Medications are considered overlapping if there is at least 1 day where the medication intervals overlap. If a medication was started on the same day another medication was stopped, these medications are not considered overlapping.
