#' familyibdhist_emr_extract
#'
#' A function to extract records from the Family History EMR table indicating a family member with a history of IBD. User can define to include all family members or only First Degree Family members.
#' First degree is defined as: Biological Parent, Sibling or Child. All options exclude Negative History or No history.
#'
#' @param data A list of dataframes, typically generated by a call to load_data. Must include demographics, and the Patient History tables. Only EMR data needs to be uploaded.
#' @param relation Define whether to search for "FIRST_DEG", only include first degree family members. The default is to search for all family members.
#' @param negativemention If "TRUE", only include records specifically citing NO family history of IBD. The default is FALSE.
#'
#' @return A list of dataframes with all relevant EMR Patient History records.
#' @export
#'
#' @examples
#'
#' #example for patient family history of IBD
#'
#' #data = load_data(datadir="C:/Users/me/",domains=c("Patient_History","Demographics"),data_type="EMR")
#' #famhist = familyibdhist_emr_extract(data)

#' #example for only first degree family member history of IBD
#'
#' #famhist1stdeg = familyibdhist_emr_extract(data,relation="FIRST_DEG")
#'
#' #example for specific mention of "No" family member history of IBD
#'
#' #famhistnoibd = familyibdhist_emr_extract(data,negativemention=TRUE)




familyibdhist_emr_extract <- function(data,
                                  relation = NULL, negativemention=FALSE) {
  #look in history data for family history of ibd
  if(is.null(relation)==FALSE){
    relation=toupper(relation)
  }
  if(negativemention==TRUE){
    temp <- data$patient_history %>%
      filter(DATA_SOURCE=="EMR") %>%
      filter(HISTORY_TYPE=="Family") %>%
      filter(grepl("colitis|crohn|bowel dis",HISTORY_CONCEPT_NAME,ignore.case=TRUE)) %>%
      filter(!RELATION %in% c('No History of','Neg Hx'))
    result <- data$patient_history %>%
      filter(DATA_SOURCE=="EMR") %>%
      filter(HISTORY_TYPE=="Family") %>%
      filter(grepl("colitis|crohn|bowel dis",HISTORY_CONCEPT_NAME,ignore.case=TRUE)) %>%
      filter(RELATION %in% c('No History of','Neg Hx')) %>%
      filter(!DEIDENTIFIED_MASTER_PATIENT_ID %in% temp$DEIDENTIFIED_MASTER_PATIENT_ID)
  }
  if(negativemention==FALSE){
    result <- data$patient_history %>%
    filter(DATA_SOURCE=="EMR") %>%
    filter(HISTORY_TYPE=="Family") %>%
    filter(grepl("colitis|crohn|bowel dis",HISTORY_CONCEPT_NAME,ignore.case=TRUE)) %>%
    filter(!RELATION %in% c('No History of','Neg Hx'))
    if(is.null(relation)==FALSE){
      if(relation=="FIRST_DEG"){
        result1 <- result
        result <- result1 %>%
          filter(RELATION %in% c("Biological Father","Biological Mother","Brother","Child","Son","Sister","Daughter","Father of the baby","Father","Mother"))
      }
    }
  }
  return(result)
}
