#' familyibdhist_emr_extract
#'
#' A function to extract records from the Family History EMR table indicating a family member with a history of IBD. User can define to include all family members or only First Degree Family members.
#' First degree is defined as: Biological Parent, Sibling or Child.
#'
#' @param data A list of dataframes, typically generated by a call to load_data. Must include demographics, and the Patient History tables. Only EMR data needs to be uploaded.
#' @param relation Define whether to search for "FIRST_DEG", only including first degree family members.The default is to search for all family members.
#'
#' @return A list of dataframes with all relevant EMR Patient History records.
#' @export
#'
#' @examples
#'
#' #example for patient family history
#'
#' #famhist = familyibdhist_emr_extract(data)

#' #example for only first degree family member history
#'
#' #famhist1stdeg = familyibdhist_emr_extract(data,relation="FIRST_DEG")



familyibdhist_emr_extract <- function(data,
                                  relation = NULL) {
  #look in history data for family history of ibd
  result <- data$patient_history %>%
    filter(DATA_SOURCE=="EMR") %>%
    filter(HISTORY_TYPE=="Family") %>%
    filter(grepl("colitis|crohn|bowel dis",HISTORY_CONCEPT_NAME,ignore.case=TRUE))
  if(is.null(relation)==FALSE){
    if(relation=="FIRST_DEG"){
      result1 <- result
      result <- result1 %>%
        filter(RELATION %in% c("Biological Father","Biological Mother","Brother","Child","Son","Sister","Daughter","Father of the baby","Father","Mother"))
    }
  }
  return(result)
}
