#' lab_emr_extract
#'
#' A function to extract relevant lab results from
#' lab EMR data for a specific test of interest.
#'
#' 1. user defines type of lab results to select (CRP, HS CRP, NS CRP, FCAL). Alb blood/serum, Glucose blood, Glucose urine to be added in a future update.
#' 2. user defines blood, serum, urine, stool, etc (only for specific types of tests and will be added in a future update.)
#' 3. user defines if searching for only LOINC codes, all codes or key words as well
#' 4. user defines if all or positive results (default "positive/elevated" definition or custom(add later if possible))
#' 5. user defines if only valid units for positive results or all positive results
#'
#' @param data A list of dataframes, typically generated by a call to load_data. Must include demographics, and the lab tables. Only EMR data needs to be uploaded.
#' @param labtype The type of lab results to select ("CRP","HS CRP","NS CRP","FCAL"). If the user inputs any other value, the lab EMR table will be returned.
#' @param codetype The criteria to use for querying codes. The options are "LOINC" for only related LOINC codes,"KEYWORDS" for only related words in the Code Description field, or "ALL" for both critera.
#' @param positive_elevated If "TRUE", the results will only be for results above a "positive" and/or "elevated" threshold, dependent on the test category.
#' @param datecutoff Type of date cutoff to be used for EMR extract. Current options include "BEFORE ENROLLMENT" or "AFTER ENROLLMENT" - number of days before or after consent into study.
#' @param index_range Number of days before date cutoff to be used for EMR extract. Time must be specified in number of days. Default is 36500 days (100 years).
#'
#' @return A list of dataframes with all relevant EMR lab result records
#' @export
#'
#' @examples
#'
#'
#' #example for extracting all C-Reactive Protein lab results
#'#labdomemr = load_data(datadir="C:/Users/me/",domains=c("Labs","Demographics"),data_type="EMR")
#'#crp = extract_lab_emr(data=labdomemr,labtype="CRP",codetype="ALL")
#'
#' #example for extracting all High Sensitivity C-Reactive Protein lab results
#'#hscrp = extract_lab_emr(data=labdomemr,labtype="HS CRP",codetype="ALL")
#'
#' #example for extracting all non-High Sensitivity C-Reactive Protein lab results
#'#nscrp = extract_lab_emr(data=labdomemr,labtype="NS CRP",codetype="ALL")
#'
#' #example for extracting all Fecal Calprotectin lab results
#'#fcal = extract_lab_emr(data=labdomemr,labtype="FCAL",codetype="ALL")
#'
#' #example for extracting LOINC C-Reactive Protein lab results
#'#crp = extract_lab_emr(data=labdomemr,labtype="CRP",codetype="LOINC")
#'
#' #example for extracting C-Reactive Protein lab results using only keywords
#'#crp = extract_lab_emr(data=labdomemr,labtype="CRP",codetype="KEYWORDS")
#'
#' #example for extracting all elevated C-Reactive Protein lab results
#'#crp = extract_lab_emr(data=labdomemr,labtype="CRP",codetype="ALL",positive_elevated=TRUE)
#
#' #example for extracting all C-Reactive Protein lab results from after patients were enrolled in the respective study
#'#crp = extract_lab_emr(data=labdomemr,labtype="CRP",codetype="ALL",datecutoff="AFTER ENROLLMENT")
#'
#' #example for extracting all C-Reactive Protein lab results from one year after patients were enrolled in the respective study
#'#crp = extract_lab_emr(data=labdomemr,labtype="CRP",codetype="ALL",datecutoff="AFTER ENROLLMENT",index_range=365)
#'
#' #example for extracting all C-Reactive Protein lab results from two years after patients were enrolled in the respective study
#'#crp = extract_lab_emr(data=labdomemr,labtype="CRP",codetype="ALL",datecutoff="AFTER ENROLLMENT",index_range=730)
#'
#' #example for extracting all C-Reactive Protein lab results from before patients were enrolled in the respective study
#'#crp = extract_lab_emr(data=labdomemr,labtype="CRP",codetype="ALL",datecutoff="BEFORE ENROLLMENT")
#'
#' #example for extracting all C-Reactive Protein lab results from one year before patients were enrolled in the respective study
#'#crp = extract_lab_emr(data=labdomemr,labtype="CRP",codetype="ALL",datecutoff="BEFORE ENROLLMENT",index_range=365)
#'
#' #example for extracting all C-Reactive Protein lab results from two years before patients were enrolled in the respective study
#'#crp = extract_lab_emr(data=labdomemr,labtype="CRP",codetype="ALL",datecutoff="BEFORE ENROLLMENT",index_range=730)
#'
#'
#'


extract_lab_emr <- function(data,
                            labtype,
                            codetype=c("LOINC","KEYWORDS","ALL"),
                            positive_elevated=FALSE,
                            datecutoff = NULL,
                            index_range = 36500){
  labemrdata=data$labs
  labemrdata1=lab_result_cln(labemrdata)
  labtype1=toupper(labtype)
  if(labtype1=="CRP"){
    if(codetype=="ALL"){
      codelist="1988-5|11039-5|30522-7|reactive prot|CRP"
      lab=labemrdata1 %>%
        filter(grepl(codelist,SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE)|grepl(codelist,SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE)) %>%
        filter(!grepl("0 mm|not sufficient|refused|not received|cancelled|specimen too old|invalid|not valid",lab_result_cln,ignore.case=TRUE)) %>%
        filter(!grepl("XCRP|PCR|DESCRPT|MACRPH|VENOUSCRPOC",SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE)&!grepl("XCRP|PCR|DESCRPT|MACRPH|VENOUSCRPOC",SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE))
      if(positive_elevated==TRUE){
        lab=lab %>%
          filter((test_unit_cln=="MG/L"&lab_result_cln>8)|(test_unit_cln=="MG/DL"&lab_result_cln>0.8))
      }
    }
    if(codetype=="LOINC"){
      codelist="1988-5|11039-5|30522-7"
      lab=labemrdata1 %>%
        filter(grepl(codelist,SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE)|grepl(codelist,SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE)) %>%
        filter(!grepl("0 mm|not sufficient|refused|not received|cancelled|specimen too old|invalid|not valid",lab_result_cln,ignore.case=TRUE))
      if(positive_elevated==TRUE){
        lab=lab %>%
          filter((test_unit_cln=="MG/L"&lab_result_cln>8)|(test_unit_cln=="MG/DL"&lab_result_cln>0.8))
      }
    }
    if(codetype=="KEYWORDS"){
      codelist="reactive prot|CRP"
      lab=labemrdata1 %>%
        filter(grepl(codelist,SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE)|grepl(codelist,SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE)) %>%
        filter(!grepl("0 mm|not sufficient|refused|not received|cancelled|specimen too old|invalid|not valid",lab_result_cln,ignore.case=TRUE)) %>%
        filter(!grepl("XCRP|PCR|DESCRPT|MACRPH|VENOUSCRPOC",SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE)&!grepl("XCRP|PCR|DESCRPT|MACRPH|VENOUSCRPOC",SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE))
      if(positive_elevated==TRUE){
        lab=lab %>%
          filter((test_unit_cln=="MG/L"&lab_result_cln>8)|(test_unit_cln=="MG/DL"&lab_result_cln>0.8))
      }
    }
  }
  if(labtype1=="HS CRP"){
    if(codetype=="ALL"){
      codelist="30522-7"
      lab=labemrdata1 %>%
        filter(grepl(codelist,SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE)|
                grepl(codelist,SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE)|
                (grepl("high sensi",SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE)&grepl("reactive prot|CRP",SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE))|
                (grepl("high sensi",SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE)&grepl("reactive prot|CRP",SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE))) %>%
        filter(!grepl("0 mm|not sufficient|refused|not received|cancelled|specimen too old|invalid|not valid",lab_result_cln,ignore.case=TRUE)) %>%
        filter(!grepl("XCRP|PCR|DESCRPT|MACRPH|VENOUSCRPOC",SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE)&!grepl("XCRP|PCR|DESCRPT|MACRPH|VENOUSCRPOC",SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE))
      if(positive_elevated==TRUE){
        lab=lab %>%
          filter((test_unit_cln=="MG/L"&lab_result_cln>8)|(test_unit_cln=="MG/DL"&lab_result_cln>0.8))
      }
    }
    if(codetype=="LOINC"){
      codelist="30522-7"
      lab=labemrdata1 %>%
        filter(grepl(codelist,SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE)|
                 grepl(codelist,SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE)) %>%
        filter(!grepl("0 mm|not sufficient|refused|not received|cancelled|specimen too old|invalid|not valid",lab_result_cln,ignore.case=TRUE))
      if(positive_elevated==TRUE){
        lab=lab %>%
          filter((test_unit_cln=="MG/L"&lab_result_cln>8)|(test_unit_cln=="MG/DL"&lab_result_cln>0.8))
      }
    }
    if(codetype=="KEYWORDS"){
      lab=labemrdata1 %>%
        filter((grepl("high sensi",SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE)&grepl("reactive prot|CRP",SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE))|
                 (grepl("high sensi",SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE)&grepl("reactive prot|CRP",SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE))) %>%
        filter(!grepl("0 mm|not sufficient|refused|not received|cancelled|specimen too old|invalid|not valid",lab_result_cln,ignore.case=TRUE)) %>%
        filter(!grepl("XCRP|PCR|DESCRPT|MACRPH|VENOUSCRPOC",SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE)&!grepl("XCRP|PCR|DESCRPT|MACRPH|VENOUSCRPOC",SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE))
      if(positive_elevated==TRUE){
        lab=lab %>%
          filter((test_unit_cln=="MG/L"&lab_result_cln>8)|(test_unit_cln=="MG/DL"&lab_result_cln>0.8))
      }
    }
  }
  if(labtype1=="NS CRP"){
    if(codetype=="ALL"){
      codelist="1988-5|11039-5"
      lab=labemrdata1 %>%
        filter(grepl(codelist,SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE)|grepl(codelist,SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE)|
                (grepl("reactive prot|CRP",SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE)&!grepl("high sensi",SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE))|
                (grepl("reactive prot|CRP",SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE)&!grepl("high sensi",SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE))) %>%
        filter(!grepl("0 mm|not sufficient|refused|not received|cancelled|specimen too old|invalid|not valid",lab_result_cln,ignore.case=TRUE)) %>%
        filter(!grepl("XCRP|PCR|DESCRPT|MACRPH|VENOUSCRPOC",SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE)&!grepl("XCRP|PCR|DESCRPT|MACRPH|VENOUSCRPOC",SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE))
      if(positive_elevated==TRUE){
        lab=lab %>%
          filter((test_unit_cln=="MG/L"&lab_result_cln>8)|(test_unit_cln=="MG/DL"&lab_result_cln>0.8))
      }
    }
    if(codetype=="LOINC"){
      codelist="1988-5|11039-5"
      lab=labemrdata1 %>%
        filter(grepl(codelist,SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE)|grepl(codelist,SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE)) %>%
        filter(!grepl("0 mm|not sufficient|refused|not received|cancelled|specimen too old|invalid|not valid",lab_result_cln,ignore.case=TRUE))
      if(positive_elevated==TRUE){
        lab=lab %>%
          filter((test_unit_cln=="MG/L"&lab_result_cln>8)|(test_unit_cln=="MG/DL"&lab_result_cln>0.8))
      }
    }
    if(codetype=="KEYWORDS"){
      lab=labemrdata1 %>%
        filter((grepl("reactive prot|CRP",SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE)&!grepl("high sensi",SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE))|
                 (grepl("reactive prot|CRP",SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE)&!grepl("high sensi",SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE))) %>%
        filter(!grepl("0 mm|not sufficient|refused|not received|cancelled|specimen too old|invalid|not valid",lab_result_cln,ignore.case=TRUE)) %>%
        filter(!grepl("XCRP|PCR|DESCRPT|MACRPH|VENOUSCRPOC",SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE)&!grepl("XCRP|PCR|DESCRPT|MACRPH|VENOUSCRPOC",SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE))
      if(positive_elevated==TRUE){
        lab=lab %>%
          filter((test_unit_cln=="MG/L"&lab_result_cln>8)|(test_unit_cln=="MG/DL"&lab_result_cln>0.8))
      }
    }
  }
  if(labtype1=="FCAL"){
    if(codetype=="ALL"){
      codelist="38445-3|82874-9|fecal calprotectin"
      lab=labemrdata1 %>%
        filter(grepl(codelist,SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE)|
                grepl(codelist,SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE)|
                (grepl("calprotectin",SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE)&grepl("fecal|stool",SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE))|
                (grepl("calprotectin",SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE)&grepl("fecal|stool",SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE))) %>%
        filter(!grepl("0 mm|not sufficient|refused|not received|cancelled|specimen too old|invalid|not valid",lab_result_cln,ignore.case=TRUE))
      if(positive_elevated==TRUE){
        lab=lab %>%
          filter(lab_result_cln>200)
      }
    }
    if(codetype=="LOINC"){
      codelist="38445-3|82874-9"
      lab=labemrdata1 %>%
        filter(grepl(codelist,SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE)|
                 grepl(codelist,SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE)) %>%
        filter(!grepl("0 mm|not sufficient|refused|not received|cancelled|specimen too old|invalid|not valid",lab_result_cln,ignore.case=TRUE))
      if(positive_elevated==TRUE){
        lab=lab %>%
          filter(lab_result_cln>200)
      }
    }
    if(codetype=="KEYWORDS"){
      codelist="fecal calprotectin"
      lab=labemrdata1 %>%
        filter(grepl(codelist,SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE)|
                 grepl(codelist,SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE)|
                 (grepl("calprotectin",SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE)&grepl("fecal|stool",SRC_LAB_TEST_CONCEPT_NAME,ignore.case=TRUE))|
                 (grepl("calprotectin",SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE)&grepl("fecal|stool",SRC_LAB_TEST_CONCEPT_CODE,ignore.case=TRUE))) %>%
        filter(!grepl("not sufficient|refused|not received|cancelled|specimen too old|invalid|not valid",lab_result_cln,ignore.case=TRUE))
      if(positive_elevated==TRUE){
        lab=lab %>%
          filter(lab_result_cln>200)
      }
    }
  }
  if(!labtype1 %in% c("CRP","HS CRP","NS CRP","FCAL")){
    lab=labemrdata1
  }
  if(positive_elevated==TRUE){
    lab=lab %>%
      filter(!grepl("0 mm|neg|indet|0.0",lab_result_cln,ignore.case=TRUE))
  }
  if ("BEFORE ENROLLMENT" %in% datecutoff) {
    lab2 <- lab
    lab <- data$demographics %>%
      extract_consent("SPARC") %>%
      mutate(dateconsentcalc = as.Date(DATE_OF_CONSENT, format = "%d-%B-%Y")) %>%
      mutate(earliestemr = dateconsentcalc - index_range) %>%
      # merge(encemr,by="DEIDENTIFIED_MASTER_PATIENT_ID")%>%
      merge(lab2, by = "DEIDENTIFIED_MASTER_PATIENT_ID", allow.cartesian = TRUE) %>%
      mutate(dateforfilter = as.Date(SPECIMEN_COLLECTION_DATE, format = "%d-%B-%Y")) %>%
      filter(earliestemr <= dateforfilter & dateforfilter <= dateconsentcalc)
  }
  if ("AFTER ENROLLMENT" %in% datecutoff) {
    lab2 <- lab
    lab <- data$demographics %>%
      extract_consent("SPARC") %>%
      mutate(dateconsentcalc = as.Date(DATE_OF_CONSENT, format = "%d-%B-%Y")) %>%
      mutate(latestemr = dateconsentcalc + index_range) %>%
      # merge(encemr,by="DEIDENTIFIED_MASTER_PATIENT_ID")%>%
      merge(lab2, by = "DEIDENTIFIED_MASTER_PATIENT_ID", allow.cartesian = TRUE) %>%
      mutate(dateforfilter = as.Date(SPECIMEN_COLLECTION_DATE, format = "%d-%B-%Y")) %>%
      filter(dateconsentcalc <= dateforfilter & dateforfilter <= latestemr)
  }
  return(lab)
}
