
#' reason_stopped
#'
#' Extract reason stopped for ECRF and SF SPARC Data source
#'
#'
#' @param prescriptions A dataframe with prescriptions data usually generated using load_data.
#'
#' @return A dataframe with the reason stopped
#'
#'

reason_stopped <- function(prescriptions){

  stop_ecrf <- prescriptions %>%
  filter(DATA_SOURCE %in% c("SF_SPARC", "ECRF_SPARC")) %>%
  mutate(REASON_STOPPED = toupper(REASON_STOPPED),
         MEDICATION_NAME = toupper(MEDICATION_NAME)) %>%
    drop_na(REASON_STOPPED) %>%
    left_join(med_grp %>% mutate(MEDICATION_NAME = toupper(MEDICATION_NAME))) %>%
    drop_na(new_med_name) %>%
  distinct(DEIDENTIFIED_MASTER_PATIENT_ID, DATA_SOURCE, new_med_name, REASON_STOPPED) %>%
  arrange(DEIDENTIFIED_MASTER_PATIENT_ID, new_med_name) %>%
  group_by(DEIDENTIFIED_MASTER_PATIENT_ID, new_med_name) %>%
  mutate(c = seq_along(DEIDENTIFIED_MASTER_PATIENT_ID)) %>%
  pivot_wider(
    id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID, new_med_name),
    names_from = c,
    values_from = c(REASON_STOPPED),
    names_prefix = "STOP_"
  ) %>%
  rowwise() %>%
  unite(col = "REASON_STOPPED", starts_with("STOP"), na.rm = T, sep = "; ") %>%
  rename(MEDICATION = new_med_name) %>%
  mutate(across(-"DEIDENTIFIED_MASTER_PATIENT_ID", ~ ifelse(. == "", NA, as.character(.))))


}



#' current_med
#'
#' Find current medication in eCRF data source
#'
#'
#' @param medication A dataframe with generated by sparc_med_filter
#'
#' @return A dataframe with all current medications in eCRF (excludes not current)
#'
#'

current_med <- function(medication){

  current <- medication %>%
    filter(DATA_SOURCE == "ECRF_SPARC") %>%
    filter(CURRENT_MEDICATION == "YES") %>%
    mutate(
      MED_START_DATE = if_else(year(MED_START_DATE) > 1980, MED_START_DATE, as.Date(NA, format = "%d-%m-%y")),
      MED_END_DATE = if_else(year(MED_END_DATE) > 1980, MED_END_DATE, as.Date(NA, format = "%d-%m-%y"))
    ) %>%
    pivot_longer(cols = c(MED_START_DATE, MED_END_DATE), names_to = "type", values_to = "date") %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, new_med_name, DATA_SOURCE, match(type, c("MED_END_DATE", "MED_START_DATE"))) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, new_med_name, DATA_SOURCE) %>%
    slice(which.max(date)) %>%
    pivot_wider(names_from = type, values_from = date) %>%
    ungroup() %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, new_med_name,CURRENT_MEDICATION) %>%
    rename(MEDICATION = new_med_name)

}
