#### OQRUS SCORES 06/29/2026 ----
# qorus_scores
#' Create QORUS Scores Table - all responses
#'
#' @param data A list of dataframes, typically generated by a call to load_data. Must include demographics, diagnosis, encounter, procedures, and observations. Only CRF data needs to be uploaded.
#' @param index_info A dataframe  with DEIDENTIFIED_MASTER_PATIENT_ID and a variable index_date.  Other options include, enrollment, latest, endoscopy, omics collection.
#' @param filename the name of the output file. Must be .xlsx.
#' @param index_range the number of days to look out from index date. If multiple of the same score fall within this range then the one closest to the index date is picked. Default is 60 days.
#' @param location_logic specify which CD location function to use. If using logic developed by AZ then use location_logic = "AZ".
#' @param export if TRUE then writes the data frame to its own excel file
#'
#' @return qorus scores table
#' @export

qorus_scores <- function (data, index_info = c("ENROLLMENT", "LATEST", "ENDOSCOPY",
                                                   "OMICS"), filename = "QORUS_SCORES.xlsx", index_range = "60",
                              location_logic = "CCF", export = T)
{
  if ("character" %in% class(index_info)) {
    index_info <- toupper(index_info)
  }
  else {
    index_info <- index_info
  }
  consent <- extract_consent(data$demographics, "QORUS")
  demo <- extract_demo(data$demographics, "QORUS")
  dx <- data$diagnosis %>% filter(DATA_SOURCE %in% c("ECRF_QORUS")) %>%
    filter(DIAG_CONCEPT_NAME %in% c("Crohn's Disease",
                                    "IBD Unclassified", "Ulcerative Colitis")) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>%
    left_join(data$encounter %>%
                distinct(DEIDENTIFIED_MASTER_PATIENT_ID, VISIT_ENCOUNTER_ID, VISIT_ENCOUNTER_START_DATE)) %>%
    mutate(DIAGNOSIS = DIAG_CONCEPT_NAME,
           DIAGNOSIS_DATE = VISIT_ENCOUNTER_START_DATE,
           DISEASE_SITE = DIAG_SITE) %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, desc(DIAGNOSIS_DATE)) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>% slice_max(order_by = DIAGNOSIS_DATE) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, DIAGNOSIS,
           DIAGNOSIS_DATE) %>%
    ungroup() %>%
    distinct()
  table <- consent %>% left_join(demo, by = "DEIDENTIFIED_MASTER_PATIENT_ID") %>%
    left_join(dx, by = "DEIDENTIFIED_MASTER_PATIENT_ID")
  t <- as.numeric(index_range)
  if ("ENROLLMENT" %in% index_info) {
    cohort <- table %>% mutate(index_date = DATE_OF_CONSENT)
  }
  else if ("ENDOSCOPY" %in% index_info) {
    endoscopy <- data$procedures %>% filter(DATA_SOURCE == "ECRF_QORUS") %>%
      filter(PROC_CONCEPT_NAME %in% c("Colonoscopy/Sigmoidoscopy",
                                      "Pouchoscopy")) %>% mutate(PROC_START_DATE = dmy(PROC_START_DATE)) %>%
      rename(index_date = PROC_START_DATE) %>% drop_na(index_date) %>%
      select(DEIDENTIFIED_MASTER_PATIENT_ID, index_date)
    cohort <- endoscopy %>% left_join(table)
  }
  else if ("OMICS" %in% index_info) {
    omics <- data$omics_patient_mapping %>% mutate(SAMPLE_COLLECTED_DATE = dmy(SAMPLE_COLLECTED_DATE)) %>%
      mutate(index_date = SAMPLE_COLLECTED_DATE) %>% drop_na(index_date) %>%
      select(-c(DATA_SOURCE, DEIDENTIFIED_PATIENT_ID,
                VISIT_ENCOUNTER_ID)) %>% distinct()
    omics_index <- omics %>% distinct(DEIDENTIFIED_MASTER_PATIENT_ID,
                                      index_date)
    cohort <- omics_index %>% left_join(table)
  }
  else if ("LATEST" %in% index_info) {


    latest <- data$encounter %>% filter(DATA_SOURCE == "ECRF_QORUS") %>%

      ## ask Tara about this CLB -
      # filter(grepl("Smartform|Survey", TYPE_OF_ENCOUNTER,
      #              ignore.case = T)) %>%
      arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
              desc(DATA_SOURCE), desc(VISIT_ENCOUNTER_START_DATE)) %>%
      group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>% slice(which.max(VISIT_ENCOUNTER_START_DATE)) %>%
      ungroup() %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                           VISIT_ENCOUNTER_START_DATE, TYPE_OF_ENCOUNTER) %>% rename(index_date = VISIT_ENCOUNTER_START_DATE,
                                                                                     MOST_RECENT_ENCOUNTER_TYPE = TYPE_OF_ENCOUNTER)
    cohort <- table %>% left_join(latest)
  }
  else {
    cohort <- index_info %>% left_join(table)
  }
  gc()
  cdp <- data$observations %>% filter(DATA_SOURCE == "ECRF_QORUS") %>%
    filter(OBS_TEST_CONCEPT_NAME %in% c("Crohn's Disease Phenotype",
                                        "IBD Manifestations - Abdominal Abscess, Fistula, or Other Penetrating Complication") |
             str_detect(OBS_TEST_CONCEPT_NAME, "^Phenotype")) %>%
    drop_na(DESCRIPTIVE_SYMP_TEST_RESULTS) %>% right_join(cohort) %>%
    filter(DIAGNOSIS == "Crohn's Disease") %>% mutate(diff = OBS_TEST_RESULT_DATE -
                                                        index_date) %>% mutate(keep = case_when(DESCRIPTIVE_SYMP_TEST_RESULTS ==
                                                                                                  "Inflammatory, non-penetrating, non-stricturing" & diff >
                                                                                                  t ~ "keep", diff <= t ~ "keep")) %>% filter(keep ==
                                                                                                                                                "keep") %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                                                                                                                     OBS_TEST_CONCEPT_NAME, index_date) %>% slice(which.min(abs(diff))) %>%
    ungroup() %>% pivot_wider(id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID,
                                          index_date), names_from = OBS_TEST_CONCEPT_NAME, values_from = DESCRIPTIVE_SYMP_TEST_RESULTS) %>%
    mutate(`Crohn's Disease Phenotype` = case_when(`Crohn's Disease Phenotype` ==
                                                     "Inflammatory, non-penetrating, non-stricturing" ~
                                                     "Inflammatory non-penetrating, non-stricturing (B1)",
                                                   `Crohn's Disease Phenotype` == "Stricturing" ~ "Stricturing (B2)",
                                                   `Crohn's Disease Phenotype` == "Penetrating" ~ "Penetrating (B3)",
                                                   `Crohn's Disease Phenotype` == "Both stricturing and penetrating" ~
                                                     "Both stricturing and penetrating (B2B3)", TRUE ~
                                                     `Crohn's Disease Phenotype`))
  cohort <- cohort %>% left_join(cdp)
  ####
  # cdp <- data$observations %>% filter(DATA_SOURCE == "ECRF_QORUS") %>%
  #   filter(OBS_TEST_CONCEPT_NAME %in% c("Crohn's Disease Diagnosis Site"))
  ####
  ucp <- data$observations %>% filter(DATA_SOURCE == "ECRF_QORUS") %>%
    filter(OBS_TEST_CONCEPT_NAME %in% "Ulcerative Colitis Diagnosis Site" &
             (!is.na(DESCRIPTIVE_SYMP_TEST_RESULTS))) %>% distinct(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                   OBS_TEST_CONCEPT_NAME, DESCRIPTIVE_SYMP_TEST_RESULTS,
                                                                   OBS_TEST_CONCEPT_CODE, OBS_TEST_RESULT_DATE) %>% right_join(cohort) %>%
    filter(DIAGNOSIS == "Ulcerative Colitis") %>% mutate(diff = (OBS_TEST_RESULT_DATE) -
                                                           index_date) %>% mutate(keep = case_when(DESCRIPTIVE_SYMP_TEST_RESULTS ==
                                                                                                     "Rectum only(proctitis)" & diff > t ~ "keep",
                                                                                                   diff <= t ~ "keep")) %>% filter(keep == "keep") %>%
    # arrange(DEIDENTIFIED_MASTER_PATIENT_ID, match(DESCRIPTIVE_SYMP_TEST_RESULTS,
    #                                               c("Pancolitis", "Extensive ulcerative colitis (extends proximal to the splenic flexure)",
    #                                                 "Left-sided ulcerative colitis (distal to the splenic flexure only)",
    #                                                 "Ulcerative proctitis (rectum only)", "Unknown"))) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    slice(which.min(abs(diff))) %>% ungroup() %>% pivot_wider(id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                          index_date), names_from = OBS_TEST_CONCEPT_NAME, values_from = DESCRIPTIVE_SYMP_TEST_RESULTS) %>%
    mutate(`Ulcerative Colitis Diagnosis Site` = case_when(grepl("post-colectomy|j-pouch|stoma", `Ulcerative Colitis Diagnosis Site`, ignore.case = T) ~ "Post-Colectomy",
                                                           grepl("pan-colitis", `Ulcerative Colitis Diagnosis Site`,  ignore.case = T) ~ "Pancolitis (E4)",
                                                           grepl("Extensive", `Ulcerative Colitis Diagnosis Site`,  ignore.case = T) ~ "Extensive ulcerative colitis (extends proximal to the splenic flexure) (E3)",
                                                           grepl("Left-sided", `Ulcerative Colitis Diagnosis Site`,  ignore.case = T) ~ "Left-sided ulcerative colitis (distal to the splenic flexure only) (E2)",
                                                           grepl("Rectum only|proctitis", `Ulcerative Colitis Diagnosis Site`, ignore.case = T) ~ "Ulcerative proctitis (rectum only) (E1)",
                                                           TRUE ~ `Ulcerative Colitis Diagnosis Site`))


  cohort <- left_join(cohort, ucp)

  #### FINISHED 06/29/2026 EDITS HERE ----

  ibdu <- data$observations %>% filter(DATA_SOURCE == "ECRF_QORUS") %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>% filter(OBS_TEST_CONCEPT_NAME %in%
                                                          c("IBD-U Phenotype") &
                                                          (!is.na(DESCRIPTIVE_SYMP_TEST_RESULTS))) %>% distinct(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                                                                OBS_TEST_CONCEPT_NAME, DESCRIPTIVE_SYMP_TEST_RESULTS,
                                                                                                                OBS_TEST_CONCEPT_CODE, OBS_TEST_RESULT_DATE) %>% right_join(cohort) %>%
    filter(DIAGNOSIS == "IBD Unclassified") %>% mutate(diff = (OBS_TEST_RESULT_DATE) -
                                                         index_date) %>% mutate(keep = case_when(DESCRIPTIVE_SYMP_TEST_RESULTS ==
                                                                                                   "Ulcerative proctitis (rectum only)" & diff > t ~ "keep",
                                                                                                 diff <= t ~ "keep")) %>% filter(keep == "keep") %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    slice(which.min(abs(diff))) %>% pivot_wider(id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                            index_date), names_from = OBS_TEST_CONCEPT_NAME, values_from = DESCRIPTIVE_SYMP_TEST_RESULTS)
  cohort <- cohort %>% left_join(ibdu)


  #### QORUS LOCATION CHECK ----

  location <- data$observations %>% filter(DATA_SOURCE ==
                                             "ECRF_QORUS") %>% filter(OBS_TEST_CONCEPT_NAME %in% c("Crohn's Disease Diagnosis Site",
                                                                                                   "IBD-U Diagnosis Site",
                                                                                                   "Ulcerative Colitis Diagnosis Site")) %>%
    drop_na(DESCRIPTIVE_SYMP_TEST_RESULTS) %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                        OBS_TEST_CONCEPT_NAME) %>% arrange(OBS_TEST_RESULT_DATE,
                                                                                           .by_group = TRUE) %>% mutate(result = case_when(OBS_TEST_RESULT_DATE >
                                                                                                                                             lag(OBS_TEST_RESULT_DATE) & DESCRIPTIVE_SYMP_TEST_RESULTS ==
                                                                                                                                             "No" & lag(DESCRIPTIVE_SYMP_TEST_RESULTS) == "Yes" &
                                                                                                                                             OBS_TEST_CONCEPT_NAME == lag(OBS_TEST_CONCEPT_NAME) ~
                                                                                                                                             "Yes", TRUE ~ DESCRIPTIVE_SYMP_TEST_RESULTS)) %>%
    ungroup() %>% right_join(cohort) %>% filter(DIAGNOSIS ==
                                                  "Crohn's Disease") %>% mutate(diff = OBS_TEST_RESULT_DATE -
                                                                                  index_date) %>% mutate(keep = case_when(diff <=
                                                                                                                            t ~ "keep", result == "No" & diff > t ~ "keep",
                                                                                  )) %>% filter(keep == "keep") %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                                                                             index_date, OBS_TEST_CONCEPT_NAME) %>% slice(which.min(abs(diff))) %>%
    ungroup() %>% distinct(DEIDENTIFIED_MASTER_PATIENT_ID,
                           index_date, OBS_TEST_CONCEPT_NAME, result) %>% pivot_wider(id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                                                  index_date), names_from = OBS_TEST_CONCEPT_NAME,
                                                                                      values_from = result) %>% ungroup() %>%
    ibdplexus:::fix_col_names()
  cohort <- left_join(cohort, location)
  perianal <- data$observations %>% filter(DATA_SOURCE ==
                                             "ECRF_QORUS") %>%
    filter(OBS_TEST_CONCEPT_NAME %in% c("Crohn's Disease Diagnosis Site",
                                        "IBD-U Diagnosis Site",
                                        "Ulcerative Colitis Diagnosis Site")) %>%
    filter(grepl("perianal", DESCRIPTIVE_SYMP_TEST_RESULTS, ignore.case = T)) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, OBS_TEST_CONCEPT_NAME) %>%
    drop_na(DESCRIPTIVE_SYMP_TEST_RESULTS) %>% arrange(OBS_TEST_RESULT_DATE,
                                                       .by_group = TRUE) %>% mutate(result = case_when(OBS_TEST_RESULT_DATE >
                                                                                                         lag(OBS_TEST_RESULT_DATE) & DESCRIPTIVE_SYMP_TEST_RESULTS ==
                                                                                                         "No" & lag(DESCRIPTIVE_SYMP_TEST_RESULTS) == "Yes" &
                                                                                                         OBS_TEST_CONCEPT_NAME == lag(OBS_TEST_CONCEPT_NAME) ~
                                                                                                         "Yes", TRUE ~ DESCRIPTIVE_SYMP_TEST_RESULTS)) %>%
    ungroup() %>% right_join(cohort) %>% filter(DIAGNOSIS ==
                                                  "Crohn's Disease") %>% mutate(diff = OBS_TEST_RESULT_DATE -
                                                                                  index_date) %>% mutate(keep = case_when(diff <=
                                                                                                                            t ~ "keep", result == "No" & diff > t ~ "keep")) %>%
    filter(keep == "keep") %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID,
                                        index_date, OBS_TEST_CONCEPT_NAME) %>% slice(which.min(abs(diff))) %>%
    ungroup() %>% distinct(DEIDENTIFIED_MASTER_PATIENT_ID,
                           index_date, OBS_TEST_CONCEPT_NAME, result) %>% pivot_wider(id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                                                  index_date), names_from = OBS_TEST_CONCEPT_NAME,
                                                                                      values_from = result) %>% ungroup() %>%
    mutate(PERIANAL = 1) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, PERIANAL)
  cohort <- left_join(cohort, perianal)
  disease_location <- cohort %>%
    filter(DIAGNOSIS == "Crohn's Disease") %>%
    mutate(
      ileal = ifelse(grepl("Ileal", `CROHNS_DISEASE_DIAGNOSIS_SITE`, ignore.case = T), 1, 0),
      colonic = ifelse(grepl("colonic", `CROHNS_DISEASE_DIAGNOSIS_SITE`, ignore.case = T), 1, 0),
      Location = case_when(`ileal` == 1 & colonic != 1 ~ "Ileal",
                           `ileal` != 1 & colonic == 1 ~ "Colonic",
                           `ileal` == 1 & colonic == 1 ~ "Ileocolonic",
                           TRUE ~  "Unknown"),
      ilealcolonic = ifelse(ileal == 1 & colonic == 1, 1, 0),
      UpperGI = ifelse(grepl("Proximal|Upper", `CROHNS_DISEASE_DIAGNOSIS_SITE`, ignore.case = T), 1, 0)) %>%
    mutate(Location = case_when(is.na(Location) & ilealcolonic ==
                                  1 ~ "Ileocolonic", is.na(Location) & (is.na(ilealcolonic) |
                                                                          ilealcolonic == 0) & ileal == 1 ~ "Ileal", is.na(Location) &
                                  (is.na(ilealcolonic) | ilealcolonic == 0) &
                                  colonic == 1 ~ "Colonic", TRUE ~ Location)) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, INDEX_DATE,
           Location, UpperGI) %>% dplyr::rename(DISEASE_LOCATION = Location,
                                                UPPERGI = UpperGI, index_date = INDEX_DATE) %>%
    distinct()
  cohort <- left_join(cohort, disease_location)


  #### QORUS SCDAI ----


  scdai_ecrf <- data$observations %>% filter(DATA_SOURCE == "ECRF_QORUS") %>%
    filter(grepl("Abdominal Pain|General Well|Bowel Movements",
                 OBS_TEST_CONCEPT_NAME, ignore.case = T)) %>% filter(OBS_TEST_CONCEPT_NAME !=
                                                                       "Baseline Number of Daily Bowel Movements") %>% mutate(result = ifelse(is.na(DESCRIPTIVE_SYMP_TEST_RESULTS),
                                                                                                                                              TEST_RESULT_NUMERIC, DESCRIPTIVE_SYMP_TEST_RESULTS)) %>%
    mutate(result = case_when(result == "None" ~ 0, result ==
                                "Mild" ~ 1, result == "Moderate" ~ 2, result ==
                                "Severe" ~ 3, result == "Generally well" ~ 0, result ==
                                "Slightly under par" ~ 1, result == "Poor" ~ 2,
                              result == "Very poor" ~ 3, result == "Terrible" ~
                                4, result == "20+" ~ 20, TRUE ~ as.numeric(result))) %>%
    mutate(result = ifelse(result > 20, 20, result)) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, OBS_TEST_RESULT_DATE,
             OBS_TEST_CONCEPT_NAME, result) %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                         OBS_TEST_RESULT_DATE, OBS_TEST_CONCEPT_NAME) %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                                                                  OBS_TEST_CONCEPT_NAME, desc(result)) %>% slice(1) %>%
    ungroup() %>% pivot_wider(id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID,
                                          OBS_TEST_RESULT_DATE), names_from = c(OBS_TEST_CONCEPT_NAME),
                              values_from = c(result)) %>% mutate(aug18 = ifelse(OBS_TEST_RESULT_DATE <
                                                                                   as.Date("01-AUG-2018", format = "%d-%b-%Y"), "before",
                                                                                 "after")) %>% mutate(A = `Abdominal Pain`, B = if_else(aug18 ==
                                                                                                                                          "before" & !is.na(`Current Average Number of Daily Bowel Movements`),
                                                                                                                                        `Current Average Number of Daily Bowel Movements`, `Current Average Number of Daily Liquid Bowel Movements`),
                                                                                                      B = ifelse(is.na(B), `Current Average Number of Daily Bowel Movements`,
                                                                                                                 B), G = `General Well-Being`) %>% mutate(Daily.BM.Question = case_when(B ==
                                                                                                                                                                                          `Current Average Number of Daily Liquid Bowel Movements` ~
                                                                                                                                                                                          "Current Average Number of Daily Liquid Bowel Movements",
                                                                                                                                                                                        B == `Current Average Number of Daily Bowel Movements` ~
                                                                                                                                                                                          "Current Average Number of Daily Bowel Movements",
                                                                                                                                                                                        TRUE ~ as.character(NA))) %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                                                                                                                                                                              OBS_TEST_RESULT_DATE) %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>%
    mutate(diff = OBS_TEST_RESULT_DATE - lag(OBS_TEST_RESULT_DATE),
           diff2 = lead(OBS_TEST_RESULT_DATE) - OBS_TEST_RESULT_DATE) %>%
    mutate(A = ifelse(is.na(A) & diff <= 7, lag(A), A),
           G = ifelse(is.na(G) & diff <= 7, lag(G), G), B = ifelse(is.na(B) &
                                                                     diff <= 7, lag(B), B), Daily.BM.Question = ifelse(is.na(Daily.BM.Question) &
                                                                                                                         (diff <= 7), lag(Daily.BM.Question), Daily.BM.Question)) %>%
    mutate(A = ifelse(is.na(A) & (diff2 <= 7), lead(A),
                      A), G = ifelse(is.na(G) & (diff2 <= 7), lead(G),
                                     G), B = ifelse(is.na(B) & (diff2 <= 7), lead(B),
                                                    B), Daily.BM.Question = ifelse(is.na(Daily.BM.Question) &
                                                                                     (diff2 <= 7), lead(Daily.BM.Question), Daily.BM.Question)) %>%
    dplyr::rename(Daily.BM = B, Abdominal.Pain.Score = A,
                  General.well.being.score = G) %>% mutate(sCDAI.score = 44 +
                                                             (2 * 7 * Daily.BM) + (5 * 7 * Abdominal.Pain.Score) +
                                                             (7 * 7 * General.well.being.score), Source = "ECRF") %>%
    dplyr::rename(sCDAI.date = OBS_TEST_RESULT_DATE) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, sCDAI.date, sCDAI.score,
           Source, Daily.BM, Abdominal.Pain.Score, General.well.being.score,
           Daily.BM.Question)
  sCDAI <- scdai_ecrf %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                  desc(sCDAI.score), sCDAI.date) %>% dplyr::rename(scdai.source = Source) %>%
    distinct_all() %>% mutate(Daily.BM.Version = case_when(Daily.BM.Question ==
                                                             "Current Average Number of Daily Bowel Movements" ~
                                                             1, Daily.BM.Question == "Current Average Number of Daily Liquid Bowel Movements" ~
                                                             2, Daily.BM.Question == "Current Maximum Number of Daily Bowel Movements" ~
                                                             3)) %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID, desc(sCDAI.score)) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, sCDAI.date,
             sCDAI.score, scdai.source, Daily.BM, Daily.BM.Version,
             Abdominal.Pain.Score, General.well.being.score) %>%
    ungroup() %>% select(sort(names(.))) %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                    everything()) %>% dplyr::mutate(sCDAI.category = case_when(sCDAI.score <
                                                                                                                 150 ~ "Remission", sCDAI.score >= 150 & sCDAI.score <=
                                                                                                                 219 ~ "Mild", sCDAI.score >= 220 & sCDAI.score <= 450 ~
                                                                                                                 "Moderate", sCDAI.score > 450 ~ "Severe", TRUE ~ as.character(NA))) %>%
    setNames(toupper(names(.))) %>% setNames(gsub("\\.",
                                                  "_", names(.)))

  scdai <- sCDAI %>% left_join(cohort) %>%
    mutate(datediff = abs(SCDAI_DATE - index_date)) %>%
    filter(DIAGNOSIS == "Crohn's Disease" & datediff <=
             t) %>% drop_na(SCDAI_SCORE) %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                     index_date, desc(SCDAI_SOURCE), desc(SCDAI_SCORE)) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    filter(datediff == min(abs(datediff))) %>% slice(1) %>%
    distinct() %>% ungroup() %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                                        index_date, intersect(names(.), names(calculate_scdai(data$observations))))




  cohort <- cohort %>% left_join(scdai)

  #### QORUS PRO2 ----
  pro2_ecrf <- data$observations %>% filter(DATA_SOURCE == "ECRF_QORUS") %>%
    filter(OBS_TEST_CONCEPT_NAME %in% c("Current Average Number of Daily Liquid Bowel Movements",
                                        "Abdominal Pain")) %>% mutate(result = ifelse(is.na(DESCRIPTIVE_SYMP_TEST_RESULTS),
                                                                                      TEST_RESULT_NUMERIC, DESCRIPTIVE_SYMP_TEST_RESULTS)) %>%
    mutate(result = case_when(result == "None" ~ 0, result ==
                                "Mild" ~ 1, result == "Moderate" ~ 2, result ==
                                "Severe" ~ 3, result == "20+" ~ 20, TRUE ~ as.numeric(result))) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, OBS_TEST_RESULT_DATE,
             OBS_TEST_CONCEPT_NAME, result) %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                         OBS_TEST_RESULT_DATE, OBS_TEST_CONCEPT_NAME) %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                                                                  OBS_TEST_CONCEPT_NAME, desc(result), .by_group = T) %>%
    slice(1) %>% ungroup() %>% pivot_wider(id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                       OBS_TEST_RESULT_DATE), names_from = c(OBS_TEST_CONCEPT_NAME),
                                           values_from = c(result)) %>% mutate(A = `Abdominal Pain`,
                                                                               B = `Current Average Number of Daily Liquid Bowel Movements`) %>%
    ungroup() %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                          OBS_TEST_RESULT_DATE) %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>%
    mutate(diff = OBS_TEST_RESULT_DATE - lag(OBS_TEST_RESULT_DATE),
           diff2 = lead(OBS_TEST_RESULT_DATE) - OBS_TEST_RESULT_DATE) %>%
    ungroup() %>% mutate(A = ifelse(is.na(A) & diff <= 7,
                                    lag(A), A), B = ifelse(is.na(B) & diff <= 7, lag(B),
                                                           B)) %>% mutate(A = ifelse(is.na(A) & (diff2 <= 7), lead(A),
                                                                                     A), B = ifelse(is.na(B) & (diff2 <= 7), lead(B), B)) %>%
    dplyr::rename(Liquid.BM = B, Abdominal.Pain.Score = A) %>%
    mutate(pro2.score = (Liquid.BM * 2) + (Abdominal.Pain.Score *
                                             5), Source = "ECRF") %>% dplyr::rename(pro2.date = OBS_TEST_RESULT_DATE) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, pro2.date, pro2.score,
           Source, Liquid.BM, Abdominal.Pain.Score)
  PRO2 <- pro2_ecrf %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                pro2.date) %>% dplyr::rename(pro2.source = Source) %>%
    distinct_all() %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                              pro2.date, pro2.score, pro2.source, Liquid.BM, Abdominal.Pain.Score) %>%
    ungroup() %>% dplyr::mutate(pro2.category = case_when(pro2.score <
                                                            8 ~ "Remission", pro2.score >= 8 & pro2.score <= 13 ~
                                                            "Mild", pro2.score >= 14 & pro2.score <= 35 ~ "Moderate",
                                                          pro2.score > 35 ~ "Severe", TRUE ~ as.character(NA))) %>%
    select(sort(names(.))) %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                                      everything()) %>% setNames(toupper(names(.))) %>% setNames(gsub("\\.",
                                                                                                      "_", names(.)))

  pro2 <- PRO2 %>% left_join(cohort,
                             by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID)) %>% mutate(datediff = abs(PRO2_DATE -
                                                                                                       index_date)) %>% filter(DIAGNOSIS == "Crohn's Disease" &
                                                                                                                                 datediff <= t) %>% drop_na(PRO2_SCORE) %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                                                                                                                                    index_date, desc(PRO2_SOURCE), desc(PRO2_SCORE)) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    filter(datediff == min(abs(datediff))) %>% slice(1) %>%
    distinct() %>% ungroup() %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                                        index_date, starts_with("PRO2"))
  cohort <- cohort %>% left_join(pro2, by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                    index_date))

  #### QORUS PRO3 ----

  pro3_ecrf <- data$observations %>% filter(DATA_SOURCE == "ECRF_SPARC") %>%
    filter(OBS_TEST_CONCEPT_NAME %in% c("Current Average Number of Daily Liquid Bowel Movements",
                                        "Abdominal Pain", "General Well-Being")) %>% mutate(result = ifelse(is.na(DESCRIPTIVE_SYMP_TEST_RESULTS),
                                                                                                            TEST_RESULT_NUMERIC, DESCRIPTIVE_SYMP_TEST_RESULTS)) %>%
    mutate(result = ifelse(is.na(DESCRIPTIVE_SYMP_TEST_RESULTS),
                           TEST_RESULT_NUMERIC, DESCRIPTIVE_SYMP_TEST_RESULTS)) %>%
    mutate(result = case_when(result == "None" ~ 0, result ==
                                "Mild" ~ 1, result == "Moderate" ~ 2, result ==
                                "Severe" ~ 3, result == "Generally well" ~ 0, result ==
                                "Slightly under par" ~ 1, result == "Poor" ~ 2,
                              result == "Very poor" ~ 3, result == "Terrible" ~
                                4, result == "20+" ~ 20, TRUE ~ as.numeric(result))) %>%
    mutate(result = ifelse(result > 20, 20, result)) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, OBS_TEST_RESULT_DATE,
             OBS_TEST_CONCEPT_NAME, result) %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                         OBS_TEST_RESULT_DATE, OBS_TEST_CONCEPT_NAME) %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                                                                  OBS_TEST_CONCEPT_NAME, desc(result), .by_group = T) %>%
    slice(1) %>% pivot_wider(id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID,
                                         OBS_TEST_RESULT_DATE), names_from = c(OBS_TEST_CONCEPT_NAME),
                             values_from = c(result)) %>% mutate(A = `Abdominal Pain`,
                                                                 B = `Current Average Number of Daily Liquid Bowel Movements`,
                                                                 G = `General Well-Being`) %>% ungroup() %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                                                                     OBS_TEST_RESULT_DATE) %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>%
    mutate(diff = OBS_TEST_RESULT_DATE - lag(OBS_TEST_RESULT_DATE),
           diff2 = lead(OBS_TEST_RESULT_DATE) - OBS_TEST_RESULT_DATE) %>%
    ungroup() %>% mutate(A = ifelse(is.na(A) & diff <= 7,
                                    lag(A), A), B = ifelse(is.na(B) & diff <= 7, lag(B),
                                                           B), G = ifelse(is.na(G) & diff <= 7, lag(G), G)) %>%
    mutate(A = ifelse(is.na(A) & (diff2 <= 7), lead(A),
                      A), B = ifelse(is.na(B) & (diff2 <= 7), lead(B),
                                     B), G = ifelse(is.na(G) & (diff2 <= 7), lead(G),
                                                    G)) %>% dplyr::rename(Liquid.BM = B, Abdominal.Pain.Score = A,
                                                                          General.well.being.score = G) %>% mutate(pro3.score = (Liquid.BM *
                                                                                                                                   2) + (Abdominal.Pain.Score * 5) + (General.well.being.score *
                                                                                                                                                                        7), Source = "ECRF") %>% dplyr::rename(pro3.date = OBS_TEST_RESULT_DATE) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, pro3.date, pro3.score,
           Source, Liquid.BM, Abdominal.Pain.Score, General.well.being.score)
  PRO3 <- pro3_ecrf %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                pro3.date) %>% dplyr::rename(pro3.source = Source) %>%
    distinct_all() %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                              pro3.date, pro3.score, pro3.source, Liquid.BM, Abdominal.Pain.Score,
                              General.well.being.score) %>% ungroup() %>% dplyr::mutate(pro3.category = case_when(pro3.score <
                                                                                                                    13 ~ "Remission", pro3.score >= 13 & pro3.score <= 21 ~
                                                                                                                    "Mild", pro3.score >= 22 & pro3.score <= 53 ~ "Moderate",
                                                                                                                  pro3.score > 53 ~ "Severe", TRUE ~ as.character(NA))) %>%
    select(sort(names(.))) %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                                      everything()) %>% setNames(toupper(names(.))) %>% setNames(gsub("\\.",
                                                                                                      "_", names(.)))

  pro3 <- PRO3 %>% left_join(cohort,
                             by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID)) %>% mutate(datediff = abs(PRO3_DATE -
                                                                                                       index_date)) %>% filter(DIAGNOSIS == "Crohn's Disease" &
                                                                                                                                 datediff <= t) %>% drop_na(PRO3_SCORE) %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                                                                                                                                    index_date, desc(PRO3_SOURCE), desc(PRO3_SCORE)) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    filter(datediff == min(abs(datediff))) %>% slice(1) %>%
    distinct() %>% ungroup() %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                                        index_date, starts_with("PRO3"))
  cohort <- cohort %>% left_join(pro3, by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                    index_date))

  #### UCDAI ----

  ucdai_ecrf <- data$observations %>% filter(DATA_SOURCE == "ECRF_QORUS") %>%
    filter(grepl("Stool|Blood", OBS_TEST_CONCEPT_NAME, ignore.case = T)) %>%
    mutate(result = ifelse(is.na(DESCRIPTIVE_SYMP_TEST_RESULTS),
                           TEST_RESULT_NUMERIC, DESCRIPTIVE_SYMP_TEST_RESULTS)) %>%
    mutate(result = case_when(result %in% c("Normal", "Normal (same as when I am well)",
                                            "Less stool than normal") ~ 0, result == "1-2 stools/day more than normal" ~
                                1, result == "3-4 stools/day more than normal" ~
                                2, result == "5 or more stools per day more than normal" ~
                                3, result == "No blood seen" ~ 0, result == "Blood less than 50% of the time" ~
                                1, OBS_TEST_CONCEPT_NAME == "Blood in Stool" & result ==
                                "Blood 50% or more of the time" ~ 2, OBS_TEST_CONCEPT_NAME ==
                                "Blood Passed Alone" & result %in% c("Yes", "Blood 50% or more of the time") ~
                                3, TRUE ~ as.numeric(result))) %>% distinct(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                            OBS_TEST_RESULT_DATE, OBS_TEST_CONCEPT_NAME, result) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, OBS_TEST_RESULT_DATE,
             OBS_TEST_CONCEPT_NAME) %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                OBS_TEST_CONCEPT_NAME, desc(result), .by_group = T) %>%
    slice(1) %>% ungroup() %>% pivot_wider(id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                       OBS_TEST_RESULT_DATE), names_from = c(OBS_TEST_CONCEPT_NAME),
                                           values_from = c(result)) %>% mutate(R = ifelse(is.na(`Blood Passed Alone`),
                                                                                          `Blood in Stool`, `Blood Passed Alone`), S = `Recent Change in Daily Stool Frequency`) %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, OBS_TEST_RESULT_DATE) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>% mutate(diff = OBS_TEST_RESULT_DATE -
                                                          lag(OBS_TEST_RESULT_DATE), diff2 = lead(OBS_TEST_RESULT_DATE) -
                                                          OBS_TEST_RESULT_DATE) %>% ungroup() %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>%
    mutate(S = ifelse(is.na(S) & (diff <= 7), lag(S), S),
           R = ifelse(is.na(R) & (diff <= 7), lead(R), R)) %>%
    mutate(S = ifelse(is.na(S) & (diff2 <= 7), lead(S),
                      S), R = ifelse(is.na(R) & (diff2 <= 7), lead(R),
                                     R)) %>% dplyr::rename(Stool.Freq.Score = S, Rectal.Bleeding.Score = R) %>%
    mutate(UCDAI.6.score = Stool.Freq.Score + Rectal.Bleeding.Score,
           Source = "ECRF") %>% mutate(UCDAI.date = OBS_TEST_RESULT_DATE) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, UCDAI.6.score,
           UCDAI.date, Source, Stool.Freq.Score, Rectal.Bleeding.Score)
  UCDAI <- ucdai_ecrf %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                  UCDAI.date) %>% dplyr::rename(ucdai.source = Source) %>%
    distinct_all() %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, desc(UCDAI.6.score)) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, UCDAI.6.score,
             UCDAI.date, ucdai.source, Stool.Freq.Score,
             Rectal.Bleeding.Score) %>%
    ungroup() %>% select(sort(names(.))) %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                    everything()) %>% dplyr::mutate(ucdai6.category = case_when(UCDAI.6.score <
                                                                                                                  2 ~ "Remission", UCDAI.6.score >= 2 & UCDAI.6.score <=
                                                                                                                  3 ~ "Mild", UCDAI.6.score >= 4 & UCDAI.6.score <= 5 ~
                                                                                                                  "Moderate", UCDAI.6.score >= 6 ~ "Severe", TRUE ~ as.character(NA))) %>%
    setNames(toupper(names(.))) %>% setNames(gsub("\\.",
                                                  "_", names(.)))

  ucdai <- UCDAI %>% left_join(cohort) %>%
    mutate(datediff = abs(UCDAI_DATE - index_date)) %>%
    filter(DIAGNOSIS == "Ulcerative Colitis" & datediff <=
             t) %>% drop_na(UCDAI_6_SCORE) %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                       index_date, desc(UCDAI_SOURCE), desc(UCDAI_6_SCORE)) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    filter(datediff == min(abs(datediff))) %>% slice(1) %>%
    distinct() %>% ungroup() %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                                        index_date, intersect(names(.), names(calculate_ucdai(data$observations))))
  cohort <- cohort %>% left_join(ucdai)

  #### QORUS PGA ----
  PGA <- data$observations %>% filter(DATA_SOURCE == "ECRF_QORUS") %>%
    filter(OBS_TEST_CONCEPT_NAME == "Physician Global Assessment (PGA)") %>% dplyr::rename(PGA = DESCRIPTIVE_SYMP_TEST_RESULTS) %>%
    mutate(PGA.date = (OBS_TEST_RESULT_DATE)) %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                         PGA, PGA.date) %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                                    PGA.date) %>% mutate(PGA.source = "ECRF") %>% distinct_all() %>%
    setNames(toupper(names(.))) %>% setNames(gsub("\\.",
                                                  "_", names(.)))

  pga <- PGA %>% left_join(cohort) %>%
    mutate(datediff = abs(PGA_DATE - index_date)) %>% filter(datediff <=
                                                               t) %>% drop_na(PGA) %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                                               index_date, desc(PGA_SOURCE), desc(PGA)) %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                                                                                                     index_date) %>% filter(datediff == min(abs(datediff))) %>%
    slice(1) %>% distinct() %>% ungroup() %>% select(-datediff) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, intersect(names(.),
                                                                 names(calculate_pga(data$observations))))
  cohort <- cohort %>% left_join(pga)


  #### QORUS OSTOMY ----

  ostomy_ecrf <- data$observations %>% filter(DATA_SOURCE ==
                                                "ECRF_QORUS") %>% filter(OBS_TEST_CONCEPT_NAME %in%
                                                                           c("Baseline Number of Daily Bowel Movements", "Current Average Number of Daily Bowel Movements",
                                                                             "Recent Change in Daily Stool Frequency", "Current Average Number of Daily Liquid Bowel Movements")) %>%
    filter(DESCRIPTIVE_SYMP_TEST_RESULTS == "Not applicable, I have an ostomy") %>%
    mutate(ostomy = DESCRIPTIVE_SYMP_TEST_RESULTS) %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                              ostomy, VISIT_ENCOUNTER_ID) %>% left_join(data$encounter) %>%
    left_join(cohort) %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID,
                                   index_date) %>% mutate(diff = (VISIT_ENCOUNTER_START_DATE) -
                                                            index_date) %>% drop_na(ostomy) %>% slice(which.min(abs(diff))) %>%
    ungroup() %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                         ostomy, index_date, diff)
  ostomy <- ostomy_ecrf %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID,
                                     index_date) %>% slice(which.min(abs(diff))) %>% ungroup() %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, ostomy)
  cohort <- cohort %>% left_join(ostomy) %>% mutate(ostomy = case_when(DIAGNOSIS ==
                                                                         "Crohn's Disease" & is.na(SCDAI_CATEGORY) ~ ostomy,
                                                                       DIAGNOSIS == "Ulcerative Colitis" & is.na(UCDAI6_CATEGORY) ~
                                                                         ostomy, TRUE ~ as.character(NA)))
  cohort <- cohort %>% mutate(DISEASE_ACTIVITY = case_when(DIAGNOSIS ==
                                                             "Crohn's Disease" ~ SCDAI_CATEGORY, DIAGNOSIS == "Ulcerative Colitis" ~
                                                             UCDAI6_CATEGORY, TRUE ~ as.character(NA)))
  cohort <- cohort %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                               index_date) %>% setNames(gsub(" ", "_", names(.))) %>%
    select(-INDEX_DATE)
  if ("OMICS" %in% index_info) {
    cohort <- omics %>% left_join(cohort, by = c("DEIDENTIFIED_MASTER_PATIENT_ID",
                                                 "index_date"))
  }
  else {
    cohort <- cohort
  }
  cohort <- ibdplexus:::fix_col_names(cohort)

  # ALL SCORES ----

  qorus_scores_all <- list(diagnosis = dx, scdai = scdai, ucdai = ucdai, pga = pga, pro2 = pro2, pro3 = pro3)

  # sparc_scores <- lapply(sparc_scores,function(x) {colnames(x) <- toupper(colnames(x));x})

  if (export == "TRUE") {
    write.xlsx(qorus_scores_all, paste0("QORUS_scores_", Sys.Date(), ".xlsx"), colnames = T)
  }


  return(qorus_scores_all)

  # if (export == T) {
  #   style1 <- createStyle(bgFill = "#BDD7EE", textDecoration = "bold")
  #   wb <- createWorkbook()
  #   addWorksheet(wb, "scores_at_index")
  #   writeData(wb, "scores_at_index", x = cohort, startCol = 1,
  #             startRow = 1, colNames = TRUE, rowNames = FALSE)
  #   rown <- dim(cohort)[1]
  #   coln <- dim(cohort)[2]
  #   conditionalFormatting(wb, "scores_at_index", cols = 1:coln,
  #                         rows = 1, rule = "!=0", style = style1)
  #   saveWorkbook(wb, file = paste0(filename), overwrite = TRUE)
  #   return(cohort)
  # }
  # else {
  #   return(cohort)
  # }
}
