#### OQRUS SCORES ----
# qorus_scores
#' Create QORUS Scores Table - all responses
#'
#' @param data A list of dataframes, typically generated by a call to load_data. Must include demographics, diagnosis, encounter, procedures, and observations. Only CRF data needs to be uploaded.
#' @param filename the name of the output file. Must be .xlsx.
#' @param location_logic specify which CD location function to use. If using logic developed by AZ then use location_logic = "AZ".
#' @param export if TRUE then writes the data frame to its own excel file
#'
#' @return qorus scores table
#' @export

qorus_scores <- function (data, filename = "QORUS_SCORES.xlsx",
                              location_logic = "CCF", export = T)
{

  consent <- extract_consent(data$demographics, "QORUS")
  demo <- extract_demo(data$demographics, "QORUS")
  dx <- extract_diagnosis(data$diagnosis, data$encounter, data$demographics, "QORUS") %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, DIAGNOSIS, DIAGNOSIS_DATE)
  table <- consent %>% left_join(demo, by = "DEIDENTIFIED_MASTER_PATIENT_ID") %>%
    left_join(dx, by = "DEIDENTIFIED_MASTER_PATIENT_ID")

  gc()

  # cohort <- table

  #### QORUS SCDAI ----


  scdai_ecrf <- data$observations %>% filter(DATA_SOURCE == "ECRF_QORUS") %>%
    filter(grepl("Abdominal Pain|General Well|Bowel Movements",
                 OBS_TEST_CONCEPT_NAME, ignore.case = T)) %>% filter(OBS_TEST_CONCEPT_NAME !=
                                                                       "Baseline Number of Daily Bowel Movements") %>% mutate(result = ifelse(is.na(DESCRIPTIVE_SYMP_TEST_RESULTS),
                                                                                                                                              TEST_RESULT_NUMERIC, DESCRIPTIVE_SYMP_TEST_RESULTS)) %>%
    mutate(result = case_when(result == "None" ~ 0, result ==
                                "Mild" ~ 1, result == "Moderate" ~ 2, result ==
                                "Severe" ~ 3, result == "Generally well" ~ 0, result ==
                                "Slightly under par" ~ 1, result == "Poor" ~ 2,
                              result == "Very poor" ~ 3, result == "Terrible" ~
                                4, result == "20+" ~ 20, TRUE ~ as.numeric(result))) %>%
    mutate(result = ifelse(result > 20, 20, result)) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, OBS_TEST_RESULT_DATE,
             OBS_TEST_CONCEPT_NAME, result) %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                         OBS_TEST_RESULT_DATE, OBS_TEST_CONCEPT_NAME) %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                                                                  OBS_TEST_CONCEPT_NAME, desc(result)) %>% slice(1) %>%
    ungroup() %>% pivot_wider(id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID,
                                          OBS_TEST_RESULT_DATE), names_from = c(OBS_TEST_CONCEPT_NAME),
                              values_from = c(result)) %>% mutate(aug18 = ifelse(OBS_TEST_RESULT_DATE <
                                                                                   as.Date("01-AUG-2018", format = "%d-%b-%Y"), "before",
                                                                                 "after")) %>% mutate(A = `Abdominal Pain`, B = if_else(aug18 ==
                                                                                                                                          "before" & !is.na(`Current Average Number of Daily Bowel Movements`),
                                                                                                                                        `Current Average Number of Daily Bowel Movements`, `Current Average Number of Daily Liquid Bowel Movements`),
                                                                                                      B = ifelse(is.na(B), `Current Average Number of Daily Bowel Movements`,
                                                                                                                 B), G = `General Well-Being`) %>% mutate(Daily.BM.Question = case_when(B ==
                                                                                                                                                                                          `Current Average Number of Daily Liquid Bowel Movements` ~
                                                                                                                                                                                          "Current Average Number of Daily Liquid Bowel Movements",
                                                                                                                                                                                        B == `Current Average Number of Daily Bowel Movements` ~
                                                                                                                                                                                          "Current Average Number of Daily Bowel Movements",
                                                                                                                                                                                        TRUE ~ as.character(NA))) %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                                                                                                                                                                              OBS_TEST_RESULT_DATE) %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>%
    mutate(diff = OBS_TEST_RESULT_DATE - lag(OBS_TEST_RESULT_DATE),
           diff2 = lead(OBS_TEST_RESULT_DATE) - OBS_TEST_RESULT_DATE) %>%
    mutate(A = ifelse(is.na(A) & diff <= 7, lag(A), A),
           G = ifelse(is.na(G) & diff <= 7, lag(G), G), B = ifelse(is.na(B) &
                                                                     diff <= 7, lag(B), B), Daily.BM.Question = ifelse(is.na(Daily.BM.Question) &
                                                                                                                         (diff <= 7), lag(Daily.BM.Question), Daily.BM.Question)) %>%
    mutate(A = ifelse(is.na(A) & (diff2 <= 7), lead(A),
                      A), G = ifelse(is.na(G) & (diff2 <= 7), lead(G),
                                     G), B = ifelse(is.na(B) & (diff2 <= 7), lead(B),
                                                    B), Daily.BM.Question = ifelse(is.na(Daily.BM.Question) &
                                                                                     (diff2 <= 7), lead(Daily.BM.Question), Daily.BM.Question)) %>%
    dplyr::rename(Daily.BM = B, Abdominal.Pain.Score = A,
                  General.well.being.score = G) %>% mutate(sCDAI.score = 44 +
                                                             (2 * 7 * Daily.BM) + (5 * 7 * Abdominal.Pain.Score) +
                                                             (7 * 7 * General.well.being.score), Source = "ECRF") %>%
    dplyr::rename(sCDAI.date = OBS_TEST_RESULT_DATE) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, sCDAI.date, sCDAI.score,
           Source, Daily.BM, Abdominal.Pain.Score, General.well.being.score,
           Daily.BM.Question)
  sCDAI <- scdai_ecrf %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                  desc(sCDAI.score), sCDAI.date) %>% dplyr::rename(scdai.source = Source) %>%
    distinct_all() %>%
    # mutate(Daily.BM.Version = case_when(Daily.BM.Question ==
    #                                                          "Current Average Number of Daily Bowel Movements" ~
    #                                                          1, Daily.BM.Question == "Current Average Number of Daily Liquid Bowel Movements" ~
    #                                                          2, Daily.BM.Question == "Current Maximum Number of Daily Bowel Movements" ~
    #                                                          3)) %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, desc(sCDAI.score)) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, sCDAI.date,
             sCDAI.score, scdai.source, Daily.BM,
             Abdominal.Pain.Score, General.well.being.score) %>%
    ungroup() %>% select(sort(names(.))) %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                    everything()) %>% dplyr::mutate(sCDAI.category = case_when(sCDAI.score <
                                                                                                                 150 ~ "Remission", sCDAI.score >= 150 & sCDAI.score <=
                                                                                                                 219 ~ "Mild", sCDAI.score >= 220 & sCDAI.score <= 450 ~
                                                                                                                 "Moderate", sCDAI.score > 450 ~ "Severe", TRUE ~ as.character(NA))) %>%
    setNames(toupper(names(.))) %>% setNames(gsub("\\.",
                                                  "_", names(.)))

  scdai <- sCDAI %>% left_join(cohort) %>%
    drop_na(SCDAI_SCORE) %>%
    distinct() %>% ungroup() %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                                         intersect(names(.), names(calculate_scdai(data$observations))))




  # cohort <- cohort %>% left_join(scdai)

  #### QORUS PRO2 ----
  pro2_ecrf <- data$observations %>% filter(DATA_SOURCE == "ECRF_QORUS") %>%
    filter(OBS_TEST_CONCEPT_NAME %in% c("Current Average Number of Daily Liquid Bowel Movements",
                                        "Abdominal Pain")) %>% mutate(result = ifelse(is.na(DESCRIPTIVE_SYMP_TEST_RESULTS),
                                                                                      TEST_RESULT_NUMERIC, DESCRIPTIVE_SYMP_TEST_RESULTS)) %>%
    mutate(result = case_when(result == "None" ~ 0, result ==
                                "Mild" ~ 1, result == "Moderate" ~ 2, result ==
                                "Severe" ~ 3, result == "20+" ~ 20, TRUE ~ as.numeric(result))) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, OBS_TEST_RESULT_DATE,
             OBS_TEST_CONCEPT_NAME, result) %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                         OBS_TEST_RESULT_DATE, OBS_TEST_CONCEPT_NAME) %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                                                                  OBS_TEST_CONCEPT_NAME, desc(result), .by_group = T) %>%
    slice(1) %>% ungroup() %>% pivot_wider(id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                       OBS_TEST_RESULT_DATE), names_from = c(OBS_TEST_CONCEPT_NAME),
                                           values_from = c(result)) %>% mutate(A = `Abdominal Pain`,
                                                                               B = `Current Average Number of Daily Liquid Bowel Movements`) %>%
    ungroup() %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                          OBS_TEST_RESULT_DATE) %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>%
    mutate(diff = OBS_TEST_RESULT_DATE - lag(OBS_TEST_RESULT_DATE),
           diff2 = lead(OBS_TEST_RESULT_DATE) - OBS_TEST_RESULT_DATE) %>%
    ungroup() %>% mutate(A = ifelse(is.na(A) & diff <= 7,
                                    lag(A), A), B = ifelse(is.na(B) & diff <= 7, lag(B),
                                                           B)) %>% mutate(A = ifelse(is.na(A) & (diff2 <= 7), lead(A),
                                                                                     A), B = ifelse(is.na(B) & (diff2 <= 7), lead(B), B)) %>%
    dplyr::rename(Liquid.BM = B, Abdominal.Pain.Score = A) %>%
    mutate(pro2.score = (Liquid.BM * 2) + (Abdominal.Pain.Score *
                                             5), Source = "ECRF") %>% dplyr::rename(pro2.date = OBS_TEST_RESULT_DATE) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, pro2.date, pro2.score,
           Source, Liquid.BM, Abdominal.Pain.Score)
  PRO2 <- pro2_ecrf %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                pro2.date) %>% dplyr::rename(pro2.source = Source) %>%
    distinct_all() %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                              pro2.date, pro2.score, pro2.source, Liquid.BM, Abdominal.Pain.Score) %>%
    ungroup() %>% dplyr::mutate(pro2.category = case_when(pro2.score <
                                                            8 ~ "Remission", pro2.score >= 8 & pro2.score <= 13 ~
                                                            "Mild", pro2.score >= 14 & pro2.score <= 35 ~ "Moderate",
                                                          pro2.score > 35 ~ "Severe", TRUE ~ as.character(NA))) %>%
    select(sort(names(.))) %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                                      everything()) %>% setNames(toupper(names(.))) %>% setNames(gsub("\\.",
                                                                                                      "_", names(.)))

  pro2 <- PRO2 %>% left_join(cohort %>% distinct(DEIDENTIFIED_MASTER_PATIENT_ID),
                             by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID)) %>%  drop_na(PRO2_SCORE) %>%
    distinct() %>% ungroup() %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                                         starts_with("PRO2"), ABDOMINAL_PAIN_SCORE, LIQUID_BM)
  # cohort <- cohort %>% left_join(pro2, by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID))

  #### QORUS PRO3 ----

  pro3_ecrf <- data$observations %>% filter(DATA_SOURCE == "ECRF_QORUS") %>%
    filter(OBS_TEST_CONCEPT_NAME %in% c("Current Average Number of Daily Liquid Bowel Movements",
                                        "Abdominal Pain", "General Well-Being")) %>% mutate(result = ifelse(is.na(DESCRIPTIVE_SYMP_TEST_RESULTS),
                                                                                                            TEST_RESULT_NUMERIC, DESCRIPTIVE_SYMP_TEST_RESULTS)) %>%
    mutate(result = ifelse(is.na(DESCRIPTIVE_SYMP_TEST_RESULTS),
                           TEST_RESULT_NUMERIC, DESCRIPTIVE_SYMP_TEST_RESULTS)) %>%
    mutate(result = case_when(result == "None" ~ 0, result ==
                                "Mild" ~ 1, result == "Moderate" ~ 2, result ==
                                "Severe" ~ 3, result == "Generally well" ~ 0, result ==
                                "Slightly under par" ~ 1, result == "Poor" ~ 2,
                              result == "Very poor" ~ 3, result == "Terrible" ~
                                4, result == "20+" ~ 20, TRUE ~ as.numeric(result))) %>%
    mutate(result = ifelse(result > 20, 20, result)) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, OBS_TEST_RESULT_DATE,
             OBS_TEST_CONCEPT_NAME, result) %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                         OBS_TEST_RESULT_DATE, OBS_TEST_CONCEPT_NAME) %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                                                                  OBS_TEST_CONCEPT_NAME, desc(result), .by_group = T) %>%
    slice(1) %>% pivot_wider(id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID,
                                         OBS_TEST_RESULT_DATE), names_from = c(OBS_TEST_CONCEPT_NAME),
                             values_from = c(result)) %>% mutate(A = `Abdominal Pain`,
                                                                 B = `Current Average Number of Daily Liquid Bowel Movements`,
                                                                 G = `General Well-Being`) %>% ungroup() %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                                                                     OBS_TEST_RESULT_DATE) %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>%
    mutate(diff = OBS_TEST_RESULT_DATE - lag(OBS_TEST_RESULT_DATE),
           diff2 = lead(OBS_TEST_RESULT_DATE) - OBS_TEST_RESULT_DATE) %>%
    ungroup() %>% mutate(A = ifelse(is.na(A) & diff <= 7,
                                    lag(A), A), B = ifelse(is.na(B) & diff <= 7, lag(B),
                                                           B), G = ifelse(is.na(G) & diff <= 7, lag(G), G)) %>%
    mutate(A = ifelse(is.na(A) & (diff2 <= 7), lead(A),
                      A), B = ifelse(is.na(B) & (diff2 <= 7), lead(B),
                                     B), G = ifelse(is.na(G) & (diff2 <= 7), lead(G),
                                                    G)) %>% dplyr::rename(Liquid.BM = B, Abdominal.Pain.Score = A,
                                                                          General.well.being.score = G) %>% mutate(pro3.score = (Liquid.BM *
                                                                                                                                   2) + (Abdominal.Pain.Score * 5) + (General.well.being.score *
                                                                                                                                                                        7), Source = "ECRF") %>% dplyr::rename(pro3.date = OBS_TEST_RESULT_DATE) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, pro3.date, pro3.score,
           Source, Liquid.BM, Abdominal.Pain.Score, General.well.being.score)
  PRO3 <- pro3_ecrf %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                pro3.date) %>% dplyr::rename(pro3.source = Source) %>%
    distinct_all() %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                              pro3.date, pro3.score, pro3.source, Liquid.BM, Abdominal.Pain.Score,
                              General.well.being.score) %>% ungroup() %>% dplyr::mutate(pro3.category = case_when(pro3.score <
                                                                                                                    13 ~ "Remission", pro3.score >= 13 & pro3.score <= 21 ~
                                                                                                                    "Mild", pro3.score >= 22 & pro3.score <= 53 ~ "Moderate",
                                                                                                                  pro3.score > 53 ~ "Severe", TRUE ~ as.character(NA))) %>%
    select(sort(names(.))) %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                                      everything()) %>% setNames(toupper(names(.))) %>% setNames(gsub("\\.",
                                                                                                      "_", names(.)))

  pro3 <- PRO3 %>% left_join(cohort %>% distinct(DEIDENTIFIED_MASTER_PATIENT_ID),
                             by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID)) %>% drop_na(PRO3_SCORE) %>%
    distinct() %>% ungroup() %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                                         starts_with("PRO3"), ABDOMINAL_PAIN_SCORE, LIQUID_BM, GENERAL_WELL_BEING_SCORE)
  # cohort <- cohort %>% left_join(pro3, by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID))

  #### UCDAI ----



  ucdai_ecrf <- data$observations %>% filter(DATA_SOURCE == "ECRF_QORUS") %>%
    filter(grepl("Stool|Blood|Global Assessment",
                 OBS_TEST_CONCEPT_NAME, ignore.case = T)) %>% mutate(result = ifelse(is.na(DESCRIPTIVE_SYMP_TEST_RESULTS),
                                                                                     TEST_RESULT_NUMERIC, DESCRIPTIVE_SYMP_TEST_RESULTS)) %>%
    mutate(result = case_when(result %in% c("Normal", "Normal (same as when I am well)",
                                            "Less stool than normal") ~ 0, result == "1-2 stools/day more than normal" ~
                                1, result == "3-4 stools/day more than normal" ~
                                2, result == "5 or more stools per day more than normal" ~
                                3, result == "No blood seen" ~ 0, result == "Blood less than 50% of the time" ~
                                1, OBS_TEST_CONCEPT_NAME == "Blood in Stool" & result ==
                                "Blood 50% or more of the time" ~ 2, OBS_TEST_CONCEPT_NAME ==
                                "Blood Passed Alone" & result %in% c("Yes", "Blood 50% or more of the time") ~
                                3, result ==
                                "Quiescent" ~ 0, result == "Mild" ~ 1, result ==
                                "Moderate" ~ 2, result == "Severe" ~ 3, TRUE ~ as.numeric(result))) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, OBS_TEST_RESULT_DATE,
             OBS_TEST_CONCEPT_NAME, result) %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                         OBS_TEST_RESULT_DATE, OBS_TEST_CONCEPT_NAME) %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                                                                  OBS_TEST_CONCEPT_NAME, desc(result), .by_group = T) %>%
    slice(1) %>% ungroup() %>% pivot_wider(id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                       OBS_TEST_RESULT_DATE), names_from = c(OBS_TEST_CONCEPT_NAME),
                                           values_from = c(result)) %>% mutate(T = `Physician Global Assessment (PGA)`,
                                                                               R = ifelse(is.na(`Blood Passed Alone`),
                                                                                                 `Blood in Stool`, `Blood Passed Alone`), S = `Recent Change in Daily Stool Frequency`) %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, OBS_TEST_RESULT_DATE) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>% mutate(diff = OBS_TEST_RESULT_DATE -
                                                          lag(OBS_TEST_RESULT_DATE), diff2 = lead(OBS_TEST_RESULT_DATE) -
                                                          OBS_TEST_RESULT_DATE) %>% ungroup() %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>%
    mutate(T = ifelse(is.na(T) & (diff <= 7), lag(T), T),
           S = ifelse(is.na(S) & (diff <= 7), lag(S), S), R = ifelse(is.na(R) &
                                                                       (diff <= 7), lag(R), R)) %>% mutate(T = ifelse(is.na(T) &
                                                                                                                        (diff2 <= 7), lead(T), T), S = ifelse(is.na(S) & (diff2 <=
                                                                                                                                                                            7), lead(S), S), R = ifelse(is.na(R) & (diff2 <= 7),
                                                                                                                                                                                                        lead(R), R)) %>% dplyr::rename(Stool.Freq.Score = S,
                                                                                                                                                                                                                                       Rectal.Bleeding.Score = R, Global.Assessment.Score = T) %>%
    mutate(UCDAI.6.score = Stool.Freq.Score + Rectal.Bleeding.Score,
           UCDAI.9.score = Stool.Freq.Score + Rectal.Bleeding.Score +
             Global.Assessment.Score, Source = "SF") %>%
    mutate(UCDAI.date = OBS_TEST_RESULT_DATE) %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                         UCDAI.6.score, UCDAI.9.score, UCDAI.date, Source, Stool.Freq.Score,
                                                         Rectal.Bleeding.Score, Global.Assessment.Score)

  UCDAI <- ucdai_ecrf %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                  UCDAI.date) %>% dplyr::rename(ucdai.source = Source) %>%
    distinct_all() %>% group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, desc(UCDAI.6.score)) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, UCDAI.6.score, UCDAI.9.score,
             UCDAI.date, ucdai.source, Stool.Freq.Score,
             Rectal.Bleeding.Score, Global.Assessment.Score) %>%
    ungroup() %>% select(sort(names(.))) %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                    everything()) %>% dplyr::mutate(ucdai6.category = case_when(UCDAI.6.score <
                                                                                                                  2 ~ "Remission", UCDAI.6.score >= 2 & UCDAI.6.score <=
                                                                                                                  3 ~ "Mild", UCDAI.6.score >= 4 & UCDAI.6.score <= 5 ~
                                                                                                                  "Moderate", UCDAI.6.score >= 6 ~ "Severe", TRUE ~ as.character(NA))) %>%
    setNames(toupper(names(.))) %>% setNames(gsub("\\.",
                                                  "_", names(.)))

  ucdai <- UCDAI %>% left_join(cohort %>% distinct(DEIDENTIFIED_MASTER_PATIENT_ID)) %>%
    drop_na(UCDAI_6_SCORE) %>%
    distinct() %>% ungroup() # %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                                         # intersect(names(.), names(calculate_ucdai(data$observations))))
  # cohort <- cohort %>% left_join(ucdai)

  #### QORUS PGA ----
  PGA <- data$observations %>% filter(DATA_SOURCE == "ECRF_QORUS") %>%
    filter(OBS_TEST_CONCEPT_NAME == "Physician Global Assessment (PGA)") %>% dplyr::rename(PGA = DESCRIPTIVE_SYMP_TEST_RESULTS) %>%
    mutate(PGA.date = (OBS_TEST_RESULT_DATE)) %>% select(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                         PGA, PGA.date) %>% arrange(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                                    PGA.date) %>% mutate(PGA.source = "ECRF") %>% distinct_all() %>%
    setNames(toupper(names(.))) %>% setNames(gsub("\\.",
                                                  "_", names(.)))

  pga <- PGA %>% left_join(cohort %>% distinct(DEIDENTIFIED_MASTER_PATIENT_ID)) %>%
    drop_na(PGA) %>%
    distinct() %>% ungroup() %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID,  intersect(names(.),
                                                                 names(calculate_pga(data$observations)))) %>%
    mutate(PGA = if_else(PGA == "Remission", "Quiescent", PGA))
  # cohort <- cohort %>% left_join(pga)


  # cohort <- ibdplexus:::fix_col_names(cohort)

  # ALL SCORES ----

  qorus_scores_all <- list(diagnosis = dx, scdai = scdai,
                           ucdai = ucdai,
                           pga = pga,
                           pro2 = pro2,
                           pro3 = pro3)


  if (export == "TRUE") {
    write.xlsx(qorus_scores_all, paste0("QORUS_scores_", Sys.Date(), ".xlsx"), colnames = T)
  }


  return(qorus_scores_all)


}
