# # temp code to test SPARC
# demo <- load_data(datadir = "~/r_input/", domains = "demographics", cohort = "SPARC", data_type = "BOTH") %>% bind_rows()
# r <- extract_race(demo, "SPARC")

#' categorize race
#'
#' Categorize race & ethnicity into minimum choices from Collection of Race and Ethnicity Date in Clinical Trials and Clinical Studies for FDA-Regulated Medication Products
#' https://pink.citeline.com/-/media/supporting-documents/pink-sheet/2024/01/race_ethnicity_data_guidance_01292024.pdf?rev=1b3d813f6d254080bae6ec3e6ab872d0&hash=C485BD27F152B7DEBB819B012A644178&utm_campaign=The%20Evidence%20Digest&utm_medium=email&_hsmi=296353360&_hsenc=p2ANqtz-9lXtx6rO5GP2zHvxvxL4TwfKjSw5KZtP7MxmnXiPWJjaYt6F1LrPLIkiWqX1ynqmmFwtcgwsqewXuX5I25Dz7B5pi2Z6nYr_mmXnSEO0xIBNfWL6A&utm_content=296353360&utm_source=hs_email
#' EMR and eCRF data sources are used
#'
#'
#' @param race the data frame generated by extract_race function
#'
#' @return A dataframe with categorized race & ethnicity information stored in column RACE_CAT and ETHNICITY_CAT.
#' @export
categorize_race <- function(race) {


  race <-  race %>%
    mutate(R = toupper(RACE),
           E = toupper(ETHNICITY)) %>%
    mutate(R = case_when(
      R %in% c("DECLINED", "UNABLE TO ANSWER", "NOT REPORTED", "PATIENT DID NOT SPECIFY", "NONE SELECTED", "PREFER NOT TO ANSWER","PREFER NOT TO DISCLOSE") ~ "Patient Declined",
      grepl("American Indian", R, ignore.case = T) ~ "American Indian or Alaska Native",
      grepl("Pacific Island", R, ignore.case = T) ~ "Native Hawaiian or Other Pacific Islander",
      grepl("Asian|Indian", R, ignore.case = T) ~ "Asian",
      grepl("Black", R, ignore.case = T) ~ "Black or African American",
      grepl("White", R, ignore.case = T) ~ "White",
      grepl("Unknown", R, ignore.case = T) ~ "Unknown",
      is.na(R) ~ as.character(NA),
      TRUE ~ "Other")) %>%
    mutate(R = ifelse(grepl(";|/", RACE) | RACE == "ASIAN AND EUROPEAN" , "Mixed", R)) %>%
    mutate(E = case_when(grepl("Hispanic|Mexican|Cuban|Puerto", R, ignore.case = T) |
                           E %in% c("HISPANIC", "HISPANIC OR LATINO", "ANOTHER HISPANIC, LATINO/A, OR SPANISH ORIGIN",
                                    "SPANISH/HISPANIC ORIGIN", "HISPANIC OR LATINO/A/E") ~ "Hispanic or Latino",
                         !(grepl("Hispanic|Mexican|Cuban|Puerto", RACE, ignore.case = T)) &
                           E %in% c("NON-HISPANIC OR LATINO/A", "NOT HISPANIC", "NOT HISPANIC OR LATINO",
                                    "NOT HISPANIC, LATINO/A, OR SPANISH ORIGIN", "NON-HISPANIC OR LATINO",
                                    "NOT HISPANIC OR LATINO/A/E") ~ "Not Hispanic or Latino",
                         E %in% c("DECLINED", "NONE OF THESE", "PREFER NOT TO DISCLOSE",
                                  "UNABLE TO PROVIDE", "UNREPORTED/CHOSE NOT TO DISCLOSE",
                                  "Unable to provide", "PREFER NOT TO DISCLOSE; UNKNOWN OR PATIENT UNABLE TO RESPOND",
                                  "PREFER NOT TO ANSWER", "CHOOSE NOT TO DISCLOSE",
                                  "DECLINE TO ANSWER", "DECLINE TO SPECIFY", "UNREPORTED/CHOSE NOT TO DISCLOSE") ~ "Patient Declined",
                         E %in% c("UNKNOWN", "I DO NOT KNOW", "UNKNOWN OR PATIENT UNABLE TO RESPOND",
                                  "UNABLE TO PROVIDE") ~ "Unknown",
                         TRUE ~ E)) %>%
    dplyr::mutate(RACE_CAT = gsub("(?<=\\b)([a-z])", "\\U\\1", tolower(R), perl=TRUE), ETHNICITY_CAT = gsub("(?<=\\b)([a-z])", "\\U\\1", tolower(E), perl=TRUE)) %>%
    mutate(ETHNICITY_CAT = ifelse(is.na(ETHNICITY), "Missing", ETHNICITY),
           RACE_CAT = ifelse(is.na(RACE), "Missing", RACE)) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, RACE_CAT, ETHNICITY_CAT)

}
