#' sparc_med_ends
#'
#' #' Find medication discontinuation date from SPARC patient reported and electronic medical record data.
#'
#'
#' @param medication A dataframe with generated by sparc_med_filter
#'
#' @return A dataframe with the medication end date
#'
#' @details Medication start and stop dates are chosen independently from both
#'   eCRF and EMR sources. Medications with a start or stop date before 1980 are
#'   dropped.
#'
#'   If eCRF data source OR EMR data source says that medication was stopped
#'   then count it as true. Consider medication end date for eCRF and EMR data
#'   sources and medication discontinue date for EMR.#'   The earliest of these
#'   dates is the end date. For EMR, if there is no prescription within 60 days
#'   or if there is a discontinuation date but a new prescription within 60 days
#'   then they are considered to be continuously on it.
#'
#'
#'
sparc_med_ends <- function(medication) {
  # ECRF DATA ----

  # Find End Date in eCRF Data ----
  end_ecrf <- medication %>%
    filter(DATA_SOURCE == "ECRF_SPARC" | DATA_SOURCE == "ECRF") %>%
    mutate(
      MED_START_DATE = if_else(year(MED_START_DATE) > 1980, MED_START_DATE, as.Date(NA, format = "%d-%m-%y")),
      MED_END_DATE = if_else(year(MED_END_DATE) > 1980, MED_END_DATE, as.Date(NA, format = "%d-%m-%y"))
    ) %>%
    pivot_longer(cols = c(MED_START_DATE, MED_END_DATE), names_to = "type", values_to = "date") %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, new_med_name, DATA_SOURCE, match(type, c("MED_END_DATE", "MED_START_DATE"))) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, new_med_name, DATA_SOURCE) %>%
    slice(which.max(date)) %>%
    pivot_wider(names_from = type, values_from = date) %>%
    ungroup() %>%
    drop_na(MED_END_DATE) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, DATA_SOURCE, new_med_name, MED_END_DATE) %>%
    rename(
      MEDICATION = new_med_name,
      MED_END_DATE_ECRF = MED_END_DATE
    )


  # EMR Data ----


  # Find End Date in EMR Data ----
  end_emr <- medication %>%
    filter(DATA_SOURCE == "EMR") %>%
    mutate(MED_DISCONT_START_DATE_EMR = dmy(MED_DISCONT_START_DATE)) %>%
    mutate(
      MED_START_DATE = if_else(year(MED_START_DATE) > 1980, MED_START_DATE, as.Date(NA, format = "%d-%m-%y")),
      MED_END_DATE = if_else(year(MED_END_DATE) > 1980, MED_END_DATE, as.Date(NA, format = "%d-%m-%y")),
      MED_DISCONT_START_DATE_EMR = if_else(year(MED_DISCONT_START_DATE_EMR) > 1980, MED_DISCONT_START_DATE_EMR, as.Date(NA, format = "%d-%m-%y"))
    ) %>%
    mutate(drop = case_when(
      (!is.na(MED_END_DATE) | !is.na(MED_DISCONT_START_DATE_EMR)) ~ 0,
      TRUE ~ 1
    )) %>%
    filter(drop == 0) %>%
    pivot_longer(cols = c(MED_START_DATE, MED_END_DATE, MED_DISCONT_START_DATE_EMR), names_to = "type", values_to = "date") %>%
    drop_na(date) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, new_med_name, DATA_SOURCE, type, date) %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, new_med_name, DATA_SOURCE, match(type, c("MED_END_DATE", "MED_DISCONT_START_DATE_EMR", "MED_START_DATE"))) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, type, new_med_name, DATA_SOURCE) %>%
    slice(which.max(date)) %>%
    pivot_wider(names_from = type, values_from = date) %>%
    ungroup() %>%
    filter(!is.na(MED_END_DATE) | !is.na(MED_DISCONT_START_DATE_EMR)) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, DATA_SOURCE, new_med_name, MED_END_DATE, MED_DISCONT_START_DATE_EMR) %>%
    rename(
      MEDICATION = new_med_name,
      MED_END_DATE_EMR = MED_END_DATE
    )

  # Combine for eCRF and EMR  ----

  med_end <- full_join(end_ecrf, end_emr, by = c("DEIDENTIFIED_MASTER_PATIENT_ID", "MEDICATION")) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, MEDICATION, MED_END_DATE_EMR, MED_DISCONT_START_DATE_EMR, MED_END_DATE_ECRF) %>%
    rowwise() %>%
    mutate(MED_END_DATE = min(c_across(MED_END_DATE_EMR:MED_END_DATE_ECRF), na.rm = T)) %>%
    ungroup()
}
