#' sparc_medication
#'
#' Finds the medications the participant is prescribed from the
#' electronic medical record and patient reported case report forms at a
#' specific (“index”) date.
#'
#' When the index date is the date of consent, only the patient reported data is used.
#'
#' @param data A list of dataframes, typically generated by a call to load_data. Must include demographics, diagnosis, encounter, procedures, observations, biosample, omics_patient_mapping, and prescriptions.
#' @param index_info A dataframe  with DEIDENTIFIED_MASTER_PATIENT_ID and a variable index_date.  Other options include, enrollment, latest, endoscopy, omics, biosample collection.
#' @param med_groups A list of medication groups of interest. For details, refer to \code{\link{sparc_med_filter}}.
#' @param filename the name of the output file. Must be .xlsx. If filename is NULL no output file will be written.
#'
#' @return A dataframe with medication predictions.
#'
#' @details If two medications of the same MOA overlap, the start of the 2nd medication is used as the end date of the previous medication.
#' If a filename is specified, an excel file will be written as a side effect.
#' @export
sparc_medication <- function(data,
                             index_info = c("ENROLLMENT", "LATEST", "ENDOSCOPY", "OMICS", "BIOSAMPLE"),
                             med_groups = c("Biologic", "Aminosalicylates", "Immunomodulators", "Targeted synthetic small molecules"),
                             filename = "SPARC_MEDICATION.xlsx") {

  med_groups <- tolower(med_groups)
  if("character" %in% class(index_info)){index_info = toupper(index_info)}


  # Get all medication start dates ----

  med <- sparc_med_journey(data$prescriptions, data$demographics, data$observations, data$encounter, med_groups, export = FALSE)


  # CONSENT INFORMATION ----

  consent <- extract_consent(data$demographics, study = "SPARC") %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, DATE_OF_CONSENT, DATE_OF_CONSENT_WITHDRAWN)


  # DEMOGRAPHIC INFORMATION ----

  demo <- extract_demo(data$demographics, "SPARC")


  #  DIAGNOSIS & DIAGNOSIS_DATE ----


  dx <- extract_diagnosis(data$diagnosis, data$encounter, data$demographics, "SPARC")



  # CREATE TABLE ----

  table <- consent %>%
    left_join(demo, by = "DEIDENTIFIED_MASTER_PATIENT_ID") %>%
    left_join(dx, by = "DEIDENTIFIED_MASTER_PATIENT_ID")


  # CREATE INDEX_DATE ----

  if ("ENROLLMENT" %in% index_info) {
    cohort <- table %>% mutate(index_date = DATE_OF_CONSENT)
  } else if ("ENDOSCOPY" %in% index_info) {
    endoscopy <- extract_endoscopy(data$procedures)

    cohort <- endoscopy %>% left_join(table)
  } else if ("OMICS" %in% index_info) {
    omics <- data$omics_patient_mapping %>%
      mutate(SAMPLE_COLLECTED_DATE = dmy(SAMPLE_COLLECTED_DATE)) %>%
      mutate(index_date = SAMPLE_COLLECTED_DATE) %>%
      drop_na(index_date) %>%
      select(-c(DATA_SOURCE, DEIDENTIFIED_PATIENT_ID, VISIT_ENCOUNTER_ID)) %>%
      distinct()

    omics_index <- omics %>%
      distinct(DEIDENTIFIED_MASTER_PATIENT_ID, index_date)

    cohort <- omics_index %>% left_join(table)
  } else if ("BIOSAMPLE" %in% index_info) {
    biosample <- data$biosample %>%
      mutate(SAMPLE_COLLECTED_DATE = dmy(`DATE_SAMPLE_COLLECTED`)) %>%
      rename(index_date = SAMPLE_COLLECTED_DATE) %>%
      drop_na(index_date) %>%
      select(-c(DATA_SOURCE, DEIDENTIFIED_PATIENT_ID, VISIT_ENCOUNTER_ID)) %>%
      distinct()


    biosample_index <- biosample %>%
      distinct(DEIDENTIFIED_MASTER_PATIENT_ID, index_date)

    cohort <- biosample_index %>% left_join(table)
  } else if ("LATEST" %in% index_info) {
    latest <- extract_latest(data$encounter)



    cohort <- table %>% left_join(latest)
  } else {
    cohort <- index_info %>% left_join(table)
  }


  gc()

  # FIND MEDICATION AT INDEX DATE ----

  # if ("ENROLLMENT" %in% index_info) {
  #   cohort <- sparc_medication_enrollment(cohort, med)
  # } else {
    # MEDICATIONS AT OTHER INDEX DATES ----

    med_index <- med %>%
      left_join(cohort) %>%
      mutate(int = MED_START_DATE %--% MED_END_DATE) %>%
      rowwise() %>%
      mutate(ON_MED = case_when(
        index_date %within% int ~ 1,
        is.na(MED_END_DATE) & (index_date >= MED_START_DATE) ~ 1,
        TRUE ~ 0
      )) %>%
      ungroup() %>%
      distinct() %>%
      filter(ON_MED == 1) %>%
      group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, MOA) %>%
      slice(which.max(MED_START_DATE)) %>%
      pivot_wider(
        id_cols = c("DEIDENTIFIED_MASTER_PATIENT_ID", "index_date"),
        names_from = ON_MED,
        values_from = c(MEDICATION),
        values_fn = function(x) paste(x, collapse = "; ")
      ) %>%
      rename(MEDICATION_AT_INDEX = `1`)

    cohort <- cohort %>% left_join(med_index)


    med_dates <- med %>%
      left_join(cohort) %>%
      mutate(int = MED_START_DATE %--% MED_END_DATE) %>%
      rowwise() %>%
      mutate(ON_MED = case_when(
        index_date %within% int ~ 1,
        is.na(MED_END_DATE) & (index_date >= MED_START_DATE) ~ 1,
        TRUE ~ 0
      )) %>%
      ungroup() %>%
      distinct() %>%
      filter(ON_MED == 1) %>%
      group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, MOA) %>%
      slice(which.max(MED_START_DATE)) %>%
      pivot_wider(
        id_cols = c("DEIDENTIFIED_MASTER_PATIENT_ID", "index_date"),
        names_from = MEDICATION,
        values_from = c(MED_START_DATE_ECRF, MED_END_DATE_ECRF, MED_START_DATE_EMR, MED_END_DATE_EMR, CURRENT_MEDICATION_ECRF)
      ) %>%
      ungroup()


    cohort <- cohort %>% left_join(med_dates)


    # Bionaive at omics

    bionaive <- med %>%
      left_join(cohort) %>%
      mutate(int = MED_START_DATE %--% MED_END_DATE) %>%
      rowwise() %>%
      mutate(ON_MED = case_when(
        index_date %within% int ~ 1,
        is.na(MED_END_DATE_ECRF) & (index_date >= MED_START_DATE_ECRF) ~ 1,
        TRUE ~ 0
      )) %>%
      ungroup() %>%
      distinct() %>%
      filter(ON_MED == 1) %>%
      drop_na(BIONAIVE) %>%
      group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>%
      slice(which.min(BIONAIVE)) %>%
      distinct(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, BIONAIVE) %>%
      ungroup()

    cohort <- cohort %>% left_join(bionaive)

    # NO MEDICATION AT ENROLLMENT

    no_med <- med %>%
      distinct(DEIDENTIFIED_MASTER_PATIENT_ID, NO_CURRENT_IBD_MEDICATION_AT_ENROLLMENT)

    cohort <- cohort %>% left_join(no_med)
 # }

# On Steroid At Index ----

  steroid <- steroid_use_at_index(data, cohort)

  cohort <- cohort %>% left_join(steroid)






  # FOR OMICS & BIOSAMPLE ADD WHOLE TABLE IN


  if ("OMICS" %in% index_info) {
    cohort <- cohort %>% select(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, starts_with("MED"), intersect(names(.), names(steroid)))

    final_cohort <- omics %>%
      left_join(table) %>%
      left_join(cohort)
  } else if ("BIOSAMPLE" %in% index_info) {
    cohort <- cohort %>% select(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, starts_with("MED"), intersect(names(.), names(steroid)))

    final_cohort <- biosample %>%
      left_join(table) %>%
      left_join(cohort)
  } else {
    final_cohort <- cohort
  }


  # REORDER COLUMNS & FORMAT SPREADSHEET ----


  names(final_cohort) <- toupper(names(final_cohort))
  names(final_cohort) <- gsub(" ", "_", names(final_cohort))
  names(final_cohort) <- gsub("\\(|\\)", "", names(final_cohort))

  #assign col names into new tibble
  col_names <- tibble(x=final_cohort %>% names()) %>% filter(grepl("^MED_|^CURRENT_", x))

  #extract out into new columns name components
  col_names_order <- col_names %>%
    mutate(order = case_when(grepl("END", x) ~ 2,
                             grepl("START", x) ~ 1,
                             grepl("CURRENT", x) ~ 3)) %>%
    separate_wider_delim(x,delim = "_", too_few = "align_start", names_sep = "_",cols_remove = FALSE) %>%
    # mutate(before=str_extract(x,".*(?=_)"),
    #        after=str_extract(x,"_(?!.*_).*")
    # ) %>%
    arrange(x_5,x_6,match(x_4, c("ECRF","EMR")), match(x_2, c("START", "END"))) %>%
    pull(x_x)

  #rearrange colnames by this logic
  final_cohort <- final_cohort %>% select(DEIDENTIFIED_MASTER_PATIENT_ID:MEDICATION_AT_INDEX, any_of(col_names_order), everything())



  # CREATE HEADER STYLES----

  if (!is.null(filename)) {
    # orange
    style2 <- createStyle(bgFill = "#F8CBAD", textDecoration = "bold")


    # CREATE WORKBOOK ----

    wb <- createWorkbook()
    addWorksheet(wb, "med_at_index")
    writeData(wb, "med_at_index", x = final_cohort, startCol = 1, startRow = 1, colNames = TRUE, rowNames = FALSE)


    # FORMAT CELLS ----


    democoln <- max(which(colnames(final_cohort) %in% c("DIAGNOSIS")))

    rown <- dim(final_cohort)[1]
    coln <- dim(final_cohort)[2]

    conf <- max(which(colnames(final_cohort) %in% toupper("MEDICATION_AT_INDEX")))

    # column headers
    conditionalFormatting(wb, "med_at_index", cols = 1:democoln, rows = 1, rule = "!=0", style = style2)
    conditionalFormatting(wb, "med_at_index", cols = (democoln + 1):conf, rows = 1, rule = "!=0", style = style2)
    conditionalFormatting(wb, "med_at_index", cols = (conf + 1):coln, rows = 1, rule = "!=0", style = style2)



    # SAVE REPORT ----

    saveWorkbook(wb, file = paste0(filename), overwrite = TRUE)
  }
  return(final_cohort)
}
