
#' sparc_med_starts
#'
#' Extract medication first instance of medication start dates from SPARC patient reported and electronic medical record data.
#'
#'
#' @param medication A dataframe with generated by sparc_med_filter
#' @param encounter A dataframe with encounter data usually generated using load_data.
#'
#' @return A dataframe with the medication start date
#'
#' @details Medication start and stop dates are chosen independently from both
#'   eCRF and EMR sources. Medications with a start or stop date before 1980 are
#'   dropped. For EMR data, if a medication start date is missing, the visit
#'   encounter start date is used. These records are flagged in the column
#'   VISIT_ENCOUNTER_MED_START. If both data sources have information on a
#'   particular medication, the earliest start date is chosen. If the visit
#'   encounter start date is used for EMR and eCRF data is available, then the
#'   eCRF data source is used.
#'
sparc_med_starts <- function(medication, encounter) {


  # ECRF DATA ----

  # Find Start Date in eCRF Data ----

  start_ecrf <- medication %>%
    filter(DATA_SOURCE == "ECRF_SPARC" | DATA_SOURCE == "ECRF") %>%
    mutate(
      MED_START_DATE = if_else(year(MED_START_DATE) > 1980, MED_START_DATE, as.Date(NA, format = "%d-%m-%y")),
      MED_END_DATE = if_else(year(MED_END_DATE) > 1980, MED_END_DATE, as.Date(NA, format = "%d-%m-%y"))
    ) %>%
    drop_na(MED_START_DATE) %>%
    pivot_longer(cols = c(MED_START_DATE, MED_END_DATE), names_to = "type", values_to = "date") %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, new_med_name, DATA_SOURCE) %>%
    slice(which.min(date)) %>%
    pivot_wider(names_from = type, values_from = date) %>%
    ungroup() %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID,  new_med_name, MED_START_DATE) %>%
    rename(MEDICATION = new_med_name,
           MED_START_DATE_ECRF = MED_START_DATE)


  # EMR Data ----


  # Find Start Date in EMR Data ----

  start_emr <- medication %>%
    left_join(encounter, by = c("DEIDENTIFIED_MASTER_PATIENT_ID", "DEIDENTIFIED_PATIENT_ID", "DATA_SOURCE", "VISIT_ENCOUNTER_ID", "ADMISSION_TYPE", "SOURCE_OF_ADMISSION")) %>%
    mutate(VISIT_ENCOUNTER_MED_START = if_else(is.na(MED_START_DATE) & DATA_SOURCE == "EMR", 1, 0),
           MED_START_DATE = if_else(is.na(MED_START_DATE) & DATA_SOURCE == "EMR", (VISIT_ENCOUNTER_START_DATE), MED_START_DATE)) %>%
    filter(DATA_SOURCE == "EMR") %>%
      mutate(drop = case_when(
      (!is.na(MED_END_DATE) & !is.na(MED_START_DATE)) & MED_END_DATE < MED_START_DATE ~ 1,
      TRUE ~ 0
    )) %>%
    filter(drop == 0) %>%
    mutate(
      MED_START_DATE = if_else(year(MED_START_DATE) > 1980, MED_START_DATE, as.Date(NA, format = "%d-%m-%y")),
      MED_END_DATE = if_else(year(MED_END_DATE) > 1980, MED_END_DATE, as.Date(NA, format = "%d-%m-%y"))
    ) %>%
    pivot_longer(cols = c(MED_START_DATE, MED_END_DATE), names_to = "type", values_to = "date") %>%
    drop_na(date) %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, new_med_name, DATA_SOURCE, match(type, c("MED_START_DATE", "MED_END_DATE")), date) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, new_med_name, DATA_SOURCE) %>%
    slice(which.min(date)) %>%
    pivot_wider(names_from = type, values_from = date) %>%
    ungroup() %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID,  new_med_name, MED_START_DATE,VISIT_ENCOUNTER_MED_START) %>%
    rename(MEDICATION = new_med_name,
           MED_START_DATE_EMR = MED_START_DATE)

  # Combine eCRF and EMR data ----

  # Pick earlierst start date - if visit encounter start date used for EMR then use eCRF start date

  med_start <- full_join(start_ecrf, start_emr, by = c("DEIDENTIFIED_MASTER_PATIENT_ID", "MEDICATION")) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, MEDICATION, VISIT_ENCOUNTER_MED_START, MED_START_DATE_EMR, MED_START_DATE_ECRF) %>%
    rowwise() %>%
    mutate(MED_START_DATE = case_when((VISIT_ENCOUNTER_MED_START == 0 | is.na(VISIT_ENCOUNTER_MED_START)) ~ min(c_across(MED_START_DATE_EMR:MED_START_DATE_ECRF), na.rm = T),
                                      VISIT_ENCOUNTER_MED_START == 1 & !is.na(MED_START_DATE_ECRF) ~ MED_START_DATE_ECRF,
                                      VISIT_ENCOUNTER_MED_START == 1 & is.na(MED_START_DATE_ECRF) ~ MED_START_DATE_EMR)) %>%
    ungroup()



  return(med_start)
}
