#' sparc_biosample_flags
#'
#' Flags SPARC biosamples based on date sample collected as either enrollment,
#' endoscopy, endoscopy and enrollment, 3 months after endoscopy, 3 months after
#' med change.
#'
#' @param data A list of dataframes, typically generated by a call to load_data.
#'   Must include demographics, diagnosis, encounter, procedures, observations,
#'   biosample, omics_patient_mapping, prescriptions and labs.
#' @param index_range the number of days to look out from index date.
#'
#' @return A dataframe with the summary data and an excel file.
#'
#'


sparc_biosample_flags <- function(data, index_range) {

  r <- as.numeric(index_range)

  encounter <- data$encounter
  biosample <- data$biosample
  procedures <- data$procedures
  demographics <- data$demographics
  prescriptions <- data$prescriptions

  sparc_meds <- sparc_med_journey(prescriptions, demographics, dat$observations, encounter)

  # rm(dat)

  gc()

  # get all biosamples with same code from summary table
  biosample2 <- biosample %>%
    mutate(SAMPLE_COLLECTED_DATE = dmy(`DATE_SAMPLE_COLLECTED`)) %>%
    rename(index_date = SAMPLE_COLLECTED_DATE) %>%
    drop_na(index_date) %>%
    select(-c(DATA_SOURCE, DEIDENTIFIED_PATIENT_ID, VISIT_ENCOUNTER_ID)) %>%
    distinct()

  biosample_n <- biosample2 %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, BIOSAMPLE_CONCEPT_NAME) %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, BIOSAMPLE_CONCEPT_NAME) %>%
    mutate(SAMPLE_NUMBER = seq_along(DEIDENTIFIED_MASTER_PATIENT_ID)) %>%
    ungroup()

  biosample1 <- biosample2 %>%
    left_join(biosample_n, by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID, BIOSAMPLE_CONCEPT_NAME, index_date))

  # get endoscopies
  endoscopy <- ibdplexus:::extract_endoscopy(procedures) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    mutate(ENDO_INT = interval(index_date - r, index_date + r)) %>%
    mutate(DAYS90_INT = interval(index_date + (90 - r), index_date + (90 + r))) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, ENDO_INT, DAYS90_INT) %>%
    distinct()

  # get enrollment days
  enrollment <- demographics %>%
    filter(!is.na(DATE_OF_CONSENT)) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, DATE_OF_CONSENT) %>%
    mutate(DATE_OF_CONSENT = dmy(DATE_OF_CONSENT)) %>%
    mutate(ENR_INT = interval(DATE_OF_CONSENT - r, DATE_OF_CONSENT + r)) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, ENR_INT) %>%
    distinct() %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>%
    mutate(num = row_number()) %>%
    pivot_wider(names_from = num, names_prefix ="ENROLL_INT_", values_from = ENR_INT) %>%
    ungroup() %>%
    distinct()

  all_int <- endoscopy %>%
    full_join(enrollment, by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID))

  # joined

  joined <- biosample1 %>%
    left_join(all_int, by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID), relationship = "many-to-many") %>%
    mutate(SAMPLE_DATE_COLLECTED = dmy(DATE_SAMPLE_COLLECTED)) %>%
    mutate(ENROLLMENT = if_else(SAMPLE_DATE_COLLECTED %within% ENROLL_INT_1, 1, 0),
           ENROLLMENT = if_else(SAMPLE_DATE_COLLECTED %within% ENROLL_INT_2, 1, ENROLLMENT)) %>%
    mutate(ENDOSCOPY = if_else(SAMPLE_DATE_COLLECTED %within% ENDO_INT, 1, 0)) %>%
    mutate(`3 MONTHS POST ENDOSCOPY` = if_else(SAMPLE_DATE_COLLECTED %within% DAYS90_INT, 1, 0)) %>%
    mutate(ENROLLMENT = ifelse(is.na(ENROLLMENT), 0 , ENROLLMENT),
           ENDOSCOPY = ifelse(is.na(ENDOSCOPY), 0, ENDOSCOPY),
           `3 MONTHS POST ENDOSCOPY` = ifelse(is.na(`3 MONTHS POST ENDOSCOPY`), 0 , `3 MONTHS POST ENDOSCOPY`)) %>%
    mutate(flag = ifelse(ENROLLMENT == 1 | ENDOSCOPY == 1 | `3 MONTHS POST ENDOSCOPY` == 1, 1, 0)) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, BIOSAMPLE_CONCEPT_NAME, SRC_BIOSAMPLE_CONCEPT_NAME,
             SAMPLE_STATUS, DATE_SAMPLE_COLLECTED, SAMPLE_DATE_COLLECTED, BIOSAMPLE_LOCATION, MACROSCOPIC_APPEARANCE,
             SUB_LOCATION__C, VISIT_TYPE__C, index_date, SAMPLE_NUMBER) %>%
    arrange(desc(flag)) %>%
    mutate(num = row_number()) %>%
    filter(num == 1) %>%
    select(-num) %>%
    select(-flag) %>%
    select(-ends_with("_INT")) %>%
    select(-c(ENROLL_INT_1, ENROLL_INT_2)) %>%
    mutate(ENDOSCOPY_AT_ENROLLMENT = ifelse(ENROLLMENT == 1 & ENDOSCOPY == 1, 1, 0)) %>%
    ungroup()

  # get medication start dates to find biosamples ~90 days after start
  sparc_meds <- sparc_meds  %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, MEDICATION, MED_START_DATE)

  # create flag for biosample days that fit med change criteria
  med_change <- sparc_meds %>%
    left_join(biosample1 %>%
                select(DEIDENTIFIED_MASTER_PATIENT_ID, DATE_SAMPLE_COLLECTED) %>%
                mutate(SAMPLE_DATE_COLLECTED = dmy(DATE_SAMPLE_COLLECTED)),
              by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID), relationship = "many-to-many") %>%
    mutate(days_between = MED_START_DATE - SAMPLE_DATE_COLLECTED) %>%
    filter(days_between <= (90 + r) & days_between >= (90 - r)) %>%
    mutate(`3 MONTHS POST MED CHANGE` = 1) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, DATE_SAMPLE_COLLECTED, `3 MONTHS POST MED CHANGE`) %>%
    distinct()

  # join all final flags
  joined_final <- joined %>%
    left_join(med_change, by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID, DATE_SAMPLE_COLLECTED)) %>%
    mutate(`3 MONTHS POST MED CHANGE` = ifelse(is.na(`3 MONTHS POST MED CHANGE`), 0, `3 MONTHS POST MED CHANGE`)) %>%
    mutate(OTHER = ifelse(ENROLLMENT == 0 & ENDOSCOPY == 0 & `3 MONTHS POST ENDOSCOPY` == 0 &
                            `3 MONTHS POST MED CHANGE` == 0, 1, 0)) %>%
    select(-c(index_date, SAMPLE_DATE_COLLECTED))

  return(joined_final)

}
