#' sparc_scores
#'
#' Summarize the disease severity and endoscopy scores closest to a specific index date within a specific range of time.
#'
#' @param data A list of dataframes, typically generated by a call to load_data. Must include demographics, diagnosis, encounter, procedures, and observations. Only CRF data needs to be uploaded.
#' @param index_info A dataframe  with DEIDENTIFIED_MASTER_PATIENT_ID and a variable index_date.  Other options include, enrollment, latest, endoscopy, omics, biosample collection.
#' @param filename the name of the output file. Must be .xlsx.
#' @param index_range the number of days to look out from index date. If multiple of the same score fall within this range then the one closest to the index date is picked. Default is 30 days.
#' @param location_logic specify which CD location function to use. If using logic developed by AZ then use location_logic = "AZ".
#'
#' @return A dataframe with scores at that date and an excel spreadsheet.
#'
#' @details If multiple of the same score type are reported on the same date from the same data source, the more severe score is taken. If multiple scores are reported from two different sources, the Smartform data source is preferred over the eCRF data source.
#'
#' If endoscopy, omics or biosample collection date are chosen as index date then endoscopy, omics_patient_mapping or biosample tables must be in the data parameter.
#'
#' @export
sparc_scores <- function(data,
                         index_info = c("ENROLLMENT", "LATEST", "ENDOSCOPY", "OMICS", "BIOSAMPLE"),
                         filename = "SPARC_SCORES.xlsx",
                         index_range = "30",
                         location_logic = "CCF") {
  if ("character" %in% class(index_info)) {
    index_info <- toupper(index_info)
  } else {
    index_info <- index_info
  }


  # CONSENT INFORMATION ----

  consent <- extract_consent(data$demographics, "SPARC")


  # DEMOGRAPHIC INFORMATION ----

  demo <- extract_demo(data$demographics, "SPARC")


  #  DIAGNOSIS & DIAGNOSIS_DATE ----


  dx <- extract_diagnosis(data$diagnosis, data$encounter, data$demographics, "SPARC")



  # CREATE TABLE ----

  table <- consent %>%
    left_join(demo, by = "DEIDENTIFIED_MASTER_PATIENT_ID") %>%
    left_join(dx, by = "DEIDENTIFIED_MASTER_PATIENT_ID")


  # CONVERT DAYS AFTER INDEX  TO NUMERIC VALUE ----

  t <- as.numeric(index_range)

  # CREATE INDEX_DATE ----

  if ("ENROLLMENT" %in% index_info) {
    cohort <- table %>% mutate(index_date = DATE_OF_CONSENT)
  } else if ("ENDOSCOPY" %in% index_info) {
    endoscopy <- extract_endoscopy(data$procedures)

    cohort <- endoscopy %>% left_join(table)
  } else if ("OMICS" %in% index_info) {
    omics <- data$omics_patient_mapping %>%
      mutate(SAMPLE_COLLECTED_DATE = dmy(SAMPLE_COLLECTED_DATE)) %>%
      mutate(index_date = SAMPLE_COLLECTED_DATE) %>%
      drop_na(index_date) %>%
      select(-c(DATA_SOURCE, DEIDENTIFIED_PATIENT_ID, VISIT_ENCOUNTER_ID)) %>%
      distinct()

    omics_index <- omics %>%
      distinct(DEIDENTIFIED_MASTER_PATIENT_ID, index_date)

    cohort <- omics_index %>% left_join(table)
  } else if ("BIOSAMPLE" %in% index_info) {
    biosample <- data$biosample %>%
      mutate(SAMPLE_COLLECTED_DATE = dmy(`DATE_SAMPLE_COLLECTED`)) %>%
      rename(index_date = SAMPLE_COLLECTED_DATE) %>%
      drop_na(index_date) %>%
      select(-c(DATA_SOURCE, DEIDENTIFIED_PATIENT_ID, VISIT_ENCOUNTER_ID)) %>%
      distinct()


    biosample_index <- biosample %>%
      distinct(DEIDENTIFIED_MASTER_PATIENT_ID, index_date)

    cohort <- biosample %>% left_join(table)
  } else if ("LATEST" %in% index_info) {
    latest <- extract_latest(data$encounter)



    cohort <- table %>% left_join(latest)
  } else {
    cohort <- index_info %>% left_join(table)
  }


  gc()


  # PHENOTYPES: ----
  #  Crohn's Disease - just closest no date constraint if multiple before index date then keep worst one - don't make a call


  cdp <- data$observations %>%
    filter(DATA_SOURCE == "SF_SPARC") %>%
    filter(OBS_TEST_CONCEPT_NAME %in% c("Crohn's Disease Phenotype", "IBD Manifestations - Abdominal Abscess, Fistula, or Other Penetrating Complication") | str_detect(OBS_TEST_CONCEPT_NAME, "^Phenotype")) %>%
    drop_na(DESCRIPTIVE_SYMP_TEST_RESULTS) %>%
    right_join(cohort) %>%
    filter(DIAGNOSIS == "Crohn's Disease") %>%
    mutate(diff = OBS_TEST_RESULT_DATE - index_date) %>%
    mutate(keep = case_when(
      DESCRIPTIVE_SYMP_TEST_RESULTS == "Inflammatory, non-penetrating, non-stricturing" & diff > t ~ "keep",
      diff <= t ~ "keep"
    )) %>%
    filter(keep == "keep") %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, OBS_TEST_CONCEPT_NAME, index_date) %>%
    slice(which.min(abs(diff))) %>%
    ungroup() %>%
    pivot_wider(id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID, index_date), names_from = OBS_TEST_CONCEPT_NAME, values_from = DESCRIPTIVE_SYMP_TEST_RESULTS) %>%
    mutate(`Crohn's Disease Phenotype` = case_when(
      `Crohn's Disease Phenotype` == "Inflammatory, non-penetrating, non-stricturing" ~ "Inflammatory non-penetrating, non-stricturing (B1)",
      `Crohn's Disease Phenotype` == "Stricturing" ~ "Stricturing (B2)",
      `Crohn's Disease Phenotype` == "Penetrating" ~ "Penetrating (B3)",
      `Crohn's Disease Phenotype` == "Both stricturing and penetrating" ~ "Both stricturing and penetrating (B2B3)",
      TRUE ~ `Crohn's Disease Phenotype`
    ))



  cohort <- cohort %>%
    left_join(cdp)



  # PHENOTYPES:
  #  Ulcerative Colitis- just closest no date constraint if multiple before index date then keep worst one

  ucp <- data$observations %>%
    filter(DATA_SOURCE == "SF_SPARC") %>%
    filter(OBS_TEST_CONCEPT_NAME %in% "Extent of Macroscopic Ulcerative Colitis" & (!is.na(DESCRIPTIVE_SYMP_TEST_RESULTS))) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, OBS_TEST_CONCEPT_NAME, DESCRIPTIVE_SYMP_TEST_RESULTS, OBS_TEST_CONCEPT_CODE, OBS_TEST_RESULT_DATE) %>%
    right_join(cohort) %>%
    filter(DIAGNOSIS == "Ulcerative Colitis") %>%
    mutate(diff = (OBS_TEST_RESULT_DATE) - index_date) %>%
    mutate(keep = case_when(
      DESCRIPTIVE_SYMP_TEST_RESULTS == "Ulcerative proctitis (rectum only)" & diff > t ~ "keep",
      diff <= t ~ "keep"
    )) %>%
    filter(keep == "keep") %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, match(DESCRIPTIVE_SYMP_TEST_RESULTS, c(
      "Pancolitis",
      "Extensive ulcerative colitis (extends proximal to the splenic flexure)",
      "Left-sided ulcerative colitis (distal to the splenic flexure only)",
      "Ulcerative proctitis (rectum only)",
      "Unknown"
    ))) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    slice(which.min(abs(diff))) %>%
    ungroup() %>%
    pivot_wider(id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID, index_date), names_from = OBS_TEST_CONCEPT_NAME, values_from = DESCRIPTIVE_SYMP_TEST_RESULTS) %>%
    mutate(`Extent of Macroscopic Ulcerative Colitis` = case_when(
      `Extent of Macroscopic Ulcerative Colitis` == "Ulcerative proctitis (rectum only)" ~ "Ulcerative proctitis (rectum only) (E1)",
      `Extent of Macroscopic Ulcerative Colitis` == "Left-sided ulcerative colitis (distal to the splenic flexure only)" ~ "Left-sided ulcerative colitis (distal to the splenic flexure only) (E2)",
      `Extent of Macroscopic Ulcerative Colitis` == "Extensive ulcerative colitis (extends proximal to the splenic flexure)" ~ "Extensive ulcerative colitis (extends proximal to the splenic flexure) (E3)",
      `Extent of Macroscopic Ulcerative Colitis` == "Pancolitis" ~ "Pancolitis (E4)",
      TRUE ~ `Extent of Macroscopic Ulcerative Colitis`
    ))


  cohort <- left_join(cohort, ucp)



  # PHENOTYPES:
  #  IBD-U- just closest no date constraint if multiple before index date then keep worst one


  ibdu <- data$observations %>%
    filter(DATA_SOURCE == "SF_SPARC") %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>%
    filter(OBS_TEST_CONCEPT_CODE %in% c("EPIC#31000125051", "EPIC#31000125052", "EPIC#31000125053", "EPIC#31000125054", "EPIC#31000125055", "SMART_Q61__C") & (!is.na(DESCRIPTIVE_SYMP_TEST_RESULTS))) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, OBS_TEST_CONCEPT_NAME, DESCRIPTIVE_SYMP_TEST_RESULTS, OBS_TEST_CONCEPT_CODE, OBS_TEST_RESULT_DATE) %>%
    right_join(cohort) %>%
    filter(DIAGNOSIS == "IBD Unclassified") %>%
    mutate(diff = (OBS_TEST_RESULT_DATE) - index_date) %>%
    mutate(keep = case_when(
      DESCRIPTIVE_SYMP_TEST_RESULTS == "Ulcerative proctitis (rectum only)" & diff > t ~ "keep",
      diff <= t ~ "keep"
    )) %>%
    filter(keep == "keep") %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    slice(which.min(abs(diff))) %>%
    pivot_wider(id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID, index_date), names_from = OBS_TEST_CONCEPT_NAME, values_from = DESCRIPTIVE_SYMP_TEST_RESULTS)


  cohort <- cohort %>%
    left_join(ibdu)

  # DISEASE LOCATION - at index date ----


  if ("AZ" %in% location_logic) {
    location <- calculate_location_az(data$observations, data$encounter, window = t) %>%
      left_join(cohort) %>%
      filter(DIAGNOSIS == "Crohn's Disease") %>%
      mutate(diff = abs((VISIT_ENCOUNTER_START_DATE) - index_date)) %>%
      group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
      slice(which.min(diff)) %>%
      ungroup() %>%
      select(
        DEIDENTIFIED_MASTER_PATIENT_ID, `Ileal Phenotype`, `Transverse Colonic Phenotype`, `Rectal Phenotype`, `Jejunal Phenotype`, `Esophageal Phenotype`,
        `Left Colonic Phenotype`, `Gastric Phenotype`, `Anal Phenotype`, `Right Colonic Phenotype`,
        `Duodenal Phenotype`, `Colonic involvement`, `Upper GI`, `CD Location`
      )

    cohort <- cohort %>% left_join(location)
  } else {
    location <- data$observations %>%
      filter(DATA_SOURCE == "SF_SPARC") %>%
      filter(OBS_TEST_CONCEPT_NAME %in% c("Anal Phenotype", "Duodenal Phenotype", "Esophageal Phenotype", "Gastric Phenotype", "Ileal Phenotype", "Jejunal Phenotype", "Left Colonic Phenotype", "Rectal Phenotype", "Right Colonic Phenotype", "Transverse Colonic Phenotype")) %>%
      drop_na(DESCRIPTIVE_SYMP_TEST_RESULTS) %>%
      group_by(DEIDENTIFIED_MASTER_PATIENT_ID, OBS_TEST_CONCEPT_NAME) %>%
      arrange(OBS_TEST_RESULT_DATE, .by_group = TRUE) %>%
      mutate(result = case_when(OBS_TEST_RESULT_DATE > lag(OBS_TEST_RESULT_DATE) & DESCRIPTIVE_SYMP_TEST_RESULTS == "No" & lag(DESCRIPTIVE_SYMP_TEST_RESULTS) == "Yes" & OBS_TEST_CONCEPT_NAME == lag(OBS_TEST_CONCEPT_NAME) ~ "Yes", TRUE ~ DESCRIPTIVE_SYMP_TEST_RESULTS)) %>%
      ungroup() %>%
      right_join(cohort) %>%
      filter(DIAGNOSIS == "Crohn's Disease") %>%
      mutate(diff = OBS_TEST_RESULT_DATE - index_date) %>%
      mutate(keep = case_when(
        diff <= t ~ "keep",
        result == "No" & diff > t ~ "keep",
      )) %>%
      filter(keep == "keep") %>%
      group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, OBS_TEST_CONCEPT_NAME) %>%
      slice(which.min(abs(diff))) %>%
      ungroup() %>%
      distinct(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, OBS_TEST_CONCEPT_NAME, result) %>%
      pivot_wider(id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID, index_date), names_from = OBS_TEST_CONCEPT_NAME, values_from = result) %>%
      ungroup()



    cohort <- left_join(cohort, location)



    # PERIANAL INVOLVEMENT ----

    perianal <- data$observations %>%
      filter(DATA_SOURCE == "SF_SPARC") %>%
      filter(OBS_TEST_CONCEPT_NAME %in% c(
        "Perianal Abcess",
        "Perianal Fistula",
        "Perianal Fistula - Complex Fistula",
        "Rectovaginal Fistula",
        "Anal Canal Ulcer",
        "Anal Canal Stricture",
        "Anal Fissure",
        "Large Skin Tags"
      )) %>%
      group_by(DEIDENTIFIED_MASTER_PATIENT_ID, OBS_TEST_CONCEPT_NAME) %>%
      drop_na(DESCRIPTIVE_SYMP_TEST_RESULTS) %>%
      arrange(OBS_TEST_RESULT_DATE, .by_group = TRUE) %>%
      mutate(result = case_when(OBS_TEST_RESULT_DATE > lag(OBS_TEST_RESULT_DATE) & DESCRIPTIVE_SYMP_TEST_RESULTS == "No" & lag(DESCRIPTIVE_SYMP_TEST_RESULTS) == "Yes" & OBS_TEST_CONCEPT_NAME == lag(OBS_TEST_CONCEPT_NAME) ~ "Yes", TRUE ~ DESCRIPTIVE_SYMP_TEST_RESULTS)) %>%
      ungroup() %>%
      right_join(cohort) %>%
      filter(DIAGNOSIS == "Crohn's Disease") %>%
      mutate(diff = OBS_TEST_RESULT_DATE - index_date) %>%
      mutate(keep = case_when(
        diff <= t ~ "keep",
        result == "No" & diff > t ~ "keep"
      )) %>%
      filter(keep == "keep") %>%
      group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, OBS_TEST_CONCEPT_NAME) %>%
      slice(which.min(abs(diff))) %>%
      ungroup() %>%
      distinct(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, OBS_TEST_CONCEPT_NAME, result) %>%
      pivot_wider(id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID, index_date), names_from = OBS_TEST_CONCEPT_NAME, values_from = result) %>%
      ungroup()


    cohort <- left_join(cohort, perianal)



    #  CALCULATE DISEASE LOCATION ----

    disease_location <- cohort %>%
      setNames(toupper(names(.))) %>%
      filter(DIAGNOSIS == "Crohn's Disease") %>%
      mutate(
        ileal = ifelse(`ILEAL PHENOTYPE` == "Yes", 1, 0),
        colonic = ifelse(`LEFT COLONIC PHENOTYPE` == "Yes" | `RECTAL PHENOTYPE` == "Yes" |
                           `RIGHT COLONIC PHENOTYPE` == "Yes" | `TRANSVERSE COLONIC PHENOTYPE` == "Yes", 1, 0),
        ilealcolonic = ifelse(ileal == 1 & colonic == 1, 1, 0)
      ) %>%
      mutate(
        Location = case_when(
          `ILEAL PHENOTYPE` == "Yes" &
            `LEFT COLONIC PHENOTYPE` == "No" & `RECTAL PHENOTYPE` == "No" &
            `RIGHT COLONIC PHENOTYPE` == "No" & `TRANSVERSE COLONIC PHENOTYPE` == "No" ~ "Ileal",
          `ILEAL PHENOTYPE` == "No" &
            (`LEFT COLONIC PHENOTYPE` == "Yes" | `RECTAL PHENOTYPE` == "Yes" |
               `RIGHT COLONIC PHENOTYPE` == "Yes" | `TRANSVERSE COLONIC PHENOTYPE` == "Yes") ~ "Colonic",
          `ILEAL PHENOTYPE` == "Yes" &
            (`LEFT COLONIC PHENOTYPE` == "Yes" | `RECTAL PHENOTYPE` == "Yes" |
               `RIGHT COLONIC PHENOTYPE` == "Yes" | `TRANSVERSE COLONIC PHENOTYPE` == "Yes") ~ "Ileocolonic",
          `ILEAL PHENOTYPE` == "Unknown" &
            `LEFT COLONIC PHENOTYPE` == "Unknown" & `RECTAL PHENOTYPE` == "Unknown" &
            `RIGHT COLONIC PHENOTYPE` == "Unknown" & `TRANSVERSE COLONIC PHENOTYPE` == "Unknown" ~ "Unknown"
        ),
        UpperGI = case_when(
          `DUODENAL PHENOTYPE` == "Yes" | `ESOPHAGEAL PHENOTYPE` == "Yes" | `GASTRIC PHENOTYPE` == "Yes" | `JEJUNAL PHENOTYPE` == "Yes" ~ "Yes",
          `DUODENAL PHENOTYPE` == "Unknown" & `ESOPHAGEAL PHENOTYPE` == "Unknown" & `GASTRIC PHENOTYPE` == "Unknown" & `JEJUNAL PHENOTYPE` == "Unknown" ~ "Unknown",
          `DUODENAL PHENOTYPE` == "No" & `ESOPHAGEAL PHENOTYPE` == "No" & `GASTRIC PHENOTYPE` == "No" & `JEJUNAL PHENOTYPE` == "No" ~ "No"
        ),
        Perianal = case_when(
          `PHENOTYPE - ANAL STRICTURE` == "Yes" |
            `ANAL PHENOTYPE` == "Yes" |
            `ANAL CANAL STRICTURE` == "Yes" |
            `ANAL CANAL ULCER` == "Yes" |
            `ANAL FISSURE` == "Yes" |
            `PERIANAL ABCESS` == "Yes" |
            `PERIANAL FISTULA - COMPLEX FISTULA` == "Yes" |
            `PERIANAL FISTULA` == "Yes" |
            `LARGE SKIN TAGS` == "Yes" |
            `RECTOVAGINAL FISTULA` == "Yes" ~ "Yes",
          (`PHENOTYPE - ANAL STRICTURE` == "No" &
             `ANAL PHENOTYPE` == "No" &
             `ANAL CANAL STRICTURE` == "No" &
             `ANAL CANAL ULCER` == "No" &
             `ANAL FISSURE` == "No" &
             `PERIANAL ABCESS` == "No" &
             `PERIANAL FISTULA - COMPLEX FISTULA` == "No" &
             `LARGE SKIN TAGS` == "No" &
             `RECTOVAGINAL FISTULA` == "No") &
            `PERIANAL FISTULA` == "No" ~ "No",
          TRUE ~ "Unknown"
        ),
        PHENOTYPE_Data = "Yes"
      ) %>%
      mutate(Location = case_when(
        is.na(Location) & ilealcolonic == 1 ~ "Ileocolonic",
        is.na(Location) & (is.na(ilealcolonic) | ilealcolonic == 0) & ileal == 1 ~ "Ileal",
        is.na(Location) & (is.na(ilealcolonic) | ilealcolonic == 0) & colonic == 1 ~ "Colonic",
        TRUE ~ Location
      )) %>%
      select(DEIDENTIFIED_MASTER_PATIENT_ID, INDEX_DATE, Location, UpperGI, Perianal) %>%
      dplyr::rename(DISEASE_LOCATION = Location, UPPERGI = UpperGI, PERIANAL = Perianal, index_date = INDEX_DATE)

    cohort <- left_join(cohort, disease_location)

  }


  # Calculate disease activity scores +/- t days of index ----


  # SCORES ----

  # scdai
  scdai <- calculate_scdai(data$observations) %>%
    left_join(cohort) %>%
    mutate(datediff = abs(SCDAI_DATE - index_date)) %>%
    filter(DIAGNOSIS == "Crohn's Disease" & datediff <= t) %>%
    drop_na(SCDAI_SCORE) %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, desc(SCDAI_SOURCE), desc(SCDAI_SCORE)) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    filter(datediff == min(abs(datediff))) %>%
    slice(1) %>%
    distinct() %>%
    ungroup() %>%
    select(-datediff) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, intersect(names(.), names(calculate_scdai(data$observations))))



  cohort <- cohort %>% left_join(scdai)


  # pro2
  pro2 <- calculate_pro2(data$observations) %>%
    left_join(cohort) %>%
    mutate(datediff = abs(PRO2_DATE - index_date)) %>%
    filter(DIAGNOSIS == "Crohn's Disease" & datediff <= t) %>%
    drop_na(PRO2_SCORE) %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, desc(PRO2_SOURCE), desc(PRO2_SCORE)) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    filter(datediff == min(abs(datediff))) %>%
    slice(1) %>%
    distinct() %>%
    ungroup() %>%
    select(-datediff) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, intersect(names(.), names(calculate_pro2(data$observations))))


  cohort <- cohort %>% left_join(pro2)

  # pr03

  pro3 <- calculate_pro3(data$observations) %>%
    left_join(cohort) %>%
    mutate(datediff = abs(PRO3_DATE - index_date)) %>%
    filter(DIAGNOSIS == "Crohn's Disease" & datediff <= t) %>%
    drop_na(PRO3_SCORE) %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, desc(PRO3_SOURCE), desc(PRO3_SCORE)) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    filter(datediff == min(abs(datediff))) %>%
    slice(1) %>%
    distinct() %>%
    ungroup() %>%
    select(-datediff) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, intersect(names(.), names(calculate_pro3(data$observations)))) %>%
    select(-LIQUID_BM)


  cohort <- cohort %>% left_join(pro3)


  # 6pt mayo

  mayo <- calculate_mayo(data$observations) %>%
    left_join(cohort) %>%
    mutate(datediff = abs(MAYO_DATE - index_date)) %>%
    filter(DIAGNOSIS == "Ulcerative Colitis" & datediff <= t) %>%
    drop_na(MAYO_6_SCORE) %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, desc(MAYO_SOURCE), desc(MAYO_6_SCORE)) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    filter(datediff == min(abs(datediff))) %>%
    slice(1) %>%
    distinct() %>%
    ungroup() %>%
    select(-datediff) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, intersect(names(.), names(calculate_mayo(data$observations))))


  cohort <- cohort %>% left_join(mayo)

  # pga



  pga <- calculate_pga(data$observations) %>%
    left_join(cohort) %>%
    mutate(datediff = abs(PGA_DATE - index_date)) %>%
    filter(datediff <= t) %>%
    drop_na(PGA) %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, desc(PGA_SOURCE), desc(PGA)) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    filter(datediff == min(abs(datediff))) %>%
    slice(1) %>%
    distinct() %>%
    ungroup() %>%
    select(-datediff)  %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, intersect(names(.), names(calculate_pga(data$observations))))


  cohort <- cohort %>% left_join(pga)


  # ENDOSCOPY SCORES WITHIN t of INDEX DATE ----

  # SES CD


  ses <- calculate_ses(data$procedures) %>%
    left_join(cohort) %>%
    mutate(datediff = abs(SCORE_DATE - index_date)) %>%
    filter(DIAGNOSIS == "Crohn's Disease" & datediff <= t) %>%
    drop_na(SES_SCORE) %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, desc(SES_SCORE)) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    filter(datediff == min(abs(datediff))) %>%
    slice(1) %>%
    distinct() %>%
    ungroup() %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, intersect(names(.), names(calculate_ses(data$procedures)))) %>%
    rename(
      ENDO_DATE = SCORE_DATE,
      ENDO_CATEGORY = SES_CATEGORY
    )





  # Mayo Endocscopy Score - source: https://academic.oup.com/ecco-jcc/article/9/10/846/425061

  mes <- calculate_mes(data$procedures) %>%
    left_join(cohort) %>%
    mutate(datediff = abs(SCORE_DATE - index_date)) %>%
    filter(DIAGNOSIS == "Ulcerative Colitis" & datediff <= t) %>%
    drop_na(MAYO_ENDOSCOPY_SCORE) %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, desc(MAYO_ENDOSCOPY_SCORE)) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    filter(datediff == min(abs(datediff))) %>%
    slice(1) %>%
    distinct() %>%
    ungroup() %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, intersect(names(.), names(calculate_mes(data$procedures)))) %>%
    rename(
      ENDO_DATE = SCORE_DATE,
      ENDO_CATEGORY = MES_CATGORY
    )

  es <- bind_rows(ses, mes) %>%
    distinct() %>%
    mutate(ENDOSCOPY = 1) %>%
    rename(!!paste("ENDOSCOPY", t, sep = "_") := ENDOSCOPY)

  cohort <- left_join(cohort, es)




  # Ostomy ----

  ostomy_sf <- data$procedures %>%
    filter(DATA_SOURCE %in% c("SF_SPARC")) %>%
    filter(PROC_CONCEPT_NAME == "Ileostomy/Colostomy") %>%
    mutate(ostomy = PROC_STATUS_CONCEPT_NAME) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, ostomy, VISIT_ENCOUNTER_ID) %>%
    left_join(data$encounter) %>%
    left_join(cohort) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    mutate(diff = (VISIT_ENCOUNTER_START_DATE) - index_date) %>%
    slice(which.min(abs(diff))) %>%
    ungroup() %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, ostomy, index_date, diff)

  ostomy_ecrf <- data$observations %>%
    filter(DATA_SOURCE == "ECRF_SPARC") %>%
    filter(OBS_TEST_CONCEPT_NAME %in% c(
      "Baseline Number of Daily Bowel Movements",
      "Current Average Number of Daily Bowel Movements",
      "Recent Change in Daily Stool Frequency",
      "Current Average Number of Daily Liquid Bowel Movements"
    )) %>%
    filter(DESCRIPTIVE_SYMP_TEST_RESULTS == "Not applicable, I have an ostomy") %>%
    mutate(ostomy = DESCRIPTIVE_SYMP_TEST_RESULTS) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, ostomy, VISIT_ENCOUNTER_ID) %>%
    left_join(data$encounter) %>%
    left_join(cohort) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    mutate(diff = (VISIT_ENCOUNTER_START_DATE) - index_date) %>%
    drop_na(ostomy) %>%
    slice(which.min(abs(diff))) %>%
    ungroup() %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, ostomy, index_date, diff)

  ostomy <- bind_rows(ostomy_sf, ostomy_ecrf) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    slice(which.min(abs(diff))) %>%
    ungroup() %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, ostomy)

  cohort <- cohort %>%
    left_join(ostomy) %>%
    mutate(ostomy = case_when(
      DIAGNOSIS == "Crohn's Disease" & is.na(SCDAI_CATEGORY) ~ ostomy,
      DIAGNOSIS == "Ulcerative Colitis" & is.na(MAYO6_CATEGORY) ~ ostomy,
      TRUE ~ as.character(NA)
    ))

  # CALCULATE DISEASE ACTIVITY  ----


  cohort <- cohort %>%
    mutate(DISEASE_ACTIVITY = case_when(
      DIAGNOSIS == "Crohn's Disease" ~ SCDAI_CATEGORY,
      DIAGNOSIS == "Ulcerative Colitis" ~ MAYO6_CATEGORY,
      TRUE ~ as.character(NA)
    )) %>%
    mutate(DISEASE_ACTIVITY = case_when(
      is.na(DISEASE_ACTIVITY) & PGA == "Quiescent" ~ "Remission",
      is.na(DISEASE_ACTIVITY) & PGA != "Quiescent" ~ PGA,
      TRUE ~ DISEASE_ACTIVITY
    )) %>%
    rename(!!paste("DISEASE_ACTIVITY", t, sep = "_") := DISEASE_ACTIVITY)



  # ===============================
  # REORDER COLUMNS
  # ===============================




  cohort <- cohort %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    setNames(gsub(" ", "_", names(.)))






  # FOR OMICS & BIOSAMPLE ADD WHOLE TABLE IN


  if ("OMICS" %in% index_info) {
    cohort <- omics %>% left_join(cohort, by = c("DEIDENTIFIED_MASTER_PATIENT_ID", "index_date" = "INDEX_DATE"))
  } else if ("BIOSAMPLE" %in% index_info) {
    cohort <- biosample %>% left_join(cohort, by = c("DEIDENTIFIED_MASTER_PATIENT_ID", "index_date" = "INDEX_DATE"))
  } else {
    cohort <- cohort
  }



  cohort <- cohort %>%
    distinct() %>%
    setNames((gsub("\\(|\\)|\\-|\\'|\\.", " ", names(.)))) %>%
    setNames((gsub("  ", " ", names(.)))) %>%
    setNames((gsub("^ *| *$", "", names(.)))) %>%
    setNames((gsub(" ", "_", names(.))))

  names(cohort) <- toupper(names(cohort))


  # ===============================
  # CREATE HEADER STYLES
  # ===============================
  # blue
  style1 <- createStyle(bgFill = "#BDD7EE", textDecoration = "bold")



  # ===============================
  # CREATE WORKBOOK
  # ===============================

  wb <- createWorkbook()
  addWorksheet(wb, "scores_at_index")
  writeData(wb, "scores_at_index", x = cohort, startCol = 1, startRow = 1, colNames = TRUE, rowNames = FALSE)

  # ===============================
  # FORMAT CELLS
  # ===============================

  rown <- dim(cohort)[1]
  coln <- dim(cohort)[2]

  # column headers
  conditionalFormatting(wb, "scores_at_index", cols = 1:coln, rows = 1, rule = "!=0", style = style1)


  # ===============================
  # SAVE REPORT
  # ===============================
  saveWorkbook(wb, file = paste0(filename), overwrite = TRUE)
  return(cohort)
}
