#' sparc_medication_enrollment
#'
#' Finds the medications the participant is prescribed from the
#' electronic medical record and patient reported case report forms at enrollment.
#'
#' @param cohort dataframe with index_date
#' @param med dataframe generated by sparc_med_starts() function
#'
#' @return A dataframe and an excel file.

#'
sparc_medication_enrollment <- function(cohort, med) {
  # MEDICATIONS AT ENROLLMENT ----

  med_enroll <- med %>%
    mutate(index_date = DATE_OF_CONSENT) %>%
    mutate(int = MED_START_DATE_ECRF %--% MED_END_DATE_ECRF) %>%
    rowwise() %>%
    mutate(ON_MED = case_when(
      index_date %within% int ~ 1,
      is.na(MED_END_DATE_ECRF) & (index_date >= MED_START_DATE_ECRF) ~ 1,
      TRUE ~ 0
    )) %>%
    ungroup() %>%
    distinct() %>%
    filter(ON_MED == 1) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, MOA) %>%
    slice(which.max(MED_START_DATE)) %>%
    pivot_wider(
      id_cols = c("DEIDENTIFIED_MASTER_PATIENT_ID", "index_date"),
      names_from = ON_MED,
      values_from = c(MEDICATION),
      values_fn = function(x) paste(x, collapse = "; ")
    ) %>%
    rename(MEDICATION_AT_INDEX = `1`)

  cohort <- cohort %>% left_join(med_enroll)


  med_enroll_dates <- med %>%
    mutate(index_date = DATE_OF_CONSENT) %>%
    mutate(int = MED_START_DATE_ECRF %--% MED_END_DATE_ECRF) %>%
    rowwise() %>%
    mutate(ON_MED = case_when(
      index_date %within% int ~ 1,
      is.na(MED_END_DATE_ECRF) & (index_date >= MED_START_DATE_ECRF) ~ 1,
      TRUE ~ 0
    )) %>%
    ungroup() %>%
    distinct() %>%
    filter(ON_MED == 1) %>%
    pivot_wider(
      id_cols = c("DEIDENTIFIED_MASTER_PATIENT_ID", "index_date"),
      names_from = MEDICATION,
      values_from = c(MED_START_DATE_ECRF, MED_END_DATE_ECRF, MED_START_DATE_EMR, MED_END_DATE_EMR, CURRENT_MEDICATION)
    )


  cohort <- cohort %>% left_join(med_enroll_dates)


  # Bionaive at enrollment

  bionaive <- med %>%
    mutate(index_date = DATE_OF_CONSENT) %>%
    mutate(int = MED_START_DATE_ECRF %--% MED_END_DATE_ECRF) %>%
    rowwise() %>%
    mutate(ON_MED = case_when(
      index_date %within% int ~ 1,
      is.na(MED_END_DATE_ECRF) & (index_date >= MED_START_DATE_ECRF) ~ 1,
      TRUE ~ 0
    )) %>%
    ungroup() %>%
    distinct() %>%
    filter(ON_MED == 1) %>%
    drop_na(BIONAIVE) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>%
    slice(which.min(BIONAIVE)) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, index_date, BIONAIVE) %>%
    ungroup()

  cohort <- cohort %>% left_join(bionaive)

  # NO MEDICATION AT ENROLLMENT

  no_med <- med %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, NO_CURRENT_IBD_MEDICATION_AT_ENROLLMENT)

  cohort <- cohort %>% left_join(no_med)


  return(cohort)
}
