# steroid_filter
#' For SPARC, this function further filters the steroid data to remove inhalation, nasal, eye drops and ointments.
#'
#' @param medication A dataframe generated by sparc_med_filter()
#'
#' @return A filtered data frame like the one procuded by sparc_med_filter()
#'
#'
steroid_filter <- function(medication){

  medication %>%
    mutate(new_med_name = case_when(grepl("foam", MEDICATION_NAME, ignore.case = T) ~ "Steroid Foam", TRUE ~ new_med_name)) %>%
    mutate(drop = case_when(tolower(ROUTE_OF_MEDICATION) %in% c('affected eye(s)',
                                                              'affected eyes',
                                                              'both eyes',
                                                              'each eye',
                                                              'each nostril',
                                                              'eye (left)',
                                                              'eye (right)',
                                                              'eyes (each)',
                                                              'hhn',
                                                              'inhalation',
                                                              'inhaled nebulizer',
                                                              'left eye',
                                                              'nasal',
                                                              'nebulization',
                                                              'nostril (each)',
                                                              'ophthalmic',
                                                              'ophthalmic (eye)',
                                                              'right ear',
                                                              'right eye') ~ 1,
                          tolower(MED_FORM) %in% c('aero powd breath activated',
                                                   'aerosol',
                                                   'aerosol powder breath activated',
                                                   'aerosol powder, breath activated',
                                                   'aerosol powdr breath activated',
                                                   'drops',
                                                   'drops, suspension',
                                                   'drops,suspension',
                                                   'gel',
                                                   'hfa aerosol inhaler',
                                                   'spray,non-aerosol',
                                                   'suspension for nebulization') ~ 1,
                          tolower(MED_QUANTITY_UOM) %in% c('ampule',
                                                           'box',
                                                           'inhaler',
                                                           'puff') ~ 1,
                          grepl("nasal|inhalation|NASL", SRC_DRUG_CODE_CONCEPT_NAME, ignore.case = T) ~ 1,
                          toupper(MEDICATION_TREATMENT_COURSE) == "EENT PREPS" ~ 1,
                          TRUE ~ 0)) %>%
  filter(drop == 0) %>%
  select(-drop) %>%
    mutate(new_med_name = ifelse(new_med_name == "Steroids Oral", "Steroids Oral eCRF", new_med_name))

}


#' steroid_use
#'
#' For SPARC, this function finds if a patient was on steroid at the time of
#' another medication in the medication journey. Steroid information must have
#' MED_START_DATE and MED_END_DATE or MED_DISCONT_START_DATE. Inhalation, eye drops and nasal
#' routes of administration removed.
#'
#' @param prescriptions A dataframe with prescriptions data usually generated using load_data.
#' @param demographics a dataframe with demographic data usually generated using load_data.
#' @param observations a dataframe with observations data usually generated using load_data.
#' @param encounter A dataframe with encounter data usually generated using load_data.
#' @param med A dataframe generated by joining the results from med_start() and med_end()
#'
#' @return A dataframe with the master patient id, data source, medication name, original dose and any doses reported over time for that source.
#'
#'

steroid_use <- function(prescriptions, observations, demographics, encounter, med) {

  steroid <- sparc_med_filter(prescriptions, observations, demographics, encounter, med_groups = "Corticosteroids")


  mj_steroid <- steroid %>%
    mutate(MED_DISCONT_START_DATE = dmy(MED_DISCONT_START_DATE)) %>%
    mutate(MED_END_DATE = if_else(is.na(MED_END_DATE), MED_DISCONT_START_DATE, MED_END_DATE)) %>%
    filter(!is.na(MED_START_DATE) & !is.na(MED_END_DATE)) %>%
    mutate(steroid_int = MED_START_DATE %--% MED_END_DATE) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, steroid_int, new_med_name) %>%
    left_join(med) %>%
    drop_na(MEDICATION) %>%
    mutate(int = MED_START_DATE %--% MED_END_DATE) %>%
    mutate(o = int_overlaps(steroid_int, int)) %>%
    filter(o == TRUE) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, MEDICATION, MED_START_DATE, MED_END_DATE, new_med_name) %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, MEDICATION, MED_START_DATE) %>%
    mutate(c = 1) %>%
    ungroup() %>%
    pivot_wider(names_from = new_med_name, values_from = c) %>%
    rowwise() %>%
    mutate(Budesonide = ifelse("Budesonide" %in% names(.), Budesonide, NA),
           Methylprednisolone = ifelse("Methylprednisolone" %in% names(.), Methylprednisolone, NA),
           Prednisolone = ifelse("Prednisolone" %in% names(.), Prednisolone, NA),
           Prednisone = ifelse("Prednisone" %in% names(.), Prednisone, NA),
           `Steroid Enema` = ifelse("Steroid Enema" %in% names(.), `Steroid Enema`, NA),
           `Steroid Foam` = ifelse("Steroid Foam" %in% names(.), `Steroid Foam`, NA),
           `Steroid Suppository` = ifelse("Steroid Suppository" %in% names(.), `Steroid Suppository`, NA),
           `Steroids Oral eCRF` = ifelse("Steroids Oral eCRF" %in% names(.), `Steroids Oral eCRF`, NA)) %>%
    mutate(ANY_STEROID = ifelse(rowSums(across(where(is.numeric)), na.rm=TRUE) > 0, 1, 0),
           RECTAL_STEROID = ifelse(`Steroid Foam` == 1 | `Steroid Enema` == 1 | `Steroid Suppository` == 1, 1, 0),
           ORAL_IV_STEROID = ifelse(`Steroids Oral eCRF` == 1 | `Methylprednisolone` == 1 | `Budesonide` == 1| Prednisone == 1 | Prednisolone == 1 , 1, 0)) %>%
    ungroup()


return(mj_steroid)

}

#' steroid_use_at_index
#'
#' For SPARC, this function finds if a patient was on steroid at index date. Steroid information must have
#' MED_START_DATE and MED_END_DATE or MED_DISCONT_START_DATE. Inhalation, eye drops and nasal
#' routes of administration removed.
#'
#' @param data A list of dataframes, typically generated by a call to load_data. Must include demographics, diagnosis, encounter, procedures, observations, biosample, omics_patient_mapping, and prescriptions.
#' @param cohort A dataframe generated by sparc_medication
#'
#' @return A dataframe with the master patient id, data source, medication name, original dose and any doses reported over time for that source.
#'
#'

steroid_use_at_index <- function(data, cohort) {

  steroid <- sparc_med_filter(data$prescriptions, data$observations, data$demographics, data$encounter, med_groups = "Corticosteroids")


  on_steroid <- steroid %>%
    mutate(MED_DISCONT_START_DATE = dmy(MED_DISCONT_START_DATE)) %>%
    mutate(MED_END_DATE = if_else(is.na(MED_END_DATE), MED_DISCONT_START_DATE, MED_END_DATE)) %>%
    filter(!is.na(MED_START_DATE) & !is.na(MED_END_DATE)) %>%
    mutate(steroid_int = MED_START_DATE %--% MED_END_DATE) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, steroid_int, new_med_name) %>%
    left_join(cohort %>% distinct(DEIDENTIFIED_MASTER_PATIENT_ID, index_date)) %>%
    drop_na(index_date) %>%
    mutate(o = if_else(index_date %within% steroid_int, 1, 0)) %>%
    filter(o == 1) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID,index_date, new_med_name,o) %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, index_date) %>%
    ungroup() %>%
    pivot_wider(names_from = new_med_name, values_from = o) %>%
    rowwise() %>%
    mutate(Budesonide = ifelse("Budesonide" %in% names(.), Budesonide, NA),
           Methylprednisolone = ifelse("Methylprednisolone" %in% names(.), Methylprednisolone, NA),
           Prednisolone = ifelse("Prednisolone" %in% names(.), Prednisolone, NA),
           Prednisone = ifelse("Prednisone" %in% names(.), Prednisone, NA),
           `Steroid Enema` = ifelse("Steroid Enema" %in% names(.), `Steroid Enema`, NA),
           `Steroid Foam` = ifelse("Steroid Foam" %in% names(.), `Steroid Foam`, NA),
           `Steroid Suppository` = ifelse("Steroid Suppository" %in% names(.), `Steroid Suppository`, NA),
           `Steroids Oral eCRF` = ifelse("Steroids Oral eCRF" %in% names(.), `Steroids Oral eCRF`, NA)) %>%
    mutate(ANY_STEROID_AT_INDEX = ifelse(rowSums(across(where(is.numeric)), na.rm=TRUE) > 0, 1, 0),
           RECTAL_STEROID_AT_INDEX = ifelse(`Steroid Foam` == 1 | `Steroid Enema` == 1 | `Steroid Suppository` == 1, 1, 0),
           ORAL_IV_STEROID_AT_INDEX = ifelse(`Steroids Oral eCRF` == 1 | `Methylprednisolone` == 1 | `Budesonide` == 1| Prednisone == 1 | Prednisolone == 1 , 1, 0)) %>%
             ungroup()

  return(on_steroid)

}


