# tx_response
#' Create Treatment Response Table - all responses
#'
#' @param data A list of dataframes, typically generated by a call to load_data. Must include demographics, diagnosis, encounter, procedures, observations, biosample, omics_patient_mapping, prescriptions and labs.
#' @param reports_path A path to already generated SPARC Reports.
#' @param all_events Defaults to T. Includes all disease activity measure events after a patient starts a medication.
#' @param save_path the name of the desired output file. Must be .xlsx.
#' @param time_category Defaults to F. Set to T when only disease activity measures from a specified time range are required.
#' @param month_range Month for time frame of interest, after medication start date. Defaults to 12 months.
#' @param month_interest Range of months around month of interest for which to include relevant disease activity measures. Defaults to 3 months.
#' @param filtered_med Defaults to F. Set to T to filter only for specific medications.
#' @param med_interest String of medications separated by | to search for when filtered_med = T. Possible medications are: Adalimumab, Azathioprine, Balsalazide, Certolizumab Pegol, Cyclosporine, Etrasimod, Golimumab, Guselkumab, Infliximab, Mercaptopurine, Mesalamine, Methotrexate, Mirikizumab, Natalizumab, Olsalazine, Ozanimod, Risankizumab, Sulfasalazine, Tacrolimus, Tofacitinib, Upadacitinib, Ustekinumab, Vedolizumab"
#'
#' @return Tx response data file
#' @export
#'
#' @examples
#' # upload data
#' # data <- load_data(datadir, cohort = "SPARC", domains = "ALL", data_type = "both")
#' # get treatment response values for patients on Tofacitinib and Upadacitinib 12 months after medication start date, with 3 month range
#' # jaki_12mo_txresponse <- tx_response(data, reports_path = "~/REPORTS/", all_events = F, save_path = "JAKI_12MO_TX_RESPONSE.xlsx", time_category = T, month_range = 3, month_interest = 12, filtered_med = T, med_interest = "Tofacitinib|Upadacitinib")

tx_response <- function(data,
                        reports_path,
                        all_events = T,
                        save_path = "TX_RESPONSE.xlsx",
                        time_category = F,
                        month_range = 3,
                        month_interest = 12,
                        filtered_med = F,
                        med_interest = "Adalimumab|Certolizumab Pegol|Etrasimod|Golimumab|Guselkumab|Infliximab|Mirikizumab|Natalizumab||Ozanimod|Risankizumab|Tofacitinib|Upadacitinib|Ustekinumab|Vedolizumab") {

  #### Read in required report paths below ----
   # update params with more detail on reports, etc.

  # update to remove internal data load code
   reports_path <- folder_fix(reports_path)

  file.list <- list.files(path = reports_path, pattern = "\\.xlsx$", full.names = T)

  if (!any(grepl("_REPORTS", unlist(file.list)))) {

    ##  Read in summary endoscopy
    sum_endo_suffix <- "SPARC_SUMMARY_ENDOSCOPY.xlsx"

    # Find the file that ends with your target suffix
    matching_file_se <- file.list[grepl(paste0("-", sum_endo_suffix, "$"), file.list)]

    # Get file information for data extract date
    file_details <- file.info(matching_file_se)

    # Extract the creation time (ctime), to use later
    creation_date <- as.Date(file_details$ctime)


    # Check and read the file
    if (length(matching_file_se) == 1) {
      summary_endoscopy <- read_excel(matching_file_se, guess_max = 1048576)
    } else {
      stop("No summary endoscopy file found in specified reports path.")
    }

    ##  Read in medication journey
    mj_prefix <- "SPARC_medication_journey_"

    # Find the file that ends with your target suffix
    matching_file_mj <- file.list[grepl(paste0("/", mj_prefix, ".*\\.xlsx$"), file.list)]

    # Check and read the file
    if (length(matching_file_mj) == 1) {
      med_journey <- read_excel(matching_file_mj, guess_max = 1048576)
    } else {
      stop("No medication journey file found in specified reports path.")
    }

    ## read in all other reports
    reports <- load_sparc_reports(report_path = reports_path,
                                  reports = c("Medication", "score"), time = "enrollment"
    )

    # make all reports into factored levels
    pga <- reports$SPARC_SCORES$pga %>%
      mutate(OG_PGA = PGA) %>%
      mutate(PGA = ifelse(PGA == "Quiescent", "Remission", "> Remission"))

    scdai <- reports$SPARC_SCORES$scdai %>%
      filter(!is.na(SCDAI_SCORE)) %>%
      mutate(SCDAI_CATEGORY = ifelse(SCDAI_CATEGORY == "Remission", "Remission", "> Remission"))

    ucdai6 <- reports$SPARC_SCORES$ucdai %>%
      filter(!is.na(UCDAI_6_SCORE)) %>%
      mutate(UCDAI6_CATGEORY2 = ifelse(UCDAI6_CATEGORY == "Remission", "Remission", "> Remission")) %>%
      select(-UCDAI6_CATEGORY)

    ucdai6 <- ucdai6 %>%
      rename(UCDAI6_CATEGORY = UCDAI6_CATGEORY2)

    ucdai6$UCDAI6_CATEGORY <- factor(ucdai6$UCDAI6_CATEGORY, levels = c('Remission', '> Remission'), ordered = TRUE)

    scdai$SCDAI_CATEGORY <- factor(scdai$SCDAI_CATEGORY, levels = c('Remission', '> Remission'), ordered = TRUE)

    pga$PGA <- factor(pga$PGA, levels = c('Remission', '> Remission'), ordered = TRUE)

  } else {

    ##  Read in REPORTS
    reports_suffix <- "_REPORTS.xlsx"

    # Find the file that ends with your target suffix
    matching_file <- file.list[grepl(paste0(reports_suffix, "$"), file.list)]

    # Get file information for data extract date
    file_details <- file.info(matching_file)

    # Extract the creation time (ctime), to use later
    creation_date <- as.Date(file_details$ctime)


    # Check and read the file
    if (length(matching_file) == 1) {
      summary_endoscopy <- read_excel(matching_file, guess_max = 1048576, sheet = "SUMMARY_ENDOSCOPY")
    } else {
      stop("No summary endoscopy file found in specified reports path.")
    }

    # read in medication journey

    # Check and read the file
    if (length(matching_file) == 1) {
      med_journey <- read_excel(matching_file, guess_max = 1048576, sheet = "MED_JOURNEY")
    } else {
      stop("No medication journey file found in specified reports path.")
    }

    ## read in all other reports

    ##  Read in REPORTS
    reports_suffix <- "_SCORES.xlsx"

    # Find the file that ends with your target suffix
    matching_file <- file.list[grepl(paste0(reports_suffix, "$"), file.list)]

    # add in stop if file/tab not available

    # make all reports into factored levels
    pga1 <- read_excel(matching_file, guess_max = 1048576, sheet = "pga")
    pga <- pga1 %>%
      mutate(OG_PGA = PGA) %>%
      mutate(PGA = ifelse(PGA == "Quiescent", "Remission", "> Remission"))

    scdai1 <- read_excel(matching_file, guess_max = 1048576, sheet = "scdai")
    scdai <- scdai1 %>%
      filter(!is.na(SCDAI_SCORE)) %>%
      mutate(SCDAI_CATEGORY = ifelse(SCDAI_CATEGORY == "Remission", "Remission", "> Remission"))


    ucdai <- read_excel(matching_file, guess_max = 1048576, sheet = "ucdai")
    ucdai6 <- ucdai %>%
      filter(!is.na(UCDAI_6_SCORE)) %>%
      mutate(UCDAI6_CATGEORY2 = ifelse(UCDAI6_CATEGORY == "Remission", "Remission", "> Remission")) %>%
      select(-UCDAI6_CATEGORY)

    ucdai6 <- ucdai6 %>%
      rename(UCDAI6_CATEGORY = UCDAI6_CATGEORY2)

    ucdai6$UCDAI6_CATEGORY <- factor(ucdai6$UCDAI6_CATEGORY, levels = c('Remission', '> Remission'), ordered = TRUE)

    scdai$SCDAI_CATEGORY <- factor(scdai$SCDAI_CATEGORY, levels = c('Remission', '> Remission'), ordered = TRUE)

    pga$PGA <- factor(pga$PGA, levels = c('Remission', '> Remission'), ordered = TRUE)

  }


  #### Create diagnosis table ----
  # possible use scores diagnosis tab
  diagnosis <- extract_diagnosis(data$diagnosis, data$encounter, data$demographics, "SPARC")

  # left join diagnosis table to med journey table
  med_journey <- med_journey %>%
    left_join(diagnosis, by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID))

  #### Create summary endoscopy factor levels ----
  #### Plan to incorporate pouchoscopy scores in the future


  summary_endoscopy_filtered <- summary_endoscopy %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, INDEX_DATE, ENDO_DATE, ENDO_CATEGORY) %>%
    filter(!is.na(ENDO_CATEGORY)) %>%
    mutate(ENDO_CATEGORY = ifelse(ENDO_CATEGORY == "Remission", "Remission", "> Remission"))

  summary_endoscopy_filtered$ENDO_CATEGORY <- factor(summary_endoscopy_filtered$ENDO_CATEGORY, levels = c('Remission', '> Remission'), ordered = TRUE)

  #### filter for endoscopy Crohn's Disease template ----
  cd_ENDO <- med_journey  %>%
    filter(DIAGNOSIS == "Crohn's Disease") %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, MEDICATION, MED_START_DATE, MED_END_DATE) %>%
    left_join(summary_endoscopy_filtered, by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID), relationship = "many-to-many") %>%
  mutate(MED_END_DATE_DEL = if_else(!is.na(MED_END_DATE), MED_END_DATE, creation_date)) %>%
    mutate(MED_INTERVAL = interval(MED_START_DATE, MED_END_DATE_DEL)) %>%
    select(-MED_END_DATE_DEL) %>%
    mutate(ENDO_DURING = if_else(ENDO_DATE %within% MED_INTERVAL, 1, 0)) %>%
    filter(ENDO_DURING == 1) %>%
    left_join(summary_endoscopy %>% select(DEIDENTIFIED_MASTER_PATIENT_ID, ENDO_DATE, SES_SCORE),
              by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID, ENDO_DATE)) %>%
    mutate(DISEASE_ACTIVITY_MEASURE = "SES Score") %>%
    mutate(DIAGNOSIS = "Crohn's Disease") %>%
    mutate(TIME_BETWEEN = difftime(ENDO_DATE, MED_START_DATE, units = "days")) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, DIAGNOSIS, MEDICATION, MED_START_DATE,
           MED_END_DATE, DISEASE_ACTIVITY_MEASURE, TIME_BETWEEN, SES_SCORE, ENDO_CATEGORY, ENDO_DATE) %>%
    rename(ABS_OUTCOME_VALUE = SES_SCORE) %>%
    distinct()

  #### filter for endoscopy Ulcerative Colitis template ----
  uc_ENDO <- med_journey  %>%
    filter(DIAGNOSIS == "Ulcerative Colitis") %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, MEDICATION, MED_START_DATE, MED_END_DATE) %>%
    left_join(summary_endoscopy_filtered, by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID), relationship = "many-to-many") %>%
  mutate(MED_END_DATE_DEL = if_else(!is.na(MED_END_DATE), MED_END_DATE, creation_date)) %>%
    mutate(MED_INTERVAL = interval(MED_START_DATE, MED_END_DATE_DEL)) %>%
    select(-MED_END_DATE_DEL) %>%
    mutate(ENDO_DURING = if_else(ENDO_DATE %within% MED_INTERVAL, 1, 0)) %>%
    filter(ENDO_DURING == 1) %>%
    left_join(summary_endoscopy %>% select(DEIDENTIFIED_MASTER_PATIENT_ID, ENDO_DATE, MAYO_ENDOSCOPY_SCORE),
              by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID, ENDO_DATE)) %>%
    mutate(DISEASE_ACTIVITY_MEASURE = "Mayo Endoscopic Score") %>%
    mutate(DIAGNOSIS = "Ulcerative Colitis") %>%
    mutate(TIME_BETWEEN = difftime(ENDO_DATE, MED_START_DATE, units = "days")) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, DIAGNOSIS, MEDICATION, MED_START_DATE,
           MED_END_DATE, DISEASE_ACTIVITY_MEASURE, TIME_BETWEEN, MAYO_ENDOSCOPY_SCORE, ENDO_CATEGORY, ENDO_DATE) %>%
    rename(ABS_OUTCOME_VALUE = MAYO_ENDOSCOPY_SCORE) %>%
    distinct()

  #### filter UC UCDAI scores ----
  uc_UCDAI <- med_journey %>%
    filter(DIAGNOSIS == "Ulcerative Colitis") %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, MEDICATION, MED_START_DATE, MED_END_DATE) %>%
    left_join(ucdai6, by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID), relationship = "many-to-many") %>%
  mutate(MED_END_DATE_DEL = if_else(!is.na(MED_END_DATE), MED_END_DATE, creation_date)) %>%
    mutate(MED_INTERVAL = interval(MED_START_DATE, MED_END_DATE_DEL)) %>%
    select(-MED_END_DATE_DEL) %>%
    mutate(UCDAI_DURING = if_else(UCDAI_DATE %within% MED_INTERVAL, 1, 0)) %>%
    filter(UCDAI_DURING == 1) %>%
    filter(!is.na(UCDAI_6_SCORE)) %>%
    mutate(DISEASE_ACTIVITY_MEASURE = "UCDAI 6") %>%
    mutate(DIAGNOSIS = "Ulcerative Colitis") %>%
    mutate(TIME_BETWEEN = difftime(UCDAI_DATE, MED_START_DATE, units = "days")) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, DIAGNOSIS, MEDICATION, MED_START_DATE,
           MED_END_DATE, DISEASE_ACTIVITY_MEASURE, TIME_BETWEEN,
           UCDAI_6_SCORE, UCDAI6_CATEGORY, UCDAI_DATE) %>%
    rename(ABS_OUTCOME_VALUE = UCDAI_6_SCORE) %>%
    rename(SCORE_CATEGORY = UCDAI6_CATEGORY)

  #### filter CD SCDAI scores ----
  cd_SCDAI <- med_journey %>%
    filter(DIAGNOSIS == "Crohn's Disease") %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, MEDICATION, MED_START_DATE, MED_END_DATE) %>%
    left_join(scdai, by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID), relationship = "many-to-many") %>%
  mutate(MED_END_DATE_DEL = if_else(!is.na(MED_END_DATE), MED_END_DATE, creation_date)) %>%
    mutate(MED_INTERVAL = interval(MED_START_DATE, MED_END_DATE_DEL)) %>%
    select(-MED_END_DATE_DEL) %>%
    mutate(SCDAI_DURING = if_else(SCDAI_DATE %within% MED_INTERVAL, 1, 0)) %>%
    filter(SCDAI_DURING == 1) %>%
    filter(!is.na(SCDAI_SCORE)) %>%
    mutate(DISEASE_ACTIVITY_MEASURE = "SCDAI Score") %>%
    mutate(DIAGNOSIS = "Crohn's Disease") %>%
    mutate(TIME_BETWEEN = difftime(SCDAI_DATE, MED_START_DATE, units = "days")) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, DIAGNOSIS, MEDICATION, MED_START_DATE,
           MED_END_DATE, DISEASE_ACTIVITY_MEASURE, TIME_BETWEEN,
           SCDAI_SCORE, SCDAI_CATEGORY, SCDAI_DATE) %>%
    rename(ABS_OUTCOME_VALUE = SCDAI_SCORE) %>%
    rename(SCORE_CATEGORY = SCDAI_CATEGORY)

  #### PGA dates ----
  cd_PGA <- med_journey %>%
    filter(DIAGNOSIS == "Crohn's Disease") %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, MEDICATION, MED_START_DATE, MED_END_DATE) %>%
    left_join(pga, by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID), relationship = "many-to-many") %>%
  mutate(MED_END_DATE_DEL = if_else(!is.na(MED_END_DATE), MED_END_DATE, creation_date)) %>%
    mutate(MED_INTERVAL = interval(MED_START_DATE, MED_END_DATE_DEL)) %>%
    select(-MED_END_DATE_DEL) %>%
    mutate(PGA_DURING = if_else(PGA_DATE %within% MED_INTERVAL, 1, 0)) %>%
    filter(PGA_DURING == 1) %>%
    filter(!is.na(PGA)) %>%
    mutate(DISEASE_ACTIVITY_MEASURE = "PGA Score") %>%
    mutate(DIAGNOSIS = "Crohn's Disease") %>%
    mutate(TIME_BETWEEN = difftime(PGA_DATE, MED_START_DATE, units = "days")) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, DIAGNOSIS, MEDICATION,
           MED_START_DATE, MED_END_DATE, DISEASE_ACTIVITY_MEASURE, TIME_BETWEEN,
           OG_PGA, PGA, PGA_DATE) %>%
    rename(ABS_OUTCOME_VALUE = OG_PGA) %>%
    rename(SCORE_CATEGORY = PGA)

  uc_PGA <- med_journey %>%
    filter(DIAGNOSIS == "Ulcerative Colitis") %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, MEDICATION, MED_START_DATE, MED_END_DATE) %>%
    left_join(pga, by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID), relationship = "many-to-many") %>%
  mutate(MED_END_DATE_DEL = if_else(!is.na(MED_END_DATE), MED_END_DATE, creation_date)) %>%
    mutate(MED_INTERVAL = interval(MED_START_DATE, MED_END_DATE_DEL)) %>%
    select(-MED_END_DATE_DEL) %>%
    mutate(PGA_DURING = if_else(PGA_DATE %within% MED_INTERVAL, 1, 0)) %>%
    filter(PGA_DURING == 1) %>%
    filter(!is.na(PGA)) %>%
    mutate(DISEASE_ACTIVITY_MEASURE = "PGA Score") %>%
    mutate(DIAGNOSIS = "Ulcerative Colitis") %>%
    mutate(TIME_BETWEEN = difftime(PGA_DATE, MED_START_DATE, units = "days")) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, DIAGNOSIS, MEDICATION,
           MED_START_DATE, MED_END_DATE, DISEASE_ACTIVITY_MEASURE, TIME_BETWEEN,
           OG_PGA, PGA, PGA_DATE) %>%
    rename(ABS_OUTCOME_VALUE = OG_PGA) %>%
    rename(SCORE_CATEGORY = PGA)


  #### FIND AND CLEAN CRP and FCAL ----

  crp <- extract_lab_emr(data,labtype="CRP",codetype="ALL")
  fcal <- extract_lab_emr(data,labtype="FCAL",codetype="ALL")

  fcal_clean <- fcal_active_clean(fcal, data$labs) %>%
    mutate(FCAL_ACTIVE = ifelse(FCAL_ACTIVE == "INDETERMINATE", "ACTIVE",  FCAL_ACTIVE))

  fcal_clean$FCAL_ACTIVE <- factor(fcal_clean$FCAL_ACTIVE, levels = c('INACTIVE', 'ACTIVE'), ordered = TRUE)

  crp_clean <- crp_active_clean(crp, data$labs)

  crp_cleaned1 <- crp %>% mutate(drop = ifelse(is.na(test_unit_cln) &
                                                 lab_result_cln != "LOWER LIMIT", 1, 0)) %>%
    mutate(test_unit_cln = ifelse(test_unit_cln == "MILLIGRAMS PER DECILTER", "MG/DL", test_unit_cln)) %>%
    mutate(drop = ifelse(lab_result_cln == "LOWER LIMIT" | lab_result_cln == "UPPER LIMIT", 0, drop))%>%
    mutate(drop = ifelse(test_unit_cln !=  "MG/DL" & test_unit_cln != "MG/L", 1, drop)) %>%
    filter(drop != 1) %>% select(-drop) %>%
    mutate(CRP_ACTIVE = ifelse(lab_result_cln ==  "LOWER LIMIT", "INACTIVE", NA)) %>%
    mutate(CRP_ACTIVE = ifelse(lab_result_cln == "UPPER LIMIT", "ACTIVE", CRP_ACTIVE)) %>%
    mutate(lab_result_cln_numeric = as.numeric(lab_result_cln)) %>%
    mutate(lab_result_cln_numeric = ifelse(test_unit_cln == "MG/DL", lab_result_cln_numeric * 10, lab_result_cln_numeric)) %>%
    mutate(lab_result_cln_numeric = as.numeric(lab_result_cln_numeric)) %>%
    mutate(CRP_ACTIVE = ifelse(lab_result_cln_numeric <
                                 8 & is.na(CRP_ACTIVE), "INACTIVE", CRP_ACTIVE)) %>%
    mutate(CRP_ACTIVE = ifelse(is.na(CRP_ACTIVE), "ACTIVE", CRP_ACTIVE)) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, lab_result_cln_numeric,
             SPECIMEN_COLLECTION_DATE, CRP_ACTIVE) %>%
    mutate(CRP_SPECIMEN_COLLECTION_DATE = dmy(SPECIMEN_COLLECTION_DATE)) %>%
    select(-SPECIMEN_COLLECTION_DATE) %>% mutate(CRP_SOURCE = "EMR")

  crp_central_lab <- data$labs %>% filter(LAB_TEST_CONCEPT_CODE ==
                                            "hsCRP (mg/L)") %>%
    rename(lab_result_cln_numeric = TEST_RESULT_NUMERIC)

  crp_cleaned2 <- crp_central_lab %>%
    mutate(lab_result_cln_numeric = as.numeric(lab_result_cln_numeric)) %>%
    mutate(CRP_ACTIVE = ifelse(lab_result_cln_numeric <
                                 8, "INACTIVE", NA)) %>% mutate(CRP_ACTIVE = ifelse(is.na(CRP_ACTIVE),
                                                                                    "ACTIVE", CRP_ACTIVE)) %>% mutate(CRP_SPECIMEN_COLLECTION_DATE = dmy(SPECIMEN_COLLECTION_DATE)) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, CRP_SPECIMEN_COLLECTION_DATE,
             CRP_ACTIVE, lab_result_cln_numeric) %>% mutate(CRP_SOURCE = "CENTRAL LAB") %>%
    rbind(crp_cleaned1) %>%
    rename(lab_result_cln = lab_result_cln_numeric)


  crp_clean <- crp_cleaned2


  crp_clean$CRP_ACTIVE <- factor(crp_clean$CRP_ACTIVE, levels = c('INACTIVE', 'ACTIVE'), ordered = TRUE)

  fcal_cleaned1 <- fcal %>% mutate(test_unit_cln = ifelse(test_unit_cln ==
                                                            "MCG/G" | test_unit_cln == "UG/GRAM" | test_unit_cln ==
                                                            "UG/GRAM OF STOOL" | test_unit_cln == "MCG/GM" | test_unit_cln ==
                                                            "MCG.GM" | test_unit_cln == "MG/KG", "UG/G", test_unit_cln)) %>%
    mutate(FCAL_ACTIVE = ifelse(lab_result_cln == "LOWER LIMIT",
                                "INACTIVE", NA)) %>% mutate(FCAL_ACTIVE = ifelse(lab_result_cln ==
                                                                                   "UPPER LIMIT", "ACTIVE", FCAL_ACTIVE)) %>% mutate(lab_result_cln_numeric = as.numeric(lab_result_cln)) %>%
    mutate(FCAL_ACTIVE = ifelse(lab_result_cln_numeric <
                                  50 & is.na(FCAL_ACTIVE) & test_unit_cln == "UG/G",
                                "INACTIVE", FCAL_ACTIVE)) %>% mutate(FCAL_ACTIVE = ifelse(lab_result_cln_numeric >=
                                                                                            50 & lab_result_cln_numeric <= 200 & is.na(FCAL_ACTIVE) &
                                                                                            test_unit_cln == "UG/G", "INDETERMINATE", FCAL_ACTIVE)) %>%
    mutate(FCAL_ACTIVE = ifelse(lab_result_cln_numeric >
                                  200 & is.na(FCAL_ACTIVE) & test_unit_cln == "UG/G",
                                "ACTIVE", FCAL_ACTIVE)) %>% distinct(DEIDENTIFIED_MASTER_PATIENT_ID,
                                                                     SPECIMEN_COLLECTION_DATE, FCAL_ACTIVE, lab_result_cln) %>% filter(!is.na(FCAL_ACTIVE)) %>%
    mutate(FCAL_SPECIMEN_COLLECTION_DATE = dmy(SPECIMEN_COLLECTION_DATE)) %>%
    select(-SPECIMEN_COLLECTION_DATE) %>% mutate(FCAL_SOURCE = "EMR") %>%
    ungroup()

  fcal_central_lab <- data$labs %>%
    #### NOTE: UPDATE TO ACCOUNT FOR CHANGES IN HOW LAB_TST_CONCEPT_CODE FROM EXTRACT TO EXTACT ----
  filter(DATA_SOURCE != "EMR") %>%
    filter(grepl("1:50 dilution", LAB_TEST_CONCEPT_CODE, ignore.case = T))

  fcal_cleaned <- fcal_central_lab %>% ungroup() %>%
    mutate(TEST_RESULT_NUMERIC = as.numeric(TEST_RESULT_NUMERIC)) %>%
    mutate(FCAL_ACTIVE = ifelse(TEST_RESULT_NUMERIC < 50, "INACTIVE", NA)) %>%
    mutate(FCAL_ACTIVE = ifelse(TEST_RESULT_NUMERIC >=
                                  50 & TEST_RESULT_NUMERIC <= 200 & is.na(FCAL_ACTIVE),
                                "INDETERMINATE", FCAL_ACTIVE)) %>% mutate(FCAL_ACTIVE = ifelse(TEST_RESULT_NUMERIC >
                                                                                                 200 & is.na(FCAL_ACTIVE), "ACTIVE", FCAL_ACTIVE)) %>%
    mutate(FCAL_SPECIMEN_COLLECTION_DATE = dmy(SPECIMEN_COLLECTION_DATE)) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, FCAL_SPECIMEN_COLLECTION_DATE,
             FCAL_ACTIVE, TEST_RESULT_NUMERIC) %>% mutate(FCAL_SOURCE = "CENTRAL LAB") %>%
    rename(lab_result_cln = TEST_RESULT_NUMERIC) %>%
    rbind(fcal_cleaned1)



  #### filter CRP and FCAL ----
  cd_CRP <- med_journey %>%
    filter(DIAGNOSIS == "Crohn's Disease") %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, MEDICATION, MED_START_DATE, MED_END_DATE) %>%
    left_join(crp_clean, by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID), relationship = "many-to-many") %>%
  mutate(MED_END_DATE_DEL = if_else(!is.na(MED_END_DATE), MED_END_DATE, creation_date)) %>%
    mutate(MED_INTERVAL = interval(MED_START_DATE, MED_END_DATE_DEL)) %>%
    select(-MED_END_DATE_DEL) %>%
    mutate(CRP_DURING = if_else(CRP_SPECIMEN_COLLECTION_DATE %within% MED_INTERVAL, 1, 0)) %>%
    filter(CRP_DURING == 1) %>%
    filter(!is.na(CRP_ACTIVE)) %>%
    mutate(DISEASE_ACTIVITY_MEASURE = "CRP Score") %>%
    mutate(DIAGNOSIS = "Crohn's Disease") %>%
    mutate(TIME_BETWEEN = difftime(CRP_SPECIMEN_COLLECTION_DATE, MED_START_DATE, units = "days")) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, DIAGNOSIS, MEDICATION, MED_START_DATE, MED_END_DATE,
           CRP_SPECIMEN_COLLECTION_DATE, DISEASE_ACTIVITY_MEASURE, TIME_BETWEEN,
           lab_result_cln, CRP_ACTIVE) %>%
    rename(ABS_OUTCOME_VALUE = lab_result_cln) %>%
    rename(SCORE_CATEGORY = CRP_ACTIVE)

  uc_CRP <- med_journey %>%
    filter(DIAGNOSIS == "Ulcerative Colitis") %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, MEDICATION, MED_START_DATE, MED_END_DATE) %>%
    left_join(crp_clean, by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID), relationship = "many-to-many") %>%
  mutate(MED_END_DATE_DEL = if_else(!is.na(MED_END_DATE), MED_END_DATE, creation_date)) %>%
    mutate(MED_INTERVAL = interval(MED_START_DATE, MED_END_DATE_DEL)) %>%
    select(-MED_END_DATE_DEL) %>%
    mutate(CRP_DURING = if_else(CRP_SPECIMEN_COLLECTION_DATE %within% MED_INTERVAL, 1, 0)) %>%
    filter(CRP_DURING == 1) %>%
    filter(!is.na(CRP_ACTIVE)) %>%
    mutate(DISEASE_ACTIVITY_MEASURE = "CRP Score") %>%
    mutate(DIAGNOSIS = "Ulcerative Colitis") %>%
    mutate(TIME_BETWEEN = difftime(CRP_SPECIMEN_COLLECTION_DATE, MED_START_DATE, units = "days")) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, DIAGNOSIS, MEDICATION, MED_START_DATE, MED_END_DATE,
           CRP_SPECIMEN_COLLECTION_DATE, DISEASE_ACTIVITY_MEASURE, TIME_BETWEEN,
           lab_result_cln, CRP_ACTIVE) %>%
    rename(ABS_OUTCOME_VALUE = lab_result_cln) %>%
    rename(SCORE_CATEGORY = CRP_ACTIVE)

  cd_FCAL <- med_journey %>%
    filter(DIAGNOSIS == "Crohn's Disease") %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, MEDICATION, MED_START_DATE, MED_END_DATE) %>%
    left_join(fcal_cleaned, by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID), relationship = "many-to-many") %>%
  mutate(MED_END_DATE_DEL = if_else(!is.na(MED_END_DATE), MED_END_DATE, creation_date)) %>%
    mutate(MED_INTERVAL = interval(MED_START_DATE, MED_END_DATE_DEL)) %>%
    select(-MED_END_DATE_DEL) %>%
    mutate(FCAL_DURING = if_else(FCAL_SPECIMEN_COLLECTION_DATE %within% MED_INTERVAL, 1, 0)) %>%
    filter(FCAL_DURING == 1) %>%
    filter(!is.na(FCAL_ACTIVE)) %>%
    mutate(DISEASE_ACTIVITY_MEASURE = "FCAL Score") %>%
    mutate(DIAGNOSIS = "Crohn's Disease") %>%
    mutate(TIME_BETWEEN = difftime(FCAL_SPECIMEN_COLLECTION_DATE, MED_START_DATE, units = "days")) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, DIAGNOSIS, MEDICATION, MED_START_DATE, MED_END_DATE,
           FCAL_SPECIMEN_COLLECTION_DATE, DISEASE_ACTIVITY_MEASURE, TIME_BETWEEN,
           lab_result_cln, FCAL_ACTIVE) %>%
    rename(ABS_OUTCOME_VALUE = lab_result_cln) %>%
    rename(SCORE_CATEGORY = FCAL_ACTIVE) %>%
    filter(SCORE_CATEGORY != "INDETERMINATE")


  uc_FCAL <- med_journey %>%
    filter(DIAGNOSIS == "Ulcerative Colitis") %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, MEDICATION, MED_START_DATE, MED_END_DATE) %>%
    left_join(fcal_cleaned, by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID), relationship = "many-to-many") %>%
  mutate(MED_END_DATE_DEL = if_else(!is.na(MED_END_DATE), MED_END_DATE, creation_date)) %>%
    mutate(MED_INTERVAL = interval(MED_START_DATE, MED_END_DATE_DEL)) %>%
    select(-MED_END_DATE_DEL) %>%
    mutate(FCAL_DURING = if_else(FCAL_SPECIMEN_COLLECTION_DATE %within% MED_INTERVAL, 1, 0)) %>%
    filter(FCAL_DURING == 1) %>%
    filter(!is.na(FCAL_ACTIVE)) %>%
    mutate(DISEASE_ACTIVITY_MEASURE = "FCAL Score") %>%
    mutate(DIAGNOSIS = "Ulcerative Colitis") %>%
    mutate(TIME_BETWEEN = difftime(FCAL_SPECIMEN_COLLECTION_DATE, MED_START_DATE, units = "days")) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, DIAGNOSIS, MEDICATION, MED_START_DATE, MED_END_DATE,
           FCAL_SPECIMEN_COLLECTION_DATE, DISEASE_ACTIVITY_MEASURE, TIME_BETWEEN,
           lab_result_cln, FCAL_ACTIVE) %>%
    rename(ABS_OUTCOME_VALUE = lab_result_cln) %>%
    rename(SCORE_CATEGORY = FCAL_ACTIVE) %>%
    filter(SCORE_CATEGORY != "INDETERMINATE")

  #### create all full tables draft
  ALL_FULL_TABLES_DRAFT <- cd_ENDO %>%
    rbind(uc_ENDO) %>%
    rename(SCORE_CATEGORY = ENDO_CATEGORY,
           DATE = ENDO_DATE
    ) %>%
    rbind(uc_UCDAI %>%
            rename(DATE = UCDAI_DATE)) %>%
    rbind(cd_SCDAI %>%
            rename(DATE = SCDAI_DATE)) %>%
    rbind(uc_PGA %>%
            rename(DATE = PGA_DATE)) %>%
    rbind(cd_PGA %>%
            rename(DATE = PGA_DATE)) %>%
    rbind(cd_CRP %>%
            rename(DATE = CRP_SPECIMEN_COLLECTION_DATE)) %>%
    rbind(uc_CRP %>%
            rename(DATE = CRP_SPECIMEN_COLLECTION_DATE)) %>%
    rbind(cd_FCAL %>%
            rename(DATE = FCAL_SPECIMEN_COLLECTION_DATE)) %>%
    rbind(uc_FCAL %>%
            rename(DATE = FCAL_SPECIMEN_COLLECTION_DATE)) %>%
    mutate(ABS_OUTCOME_VALUE = if_else(DISEASE_ACTIVITY_MEASURE == "CRP Score" &
                                         is.na(ABS_OUTCOME_VALUE) & SCORE_CATEGORY == "INACTIVE",
                                       "LOWER LIMIT", ABS_OUTCOME_VALUE)) %>%
    mutate(ABS_OUTCOME_VALUE = if_else(DISEASE_ACTIVITY_MEASURE == "CRP Score" &
                                         is.na(ABS_OUTCOME_VALUE) & SCORE_CATEGORY == "ACTIVE",
                                       "UPPER LIMIT", ABS_OUTCOME_VALUE)) %>%
    rename(INDEX_DATE = DATE)


  #### ADD STEROIDS
  steroid <- sparc_med_filter(data$prescriptions, data$observations,
                              data$demographics, data$encounter, med_groups = "Corticosteroids")

  steroids_on <- steroid %>%
    mutate(MED_DISCONT_START_DATE = dmy(MED_DISCONT_START_DATE)) %>%
    mutate(MED_END_DATE = if_else(is.na(MED_END_DATE), MED_DISCONT_START_DATE, MED_END_DATE)) %>%
    filter(!is.na(MED_START_DATE) & !is.na(MED_END_DATE)) %>%
    mutate(steroid_int = interval(MED_START_DATE, MED_END_DATE)) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, steroid_int, new_med_name,
             MED_START_DATE, MED_END_DATE, DOSE_OF_MEDICATION, UNIT_OF_MEASURE_FOR_MEDICATION,
             MEDICATION_FREQUENCE) %>%
    filter(new_med_name == "Prednisone" | new_med_name == "Budesonide") %>%
    filter(MEDICATION_FREQUENCE != "Every 2 weeks" &
             MEDICATION_FREQUENCE != "Other" | is.na(MEDICATION_FREQUENCE)) %>%
    filter(!str_detect(MEDICATION_FREQUENCE, "[0-9]") | is.na(MEDICATION_FREQUENCE)) %>%
    filter(!is.na(DOSE_OF_MEDICATION)) %>%
    filter(!str_detect(DOSE_OF_MEDICATION, ",")) %>%
    filter(!str_detect(DOSE_OF_MEDICATION, "-")) %>%
    mutate(DOSE_OF_MEDICATION = str_replace(DOSE_OF_MEDICATION, "mg| mg", "")) %>%
    mutate(DOSE_OF_MEDICATION = str_replace(DOSE_OF_MEDICATION, "[/]", "")) %>%
    mutate(DOSE_OF_MEDICATION = str_replace(DOSE_OF_MEDICATION, "day", "")) %>%
    mutate(DOSE_OF_MEDICATION = as.numeric(DOSE_OF_MEDICATION)) %>%
    filter(str_detect(UNIT_OF_MEASURE_FOR_MEDICATION, "mg")) %>%
    mutate(TIME_ON_MED = difftime(MED_END_DATE, MED_START_DATE, units = "days")) %>%
    filter(TIME_ON_MED >= 14) %>%
    select(-c(MED_START_DATE, MED_END_DATE, TIME_ON_MED)) %>%
    mutate(keep = ifelse(new_med_name == "Budesonide" & DOSE_OF_MEDICATION >= 9  |
                           new_med_name == "Prednisone" & DOSE_OF_MEDICATION >= 40, 1, 0)) %>%
    filter(keep == 1) %>%
    select(-keep)


  ALL_FULL_TABLES_STEROIDS <- ALL_FULL_TABLES_DRAFT %>%
    left_join(steroids_on,
              by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID),
              relationship = "many-to-many") %>%
    mutate(STEROID_FLAG = if_else(INDEX_DATE %within% steroid_int, 1, 0)) %>%
    mutate(STEROID_FLAG = ifelse(is.na(STEROID_FLAG), 0, STEROID_FLAG)) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, MEDICATION, MED_START_DATE, MED_END_DATE,
             DISEASE_ACTIVITY_MEASURE, INDEX_DATE, ABS_OUTCOME_VALUE) %>%
    slice(which.max(STEROID_FLAG)) %>%
    ungroup() %>%
    select(-c(steroid_int, new_med_name, DOSE_OF_MEDICATION, UNIT_OF_MEASURE_FOR_MEDICATION,
              MEDICATION_FREQUENCE))

  #### HOSPITALIZATIONS AND SURGERIES
  sf_proc_list <- c(
    "Colon Resection - Ascending Colon", "Colon Resection - Cecum",
    "Colon Resection - Descending Colon", "Colon Resection - Rectum",
    "Colon Resection - Sigmoid", "Colon Resection - Transverse Colon",
    "Colonic Resection", "Complete Colectomy", "Esophageal Surgery",
    "Gastroduodenal Surgery", "IBD Surgeries", "Ileocolonic Resection",
    "Small Bowel Resection", "Small Bowel Resection - Duodenum",
    "Small Bowel Resection - Ileum", "Small Bowel Resection - Jejunum"
  )

  # find all relevant smartform procedures
  SF_procedures <- data$procedures %>%
    filter(DATA_SOURCE == "SF_SPARC") %>%
    # filter(DEIDENTIFIED_MASTER_PATIENT_ID %in% new_user_cohort_ids) %>%
    filter(PROC_CONCEPT_NAME %in% sf_proc_list) %>%
    filter(!is.na(PROC_STATUS_CONCEPT_CODE)) %>%
    left_join(
      data$encounter %>%
        distinct(
          DEIDENTIFIED_MASTER_PATIENT_ID, VISIT_ENCOUNTER_ID,
          VISIT_ENCOUNTER_START_DATE
        ),
      by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID, VISIT_ENCOUNTER_ID)
    ) %>%
    filter(PROC_STATUS_CONCEPT_CODE == "Yes")

  ## SMARTFORM PROCEDURES - NOT HISTORIC
  sf_procedures_mapped <- SF_procedures %>%
    filter(is.na(PROC_START_DATE)) %>%
    filter(PROC_STATUS_CONCEPT_NAME == "Yes") %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, PROC_CONCEPT_NAME, VISIT_ENCOUNTER_START_DATE) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID, VISIT_ENCOUNTER_START_DATE) %>%
    summarise(text = paste(PROC_CONCEPT_NAME, collapse = "; ")) %>%
    ungroup() %>%
    mutate(DEIDENTIFIED_MASTER_PATIENT_ID = as.numeric(DEIDENTIFIED_MASTER_PATIENT_ID)) %>%
    rename(PROC_DATE = VISIT_ENCOUNTER_START_DATE)


  ## CRF surgeries
  #crf_obs_surgeries <- c("Reason for Hospitalization")

  ecrf_obs_surg <- data$observations %>%
    filter(DATA_SOURCE == "ECRF_SPARC") %>%
    filter(OBS_TEST_CONCEPT_NAME == "Surgery Bowel Resection" |
             OBS_TEST_CONCEPT_NAME == "Surgery Performed (IBD-Related)") %>%
    left_join(
      data$encounter %>%
        distinct(
          DEIDENTIFIED_MASTER_PATIENT_ID, VISIT_ENCOUNTER_ID,
          VISIT_ENCOUNTER_START_DATE, TYPE_OF_ENCOUNTER
        ),
      by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID, VISIT_ENCOUNTER_ID)
    ) %>%
    relocate(VISIT_ENCOUNTER_START_DATE, .after = OBS_TEST_CONCEPT_NAME)

  ecrf_obs_surg_clean <- ecrf_obs_surg %>%
    distinct(
      DEIDENTIFIED_MASTER_PATIENT_ID, OBS_TEST_CONCEPT_NAME, TYPE_OF_ENCOUNTER,
      VISIT_ENCOUNTER_START_DATE, DESCRIPTIVE_SYMP_TEST_RESULTS
    )

  ecrf_encounter_surg <- data$encounter %>%
    filter(DATA_SOURCE == "ECRF_SPARC") %>%
    filter( # TYPE_OF_ENCOUNTER == "IBD Procedure Survey" |
      TYPE_OF_ENCOUNTER == "IBD Hospitalization" |
        # TYPE_OF_ENCOUNTER == "IBD Hospitalization Survey" |
        TYPE_OF_ENCOUNTER == "Hospitalization via office visit" |
        TYPE_OF_ENCOUNTER == "IBD Hospitalization via emergency room" |
        TYPE_OF_ENCOUNTER == "Scheduled IBD hospitalization"
    ) %>%
    # filter(TYPE_OF_ENCOUNTER == "Scheduled IBD hospitalization") %>%
    left_join(data$observations,
              by = join_by(
                DEIDENTIFIED_MASTER_PATIENT_ID, DEIDENTIFIED_PATIENT_ID,
                DATA_SOURCE, VISIT_ENCOUNTER_ID
              )
    ) %>%
    filter(grepl("Surgery", OBS_TEST_CONCEPT_NAME, ignore.case = T) |
             grepl("Surgery", DESCRIPTIVE_SYMP_TEST_RESULTS, ignore.case = T))

  ecrf_encounter_surg_clean <- ecrf_encounter_surg %>%
    distinct(
      DEIDENTIFIED_MASTER_PATIENT_ID, OBS_TEST_CONCEPT_NAME, TYPE_OF_ENCOUNTER,
      VISIT_ENCOUNTER_START_DATE, DESCRIPTIVE_SYMP_TEST_RESULTS
    )

  all_ecrf_surg <- ecrf_obs_surg_clean %>%
    rbind(ecrf_encounter_surg_clean) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, VISIT_ENCOUNTER_START_DATE, .keep_all = T)

  # ecrf surgery examples
  # see if needed
  ecrf_obs_surgery1 <- ecrf_obs_surg %>%
    filter(OBS_TEST_CONCEPT_NAME == "Surgery Bowel Resection") %>%
    distinct(
      DEIDENTIFIED_MASTER_PATIENT_ID, OBS_TEST_CONCEPT_NAME, TYPE_OF_ENCOUNTER,
      VISIT_ENCOUNTER_START_DATE, DESCRIPTIVE_SYMP_TEST_RESULTS
    ) %>%
    distinct(DESCRIPTIVE_SYMP_TEST_RESULTS, .keep_all = T) %>%
    mutate(TABLE = "OBSERVATIONS")

  ecrf_obs_surgery2 <- ecrf_obs_surg %>%
    filter(OBS_TEST_CONCEPT_NAME == "Surgery Performed (IBD-Related)") %>%
    distinct(
      DEIDENTIFIED_MASTER_PATIENT_ID, OBS_TEST_CONCEPT_NAME, TYPE_OF_ENCOUNTER,
      VISIT_ENCOUNTER_START_DATE, DESCRIPTIVE_SYMP_TEST_RESULTS
    ) %>%
    distinct(DESCRIPTIVE_SYMP_TEST_RESULTS, .keep_all = T) %>%
    mutate(TABLE = "OBSERVATIONS")

  ecrf_enc_surg_ex <- ecrf_encounter_surg %>%
    distinct(
      DEIDENTIFIED_MASTER_PATIENT_ID, OBS_TEST_CONCEPT_NAME, TYPE_OF_ENCOUNTER,
      VISIT_ENCOUNTER_START_DATE, DESCRIPTIVE_SYMP_TEST_RESULTS
    ) %>%
    distinct(DESCRIPTIVE_SYMP_TEST_RESULTS, TYPE_OF_ENCOUNTER, OBS_TEST_CONCEPT_NAME,
             .keep_all = T
    ) %>%
    mutate(TABLE = "ENCOUNTER")

  all_ecrf_surg_examples <- ecrf_obs_surgery1 %>%
    rbind(ecrf_obs_surgery2) %>%
    rbind(ecrf_enc_surg_ex) %>%
    mutate(flag = ifelse(OBS_TEST_CONCEPT_NAME == "Reason for CD Related Surgery" |
                           OBS_TEST_CONCEPT_NAME == "Reason for UC Related Surgery", 1, NA)) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>%
    fill(flag, .direction = "updown") %>%
    mutate(S = n()) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, VISIT_ENCOUNTER_START_DATE, .keep_all = T)


  all_surgeries <- all_ecrf_surg %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, VISIT_ENCOUNTER_START_DATE) %>%
    rename(PROC_DATE = VISIT_ENCOUNTER_START_DATE) %>%
    rbind(sf_procedures_mapped %>% select(-text)) %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID, PROC_DATE) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>%
    mutate(R = row_number()) %>%
    mutate(R = paste0("PROC_NUM_", R)) %>%
    pivot_wider(id_cols = DEIDENTIFIED_MASTER_PATIENT_ID,
                names_from = R,
                values_from = PROC_DATE)

  ALL_FULL_TABLES_ADD_SURG <- ALL_FULL_TABLES_STEROIDS %>%
    left_join(all_surgeries %>%
                mutate(DEIDENTIFIED_MASTER_PATIENT_ID = as.character(DEIDENTIFIED_MASTER_PATIENT_ID))) %>%
    mutate(MED_INTERVAL = interval(MED_START_DATE, MED_END_DATE)) %>%
    rowwise() %>%
    mutate(
      SURG_ON_MED = {
        # Combine the PROC_NUM dates into a list
        dates <- c_across(starts_with("PROC_NUM_"))
        # Filter dates within the interval and take the earliest if available
        earliest_date <- min(dates[dates %within% MED_INTERVAL], na.rm = TRUE)
        if_else(is.infinite(earliest_date), NA, earliest_date)
      }
    ) %>%
    ungroup() %>%
    select(-c(starts_with("PROC_NUM_")))


  #### hospitalizations

  sf_hosp <- data$observations %>%
    filter(DATA_SOURCE == "SF_SPARC") %>%
    filter(OBS_TEST_CONCEPT_NAME == "Number of days Hospitalized in the past 6 months" |
             OBS_TEST_CONCEPT_NAME == "Number of days Hospitalized in past 12 months") %>%
    mutate(TEST_RESULT_NUMERIC = as.numeric(TEST_RESULT_NUMERIC)) %>%
    filter(TEST_RESULT_NUMERIC > 0) %>%
    distinct(
      DEIDENTIFIED_MASTER_PATIENT_ID, OBS_ID, OBS_TEST_CONCEPT_NAME, TEST_RESULT_NUMERIC,
      OBS_TEST_RESULT_DATE
    ) %>%
    # make date range of interval when the hospitalizations could've been possible
    mutate(INTERVAL = if_else(
      OBS_TEST_CONCEPT_NAME == "Number of days Hospitalized in the past 6 months",
      interval(OBS_TEST_RESULT_DATE %m-% months(6), OBS_TEST_RESULT_DATE),
      interval(OBS_TEST_RESULT_DATE %m-% months(12), OBS_TEST_RESULT_DATE)
    ))

  ## eCRF hospitalizations

  ecrf_hosp <- data$encounter %>%
    filter(DATA_SOURCE == "ECRF_SPARC") %>%
    filter(
      TYPE_OF_ENCOUNTER == "IBD Hospitalization" |
        TYPE_OF_ENCOUNTER == "Hospitalization via office visit" |
        TYPE_OF_ENCOUNTER == "IBD Hospitalization via emergency room" |
        TYPE_OF_ENCOUNTER == "Scheduled IBD hospitalization"
    ) %>%
    mutate(DEIDENTIFIED_MASTER_PATIENT_ID = as.numeric(DEIDENTIFIED_MASTER_PATIENT_ID)) %>%
    select(DEIDENTIFIED_MASTER_PATIENT_ID, #  ECRF_HOSPITAL_FLAG, # MEDICATION, INDEX_DATE,
           VISIT_ENCOUNTER_START_DATE, VISIT_ENCOUNTER_END_DATE) %>%
    rename(
      ADMISSION_DATE = VISIT_ENCOUNTER_START_DATE,
      DISCHARGE_DATE = VISIT_ENCOUNTER_END_DATE
    ) %>%
    mutate(ECRF_HOSPITAL_FLAG = TRUE)


  # EMR
  # Find inpatient encounters from the EMR by looking at those with
  # admission date, link to diagnosis and see if related to ibd

  ibd <- emr_extract_diagnosis(
    data = data,
    inclusion = "CUSTOM",
    custominc = c("K50|K51|K52")
  )

  # EMR In Patient Admissions ---
  emr_hosp_enc <- data$encounter %>%
    filter(DATA_SOURCE == "EMR") %>%
    drop_na(ADMISSION_DATE) %>%
    filter(as.numeric(LENGTH_OF_STAY) > 0) %>%
    # IBD diagnosis associated with encounter
    inner_join(ibd$diagnosis) %>%
    filter(ADMISSION_TYPE_NAME %in% c("Inpatient") | TYPE_OF_ENCOUNTER == "Inpatient") %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID,
             # MEDICATION, INDEX_DATE,
             ADMISSION_DATE, DISCHARGE_DATE)


  emr_hosp_proc <- data$procedures %>%
    filter(DATA_SOURCE == "EMR") %>%
    filter(PROC_CONCEPT_NAME == "Admit To Inpatient") %>%
    left_join(data$encounter) %>%
    filter(as.numeric(LENGTH_OF_STAY) > 0) %>%
    # IBD diagnosis associated with encounter
    inner_join(ibd$diagnosis) %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID,
             ADMISSION_DATE, DISCHARGE_DATE)

  emr_hosp <- bind_rows(emr_hosp_enc, emr_hosp_proc) %>%
    distinct() %>%
    mutate(EMR_HOSPITAL_FLAG = 1) %>%
    mutate(
      ADMISSION_DATE = dmy(ADMISSION_DATE),
      DISCHARGE_DATE = dmy(DISCHARGE_DATE)
    )

  hospitalizations <- bind_rows(ecrf_hosp %>% mutate(DEIDENTIFIED_MASTER_PATIENT_ID = as.character(DEIDENTIFIED_MASTER_PATIENT_ID)), emr_hosp) %>%
    rowwise() %>%
    mutate(HOSPITAL_FLAG = sum(ECRF_HOSPITAL_FLAG, EMR_HOSPITAL_FLAG, na.rm = T)) %>%
    ungroup() %>%
    mutate(HOSPITAL_SOURCE = case_when(
      ECRF_HOSPITAL_FLAG == 1 ~ "ECRF",
      EMR_HOSPITAL_FLAG == 1 ~ "EMR",
      TRUE ~ as.character(NA)
    )) %>%
    select(-ECRF_HOSPITAL_FLAG, -EMR_HOSPITAL_FLAG) %>%
    distinct() %>%
    arrange(DEIDENTIFIED_MASTER_PATIENT_ID) %>% # , INDEX_DATE) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID # ,
             # INDEX_DATE, MEDICATION
    ) %>%
    mutate(c = seq_along(DEIDENTIFIED_MASTER_PATIENT_ID)) %>%
    ungroup() %>%
    pivot_wider(
      id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID), # , INDEX_DATE, MEDICATION),
      names_from = c,
      values_from = c(ADMISSION_DATE, DISCHARGE_DATE, HOSPITAL_SOURCE)
    ) %>%
    mutate(HOSPITAL_FLAG = 1)

  ALL_FULL_TABLES_ADD_HOSP <- ALL_FULL_TABLES_ADD_SURG %>%
    left_join(hospitalizations %>%
                mutate(DEIDENTIFIED_MASTER_PATIENT_ID = as.character(DEIDENTIFIED_MASTER_PATIENT_ID))) %>%
    rowwise() %>%
    mutate(
      HOSP_ON_MED = {
        # Combine the PROC_NUM dates into a list
        dates <- c_across(starts_with("ADMISSION_DATE_"))
        # Filter dates within the interval and take the earliest if available
        earliest_date <- min(dates[dates %within% MED_INTERVAL], na.rm = TRUE)
        if_else(is.infinite(earliest_date), NA, earliest_date)
      }
    ) %>%
    ungroup() %>%
    select(-c(starts_with("ADMISSION_DATE"),
              starts_with("DISCHARGE_DATE"),
              starts_with("HOSPITAL_SOURCE"))) %>%
    select(-HOSPITAL_FLAG)



  #### INDUCTION
  ALL_FULL_TABLES_INDUCTION <- ALL_FULL_TABLES_ADD_HOSP  %>%
    mutate(TIME_ON_MED = if_else(!is.na(MED_END_DATE), difftime(MED_END_DATE, MED_START_DATE, units = "days"),
                                 difftime(creation_date, MED_START_DATE, units = "days"))) %>%
    mutate(FAIL_INDUCTION_FLAG = case_when(MEDICATION == "Tofacitinib" & TIME_ON_MED < 56 |
                                             MEDICATION == "Ustekinumab" & TIME_ON_MED < 56 |
                                             MEDICATION == "Risankizumab" & TIME_ON_MED < 56 |
                                             MEDICATION == "Upadacitinib" & TIME_ON_MED < 56 ~ 1,
                                           str_detect(MEDICATION, "Adalimumab") & TIME_ON_MED < 28 ~ 1,
                                           str_detect(MEDICATION, "Infliximab") & TIME_ON_MED < 98 ~ 1,
                                           MEDICATION == "Golimumab" & TIME_ON_MED < 42 |
                                             MEDICATION == "Vedolizumab" & TIME_ON_MED < 42 ~ 1,
                                           MEDICATION == "Ozanimod" & TIME_ON_MED < 7 ~ 1,
                                           ## check these
                                           MEDICATION == "Natalizumab" & TIME_ON_MED < 84 ~ 1,
                                           MEDICATION == "Certolizumab Pegol" & TIME_ON_MED < 28 ~ 1,

                                           TRUE ~ 0)) %>%

    select(-TIME_ON_MED)

  # Add 'omics data dates ----
  # dates of omics data within 30 and 60 days of outcome date
  # update to be outcome date not index date

  # add blood RNA Seq
  bloodRNA <- data$omics_patient_mapping %>%
    filter(ASSAY_NAME == "Blood RNASeq") %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, ASSAY_NAME, SAMPLE_COLLECTED_DATE) %>%
    mutate(SAMPLE_COLLECTED_DATE = dmy(SAMPLE_COLLECTED_DATE)) %>%
    # mutate(ASSAY_NAME = ifelse(ASSAY_NAME == "Proteomic biomarker panels (Olink)", "Olink", ASSAY_NAME)) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>%
    mutate(R = row_number()) %>%
    mutate(R = paste0(ASSAY_NAME, "_", R)) %>%
    pivot_wider(id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID),
                names_from = R,
                values_from = SAMPLE_COLLECTED_DATE)

  RNA <- data$omics_patient_mapping %>%
    filter(ASSAY_NAME == "RNASeq") %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, ASSAY_NAME, SAMPLE_COLLECTED_DATE) %>%
    mutate(SAMPLE_COLLECTED_DATE = dmy(SAMPLE_COLLECTED_DATE)) %>%
    # mutate(ASSAY_NAME = ifelse(ASSAY_NAME == "Proteomic biomarker panels (Olink)", "Olink", ASSAY_NAME)) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>%
    mutate(R = row_number()) %>%
    mutate(R = paste0(ASSAY_NAME, "_", R)) %>%
    pivot_wider(id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID),
                names_from = R,
                values_from = SAMPLE_COLLECTED_DATE)

  OLINK <- data$omics_patient_mapping %>%
    filter(ASSAY_NAME == "Proteomic biomarker panels (Olink)") %>%
    distinct(DEIDENTIFIED_MASTER_PATIENT_ID, ASSAY_NAME, SAMPLE_COLLECTED_DATE) %>%
    mutate(SAMPLE_COLLECTED_DATE = dmy(SAMPLE_COLLECTED_DATE)) %>%
    mutate(ASSAY_NAME = ifelse(ASSAY_NAME == "Proteomic biomarker panels (Olink)", "Olink", ASSAY_NAME)) %>%
    group_by(DEIDENTIFIED_MASTER_PATIENT_ID) %>%
    mutate(R = row_number()) %>%
    mutate(R = paste0(ASSAY_NAME, "_", R)) %>%
    pivot_wider(id_cols = c(DEIDENTIFIED_MASTER_PATIENT_ID),
                names_from = R,
                values_from = SAMPLE_COLLECTED_DATE)

  # Specify RNAseq in column names
  ALL_FULL_TABLES_RNAOLINK <- ALL_FULL_TABLES_INDUCTION %>%
    left_join(RNA, by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID)) %>%
    mutate(INDEX_RANGE = interval(INDEX_DATE - days(60), INDEX_DATE + days(60))) %>%
    mutate(MED_START_RANGE = interval(MED_START_DATE - days(30), MED_START_DATE)) %>%
    rowwise() %>%
    mutate(
      TISSUE_RNA_60_INDEX = {
        # Combine RNASeq dates into a list
        dates <- c_across(starts_with("RNASeq_"))
        # Remove NA dates
        dates <- dates[!is.na(dates)]
        # Filter dates within the INDEX_RANGE interval
        dates_in_range <- dates[dates %within% INDEX_RANGE]
        # Find the date closest to INDEX_DATE4 if any date is within range
        if (length(dates_in_range) > 0) {
          closest_date <- dates_in_range[which.min(abs(as.numeric(dates_in_range - INDEX_DATE)))]
        } else {
          closest_date <- NA
        }
        closest_date
      }
    ) %>%
    ungroup() %>%
    rowwise() %>%
    mutate(
      TISSUE_RNA_30_MED = {
        # Combine RNASeq dates into a list
        dates <- c_across(starts_with("RNASeq_"))
        # Remove NA dates
        dates <- dates[!is.na(dates)]
        # Filter dates within the INDEX_RANGE interval
        dates_in_range <- dates[dates %within% MED_START_RANGE]
        # Find the date closest to INDEX_DATE4 if any date is within range
        if (length(dates_in_range) > 0) {
          closest_date <- dates_in_range[which.min(abs(as.numeric(dates_in_range - INDEX_DATE)))]
        } else {
          closest_date <- NA
        }
        closest_date
      }
    ) %>%
    ungroup()  %>%
    left_join(OLINK, by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID)) %>%
    rowwise() %>%
    mutate(
      OLINK_60_INDEX = {
        # Combine RNASeq dates into a list
        dates <- c_across(starts_with("Olink_"))
        # Remove NA dates
        dates <- dates[!is.na(dates)]
        # Filter dates within the INDEX_RANGE interval
        dates_in_range <- dates[dates %within% INDEX_RANGE]
        # Find the date closest to INDEX_DATE4 if any date is within range
        if (length(dates_in_range) > 0) {
          closest_date <- dates_in_range[which.min(abs(as.numeric(dates_in_range - INDEX_DATE)))]
        } else {
          closest_date <- NA
        }
        closest_date
      }
    ) %>%
    ungroup() %>%
    rowwise() %>%
    mutate(
      OLINK_30_MED = {
        # Combine RNASeq dates into a list
        dates <- c_across(starts_with("Olink_"))
        # Remove NA dates
        dates <- dates[!is.na(dates)]
        # Filter dates within the INDEX_RANGE interval
        dates_in_range <- dates[dates %within% MED_START_RANGE]
        # Find the date closest to INDEX_DATE4 if any date is within range
        if (length(dates_in_range) > 0) {
          closest_date <- dates_in_range[which.min(abs(as.numeric(dates_in_range - INDEX_DATE)))]
        } else {
          closest_date <- NA
        }
        closest_date
      }
    ) %>%
    ungroup() %>%
    left_join(bloodRNA, by = join_by(DEIDENTIFIED_MASTER_PATIENT_ID)) %>%
    mutate(INDEX_RANGE = interval(INDEX_DATE - days(60), INDEX_DATE + days(60))) %>%
    mutate(MED_START_RANGE = interval(MED_START_DATE - days(30), MED_START_DATE)) %>%
    rowwise() %>%
    mutate(
      BLOOD_RNA_60_INDEX = {
        # Combine RNASeq dates into a list
        dates <- c_across(starts_with("Blood RNASeq_"))
        # Remove NA dates
        dates <- dates[!is.na(dates)]
        # Filter dates within the INDEX_RANGE interval
        dates_in_range <- dates[dates %within% INDEX_RANGE]
        # Find the date closest to INDEX_DATE4 if any date is within range
        if (length(dates_in_range) > 0) {
          closest_date <- dates_in_range[which.min(abs(as.numeric(dates_in_range - INDEX_DATE)))]
        } else {
          closest_date <- NA
        }
        closest_date
      }
    ) %>%
    ungroup() %>%
    rowwise() %>%
    mutate(
      BLOOD_RNA_30_MED = {
        # Combine RNASeq dates into a list
        dates <- c_across(starts_with("Blood RNASeq_"))
        # Remove NA dates
        dates <- dates[!is.na(dates)]
        # Filter dates within the INDEX_RANGE interval
        dates_in_range <- dates[dates %within% MED_START_RANGE]
        # Find the date closest to INDEX_DATE4 if any date is within range
        if (length(dates_in_range) > 0) {
          closest_date <- dates_in_range[which.min(abs(as.numeric(dates_in_range - INDEX_DATE)))]
        } else {
          closest_date <- NA
        }
        closest_date
      }
    ) %>%
    ungroup()

  ALL_FULL_TABLES_FINAL_2.0 <- ALL_FULL_TABLES_RNAOLINK %>%
    #update to do starts_with for olink. May require extra coding above.
    select(-c(starts_with("RNASeq"), starts_with("Blood RNASeq"), Olink_1, Olink_2, Olink_3, Olink_4, INDEX_RANGE, MED_START_RANGE,
              MED_INTERVAL)) %>%
    # mutate(across(where(~inherits(.x, "POSIXct")), as.Date))
    mutate(across(where(is.POSIXct), as.Date))

  # remove score from fcal or crp


  factor_levels <- c("Mayo Endoscopic Score", "UCDAI 6", "SES Score",
                     "SCDAI Score", "PGA Score", "FCAL Score", "CRP Score")

  # maybe want to add earlier in future iteration
  # future may want to make it able to run with just one IBD diagnosis

  if (filtered_med == T) {

    med_interest2 <- paste( unlist(med_interest), collapse='|')

    ALL_FULL_TABLES_FINAL_2.0 <- ALL_FULL_TABLES_FINAL_2.0 %>%
      filter(grepl(med_interest2, MEDICATION, ignore.case = T))

  }

  if (all_events == T) {

    ALL_FULL_TABLES_FINAL_2.0 <- ALL_FULL_TABLES_FINAL_2.0 %>%
      rename(DISEASE_ACTIVITY_MEASURE_DATE = INDEX_DATE)

    ALL_FULL_TABLES_FINAL_ONE <- ALL_FULL_TABLES_FINAL_2.0 %>%
      group_by(DEIDENTIFIED_MASTER_PATIENT_ID, MEDICATION) %>%
      slice(which.min(TIME_BETWEEN)) %>%
      rename(DISEASE_ACTIVITY_MEASURE_DATE = INDEX_DATE)
    # rename ABS_OUTCOME_VALUE to be ABS_DISEASE_ACTIVITY_VALUE

    ALL_FULL_TABLES_FINAL_RIGOR <- ALL_FULL_TABLES_FINAL_2.0 %>%
      group_by(DEIDENTIFIED_MASTER_PATIENT_ID, MEDICATION, MED_START_DATE, MED_END_DATE) %>%
      mutate(DISEASE_ACTIVITY_MEASURE = factor(DISEASE_ACTIVITY_MEASURE, levels = factor_levels)) %>%
      # Select the highest factor level (lowest number)
      slice_min(order_by = DISEASE_ACTIVITY_MEASURE, n = 1) %>%
      ungroup() %>%
      rename(DISEASE_ACTIVITY_MEASURE_DATE = INDEX_DATE)

    # rename INDEX here to reflect MEASURE or DISEASE_ACTIVITY
    dictionary <- data.frame(
      Column_Name = c(
        "DEIDENTIFIED_MASTER_PATIENT_ID", "DIAGNOSIS", "MEDICATION", "MED_START_DATE",
        "MED_END_DATE", "DISEASE_ACTIVITY_MEASURE", "TIME_BETWEEN",
        "ABS_OUTCOME_VALUE", "SCORE_CATEGORY", "DISEASE_ACTIVITY_MEASURE_DATE",
        "FAIL_INDUCTION_FLAG", "STEROID_FLAG", "SURG_ON_MED", "HOSP_ON_MED",
        "TISSUE_RNA_60_INDEX", "TISSUE_RNA_30_MED", "OLINK_60_INDEX", "OLINK_30_MED",
        "BLOOD_RNA_60_INDEX", "BLOOD_RNA_30_MED"

      ),
      Definition = c(
        "Patient ID", "Diagnosis", "Medication", "Med Start Date",
        "Med End Date", "Disease activity measure used in that row",
        "Time between disease activity date and med start date",
        "Value of the disease activity measure", "Specified score category of disease measure",
        "Date of the disease activity measure",
        "Flag if the medication was stopped before the end of the induction period",
        "Flag if index date is during time when patient was also on steroids",
        "Earliest IBD related surgery date after medication start date",
        "Earliest IBD related hospitalization date after medication start date",
        "Date of Tissue RNASeq closest to index date, within +/- 60 days of index date",
        "Date of Tissue RNASeq closest to medication start date, within 30 days prior to medication started",
        "Date of Olink closest to index date, within +/- 60 days of index date",
        "Date of Olink closest to medication start date, within 30 days prior to medication started",
        "Date of Blood RNASeq closest to index date, within +/- 60 days of index date",
        "Date of Blood RNASeq closest to medication start date, within 30 days prior to medication started"
      )
    )

    sheets <- list("ALL SCORES" = ALL_FULL_TABLES_FINAL_2.0,
                   "CLOSEST SCORE" = ALL_FULL_TABLES_FINAL_ONE,
                   "MOST RIGOROUS" = ALL_FULL_TABLES_FINAL_RIGOR,
                   "DICTIONARY" = dictionary
    )
    write_xlsx(sheets, save_path)


  }

  if (time_category == T) {


    ALL_FULL_TABLES_FINAL_2.0_TIME <- ALL_FULL_TABLES_FINAL_2.0 %>%
      mutate(MONTHX = as.Date(MED_START_DATE) %m+% months(month_interest)) %>%
      mutate(MONTHX_START = MONTHX %m-% months(month_range)) %>%
      mutate(MONTHX_END = MONTHX %m+% months(month_range) - days(1)) %>%
      mutate(MONTHX_END_FIX = if_else(!is.na(MED_END_DATE) & MONTHX_END > MED_END_DATE, 1, 0)) %>%
      mutate(MONTHX_END = if_else(MONTHX_END_FIX == 1, MED_END_DATE, MONTHX_END)) %>%
      mutate(POS_INT_FLAG = if_else(!is.na(MED_END_DATE) & MONTHX_START > MED_END_DATE, 1, 0)) %>%
      mutate(MONTHX_INT = interval(MONTHX_START, MONTHX_END))  %>%
      mutate(MONTHX_INT = if_else(POS_INT_FLAG == 1, NA, MONTHX_INT)) %>%
      mutate(DA_DATE = MED_START_DATE + days(TIME_BETWEEN)) %>%
      mutate(IN_RANGE = if_else(DA_DATE %within% MONTHX_INT, 1, 0)) %>%
      filter(IN_RANGE == 1) %>%
      # select(-DA_DATE) %>%
      rename_with(~paste0("MONTH", month_interest, "_INT"), .cols = MONTHX_INT) %>%
      rename_with(~paste0("MONTH", month_interest, "_END"), .cols = MONTHX_END) %>%
      rename_with(~paste0("MONTH", month_interest, "_START"), .cols = MONTHX_START) %>%
      mutate(TIME_CATEGORY = paste0(month_interest, " (+/-", month_range, ") months")) %>%
      select(-INDEX_DATE) %>%
      rename(INDEX_DATE = MONTHX) %>%
      rename(DISEASE_ACTIVITY_MEASURE_DATE = DA_DATE) %>%
      select(-c(IN_RANGE, POS_INT_FLAG, starts_with("MONTH"))) %>%
      relocate(DISEASE_ACTIVITY_MEASURE_DATE, .before = INDEX_DATE)


    ALL_FULL_TABLES_FINAL_ONE_TIME <- ALL_FULL_TABLES_FINAL_2.0_TIME %>%
      group_by(DEIDENTIFIED_MASTER_PATIENT_ID, MEDICATION) %>%
      slice(which.min(TIME_BETWEEN))

    ALL_FULL_TABLES_FINAL_RIGOR_TIME <- ALL_FULL_TABLES_FINAL_2.0_TIME %>%
      group_by(DEIDENTIFIED_MASTER_PATIENT_ID, MEDICATION, MED_START_DATE, MED_END_DATE) %>%
      mutate(DISEASE_ACTIVITY_MEASURE = factor(DISEASE_ACTIVITY_MEASURE, levels = factor_levels)) %>%
      # Select the highest factor level (lowest number)
      slice_min(order_by = DISEASE_ACTIVITY_MEASURE, n = 1) %>%
      ungroup()

    dictionary <- data.frame(
      Column_Name = c(
        "DEIDENTIFIED_MASTER_PATIENT_ID", "DIAGNOSIS", "MEDICATION", "MED_START_DATE",
        "MED_END_DATE", "DISEASE_ACTIVITY_MEASURE", "TIME_BETWEEN",
        "TIME_CATEGORY",
        "ABS_OUTCOME_VALUE", "SCORE_CATEGORY", "DISEASE_ACTIVITY_MEASURE_DATE", "INDEX_DATE",
        "FAIL_INDUCTION_FLAG", "STEROID_FLAG", "SURG_ON_MED", "HOSP_ON_MED",
        "TISSUE_RNA_60_INDEX", "TISSUE_RNA_30_MED", "OLINK_60_INDEX", "OLINK_30_MED",
        "BLOOD_RNA_60_INDEX", "BLOOD_RNA_30_MED"

      ),
      Definition = c(
        "Patient ID", "Diagnosis", "Medication", "Med Start Date",
        "Med End Date", "Disease activity measure used in that row",
        "Time between disease activity date and med start date",
        "Time category of disease activity measures, based on the month of interest and the range of months around it", # nice to have to add time category using paste
        "Value of the disease activity measure", "Specified score category of disease measure",
        "Date of disease activity measure",
        "Date of timepoint of interest (MED_START_DATE + MONTHS_OF_INTEREST)",
        "Flag if the medication was stopped before the end of the induction period",
        "Flag if index date is during time when patient was also on steroids",
        "Earliest IBD related surgery date after medication start date",
        "Earliest IBD related hospitalization date after medication start date",
        "Date of Tissue RNASeq closest to index date, within +/- 60 days of index date",
        "Date of Tissue RNASeq closest to medication start date, within 30 days prior to medication started",
        "Date of Olink closest to index date, within +/- 60 days of index date",
        "Date of Olink closest to medication start date, within 30 days prior to medication started",
        "Date of Blood RNASeq closest to index date, within +/- 60 days of index date",
        "Date of Blood RNASeq closest to medication start date, within 30 days prior to medication started"
      )
    )




    sheets <- list("ALL SCORES" = ALL_FULL_TABLES_FINAL_2.0_TIME,
                   "CLOSEST SCORE" = ALL_FULL_TABLES_FINAL_ONE_TIME,
                   "MOST RIGOROUS" = ALL_FULL_TABLES_FINAL_RIGOR_TIME,
                   "DICTIONARY" = dictionary
    )
    write_xlsx(sheets, save_path)


  }

}
